Preparations:
- load prediction.csv
    - drop the lines with the non-used ifs
    - if there is more then one if, take mean

- add column "sample" to master table
- join them
- drop unnecessary columns (matadata, paths, ranks)

In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import ast
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score, precision_score, f1_score, precision_recall_curve, confusion_matrix

# Configuration
CSV_PATH =  "/home/bri/pymol/data/predictions/preds_snir.csv" 
MASTER_PATH =  "/home/bri/pymol/data/3ab/table/master_table_snir.csv" 
YAML_PATH = "/home/bri/pymol/EDA/static/metric_directions.yaml"
OUTPUT_DIR = Path("/home/bri/pymol/EDA/static/snir_outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


KEEP_INTERFACES = {"A,C", "B,C"}   # as option if there is more than one, default A,B
palette = {"binder": "#2196F3", "ala_scan": "#FF5722"}


# Load data
preds_df = pd.read_csv(CSV_PATH)

preds_df.head()
preds_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 92 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   sample                                  105 non-null    str
 1   binding                                 105 non-null    bool
 2   interface                               105 non-null    str
 3   af3_pae                                 105 non-null    float64
 4   af3_plddt                               105 non-null    float64
 5   af3_interface_dG                        105 non-null    float64
 6   af3_interface_dG_SASA_ratio             105 non-null    float64
 7   af3_ipae                                105 non-null    float64
 8   af3_iplddt                              105 non-null    float64
 9   af3_ipsae                               105 non-null    float64
 10  af3_pdockq                              105 non-null    float64
 11  af3_pdockq2                             105 non-null    float64
 12  af3_lis                                 105 non-null    float64
 13  af3_iptm                                105 non-null    float64
 14  af3_ptm                                 105 non-null    float64
 15  af3_pyros_binder_score                  105 non-null    float64
 16  af3_rank                                105 non-null    float64
 17  af3_ranking_score                       105 non-null    float64
 18  af3_rank0_masif                         34 non-null     float64
 19  cf_af3_rmsd                             105 non-null    float64
 20  cf_pae                                  105 non-null    float64
 21  cf_plddt                                105 non-null    float64
 22  cf_interface_dG                         105 non-null    float64
 23  cf_interface_dG_SASA_ratio              105 non-null    float64
 24  cf_ipae                                 105 non-null    float64
 25  cf_iplddt                               105 non-null    float64
 26  cf_ipsae                                105 non-null    float64
 27  cf_pdockq                               105 non-null    float64
 28  cf_pdockq2                              105 non-null    float64
 29  cf_lis                                  105 non-null    float64
 30  cf_iptm                                 105 non-null    float64
 31  cf_ptm                                  105 non-null    float64
 32  cf_pyros_binder_score                   105 non-null    float64
 33  cf_rank                                 105 non-null    float64
 34  cf_rank0_masif                          37 non-null     float64
 35  pred_ilddt                              105 non-null    float64
 36  pred_lddt                               105 non-null    float64
 37  esmfold_ipae                            37 non-null     float64
 38  esmfold_iplddt                          37 non-null     float64
 39  esmfold_plddt                           105 non-null    float64
 40  esmfold_pae                             105 non-null    float64
 41  esmfold_ptm                             105 non-null    float64
 42  chai_unconstrained_score                105 non-null    float64
 43  chai_unconstrained_model_path           105 non-null    str
 44  chai_constrained_score                  105 non-null    float64
 45  chai_constrained_model_path             105 non-null    str
 46  chai_unconstrained_aggregate_score      105 non-null    float64
 47  chai_unconstrained_ptm                  105 non-null    float64
 48  chai_unconstrained_iptm                 105 non-null    float64
 49  chai_unconstrained_per_chain_ptm        105 non-null    str
 50  chai_unconstrained_per_chain_pair_iptm  105 non-null    str
 51  chai_unconstrained_interface_iptm       105 non-null    float64
 52  chai_unconstrained_ipsae                105 non-null    float64
 53  chai_unconstrained_pdockq               105 non-null    float64
 54  chai_unconstrained_pdockq2              105 non-null    float64
 55  chai_unconstrained_lis                  105 non-null    float64
 56  chai_constrained_aggregate_score        105 non-null    float64
 57  chai_constrained_ptm                    105 non-null    float64
 58  chai_constrained_iptm                   105 non-null    float64
 59  chai_constrained_per_chain_ptm          105 non-null    str
 60  chai_constrained_per_chain_pair_iptm    105 non-null    str
 61  chai_constrained_interface_iptm         35 non-null     float64
 62  chai_constrained_ipsae                  35 non-null     float64
 63  chai_constrained_pdockq                 35 non-null     float64
 64  chai_constrained_pdockq2                35 non-null     float64
 65  chai_constrained_lis                    35 non-null     float64
 66  boltz_free_confidence_score             105 non-null    float64
 67  boltz_free_ptm                          105 non-null    float64
 68  boltz_free_iptm                         105 non-null    float64
 69  boltz_free_plddt                        105 non-null    float64
 70  boltz_free_iplddt                       105 non-null    float64
 71  boltz_free_pde                          105 non-null    float64
 72  boltz_free_ipde                         105 non-null    float64
 73  boltz_free_per_chain_pair_iptm          105 non-null    float64
 74  boltz_free_model_path                   105 non-null    str
 75  boltz_free_ipsae                        105 non-null    float64
 76  boltz_free_pdockq                       105 non-null    float64
 77  boltz_free_pdockq2                      105 non-null    float64
 78  boltz_free_lis                          105 non-null    float64
 79  boltz_template_confidence_score         105 non-null    float64
 80  boltz_template_ptm                      105 non-null    float64
 81  boltz_template_iptm                     105 non-null    float64
 82  boltz_template_plddt                    105 non-null    float64
 83  boltz_template_iplddt                   105 non-null    float64
 84  boltz_template_pde                      105 non-null    float64
 85  boltz_template_ipde                     105 non-null    float64
 86  boltz_template_per_chain_pair_iptm      105 non-null    float64
 87  boltz_template_model_path               105 non-null    str
 88  boltz_template_ipsae                    105 non-null    float64
 89  boltz_template_pdockq                   105 non-null    float64
 90  boltz_template_pdockq2                  105 non-null    float64
 91  boltz_template_lis                      105 non-null    float64
dtypes: bool(1), float64(81), str(10)
memory usage: 74.9 KB

In [85]:
df_if = preds_df[preds_df["interface"].str.strip().isin(KEEP_INTERFACES)].copy()
print(f"Loaded {len(df_if)} rows. Interfaces: {df_if['interface'].unique()}")

df_if.head(10)

Loaded 70 rows. Interfaces: <StringArray>
['A,C', 'B,C']
Length: 2, dtype: str

,sample,binding,interface,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,...,boltz_template_plddt,boltz_template_iplddt,boltz_template_pde,boltz_template_ipde,boltz_template_per_chain_pair_iptm,boltz_template_model_path,boltz_template_ipsae,boltz_template_pdockq,boltz_template_pdockq2,boltz_template_lis
1,5ig7_abc_cut,False,"A,C",2.572969,95.599717,10.97,1.38,2.321875,94.630252,0.780104,...,0.987334,0.987299,0.258769,0.284754,0.948463,/scicore/home/schwede/barta0000/scoring_pipeli...,0.921477,0.2352,0.9699,0.8588
2,5ig7_abc_cut,False,"B,C",2.572969,95.599717,5.13,0.67,1.720000,95.189670,0.790385,...,0.987334,0.987299,0.258769,0.284754,0.956973,/scicore/home/schwede/barta0000/scoring_pipeli...,0.928806,0.2332,0.9688,0.8586
4,5ig7_abc_cut_A_Y66A,False,"A,C",2.572738,95.767986,17.48,2.33,2.219231,94.959764,0.779923,...,0.986631,0.985549,0.257634,0.291466,0.935394,/scicore/home/schwede/barta0000/scoring_pipeli...,0.898429,0.2315,0.9617,0.8487
5,5ig7_abc_cut_A_Y66A,False,"B,C",2.572738,95.767986,0.73,0.10,1.700000,95.167570,0.792646,...,0.986631,0.985549,0.257634,0.291466,0.945723,/scicore/home/schwede/barta0000/scoring_pipeli...,0.907364,0.2149,0.9585,0.8409
7,5ifj_abc_cut_A_S64A,False,"A,C",2.539446,95.613237,23.78,2.92,2.434375,94.266763,0.775252,...,0.984658,0.983850,0.258604,0.295100,0.932908,/scicore/home/schwede/barta0000/scoring_pipeli...,0.892828,0.2290,0.9581,0.8494
8,5ifj_abc_cut_A_S64A,False,"B,C",2.539446,95.613237,5.41,0.70,1.710000,95.361092,0.782671,...,0.984658,0.983850,0.258604,0.295100,0.944936,/scicore/home/schwede/barta0000/scoring_pipeli...,0.904881,0.2280,0.9569,0.8415
10,5ifj_abc_cut_all_A,False,"A,C",3.597543,93.235998,52.47,5.49,2.602632,84.615603,0.216341,...,0.953720,0.922320,0.256769,0.294560,0.943772,/scicore/home/schwede/barta0000/scoring_pipeli...,0.912904,0.1090,0.6813,0.8530
11,5ifj_abc_cut_all_A,False,"B,C",3.597543,93.235998,16.68,4.56,1.806250,82.884986,0.162327,...,0.953720,0.922320,0.256769,0.294560,0.926717,/scicore/home/schwede/barta0000/scoring_pipeli...,0.872455,0.1163,0.6247,0.8453
13,5ig7_abc_cut_B_G114A,False,"A,C",2.436673,95.869087,24.31,3.01,2.137500,95.580074,0.803864,...,0.986487,0.986081,0.256536,0.278153,0.950070,/scicore/home/schwede/barta0000/scoring_pipeli...,0.924004,0.2335,0.9680,0.8583
14,5ig7_abc_cut_B_G114A,False,"B,C",2.436673,95.869087,0.09,0.01,1.631250,95.483511,0.816920,...,0.986487,0.986081,0.256536,0.278153,0.955974,/scicore/home/schwede/barta0000/scoring_pipeli...,0.927049,0.2016,0.9601,0.8512

In [93]:
num_cols = df_if.select_dtypes(include=['number']).columns
other_cols = [c for c in df_if.columns if c not in num_cols and c != 'sample']

agg_dict = {col: 'mean' for col in num_cols}
agg_dict.update({col: 'first' for col in other_cols})

df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

df_1if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,binding,interface,chai_unconstrained_model_path,chai_constrained_model_path,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm,boltz_free_model_path,boltz_template_model_path
0,5ifj_abc_cut,2.593883,95.404666,14.690,1.855,1.993750,95.036725,0.788184,0.20980,0.88085,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9346736073493958, 0.941501259803772]]","[[[0.9346736073493958, 0.8659998178482056], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
1,5ifj_abc_cut_A_D111A,2.815847,95.282854,13.225,1.745,2.100000,94.730775,0.765295,0.18660,0.88195,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.934756338596344, 0.9413727521896362]]","[[[0.934756338596344, 0.8664464950561523], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
2,5ifj_abc_cut_A_K110A,2.790728,94.871984,19.975,2.845,2.275417,92.998114,0.769552,0.18030,0.85065,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9350460767745972, 0.9415807127952576]]","[[[0.9350460767745972, 0.8660252094268799], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
3,5ifj_abc_cut_A_S64A,2.539446,95.613237,14.595,1.810,2.072188,94.813927,0.778962,0.19900,0.88450,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9445436000823975, 0.9495869874954224, 0.17...","[[[0.9445436000823975, 0.8924098014831543, 0.0...","[[0.9345250129699707, 0.9413044452667236]]","[[[0.9345250129699707, 0.8659787178039551], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
4,5ifj_abc_cut_A_W52A,3.005329,94.814333,46.435,5.940,2.303125,91.482646,0.695928,0.19125,0.78185,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9452440142631531, 0.9471760392189026, 0.16...","[[[0.9452440142631531, 0.8792759776115417, 0.0...","[[0.9345828890800476, 0.9411274194717407]]","[[[0.9345828890800476, 0.8663274645805359], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
5,5ifj_abc_cut_A_Y66A,2.701376,95.337838,17.485,2.305,2.249649,93.429048,0.763715,0.19335,0.84245,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9473956227302551, 0.9488828778266907, 0.16...","[[[0.9473956227302551, 0.8850024938583374, 0.0...","[[0.9346519708633423, 0.9413310289382935]]","[[[0.9346519708633423, 0.8664906620979309], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
6,5ifj_abc_cut_B_L116A,2.806607,95.032996,7.610,0.985,2.205952,93.484476,0.747441,0.17235,0.82990,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9485109448432922, 0.9499985575675964, 0.17...","[[[0.9485109448432922, 0.8920019865036011, 0.0...","[[0.9348855018615723, 0.9416057467460632]]","[[[0.9348855018615723, 0.8666328191757202], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
7,5ifj_abc_cut_B_V38A,2.714935,95.220947,15.440,2.000,2.254062,93.465938,0.758796,0.19055,0.85940,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9468277096748352, 0.9472519159317017, 0.10...","[[[0.9468277096748352, 0.8879522085189819, 0.0...","[[0.9348711967468262, 0.9404247403144836]]","[[[0.9348711967468262, 0.8658405542373657], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
8,5ifj_abc_cut_B_W107A,2.878966,95.089607,17.035,2.335,2.471875,93.380576,0.623665,0.16430,0.79175,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9425944089889526, 0.9466992616653442, 0.10...","[[[0.9425944089889526, 0.8834366798400879, 0.0...","[[0.9346067309379578, 0.9413726925849915]]","[[[0.9346067309379578, 0.8661914467811584], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
9,5ifj_abc_cut_B_Y37A,3.004751,94.723352,10.755,1.380,2.298611,92.120377,0.640578,0.17745,0.77900,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.940564751625061, 0.9448128938674927, 0.095...","[[[0.940564751625061, 0.8819113969802856, 0.04...","[[0.9345679879188538, 0.94112229347229]]","[[[0.9345679879188538, 0.8665298819541931], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
10,5ifj_abc_cut_all_A,3.597543,93.235998,34.575,5.025,2.204441,83.750294,0.189334,0.11440,0.33130,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9467074275016785, 0.9420090913772583, 0.11...","[[[0.9467074275016785, 0.8753525018692017, 0.0...","[[0.9341180324554443, 0.9413625597953796]]","[[[0.9341180324554443, 0.8662437200546265], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
11,5ig7_abc_cut,2.572969,95.599717,8.050,1.025,2.020937,94.909961,0.785245,0.20200,0.89390,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9348973035812378, 0.9414625763893127]]","[[[0.9348973035812378, 0.8661490678787231], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
12,5ig7_abc_cut_A_K110A,2.806122,94.950463,16.750,2.340,2.220000,93.355815,0.756785,0.20195,0.85780,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9444799423217773, 0.9482003450393677, 0.09...","[[[0.9444799423217773, 0.8866336941719055, 0.0...","[[0.9339132308959961, 0.9403352737426758]]","[[[0.9339132308959961, 0.8629684448242188], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
13,5ig7_abc_cut_A_W52A,2.731340,95.457781,11.955,1.515,2.111607,93.974962,0.749117,0.21550,0.86160,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9392455220222473, 0.9467980265617371, 0.08...","[[[0.9392455220222473, 0.8777296543121338, 0.0...","[[0.9339661002159119, 0.9405071139335632]]","[[[0.9339661002159119, 0.863102912902832], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
14,5ig7_abc_cut_A_Y66A,2.572738,95.767986,9.105,1.215,1.959615,95.063667,0.786285,0.22025,0.88890,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9482442736625671, 0.9485312104225159, 0.16...","[[[0.9482442736625671, 0.885511040687561, 0.06...","[[0.933533251285553, 0.9410054087638855]]","[[[0.933533251285553, 0.8630070686340332], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
15,5ig7_abc_cut_B_G114A,2.436673,95.869087,12.200,1.510,1.884375,95.531792,0.810392,0.19195,0.90170,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9472417831420898, 0.9477450847625732, 0.09...","[[[0.9472417831420898, 0.8837891817092896, 0.0...","[[0.9332777261734009, 0.9409425854682922]]","[[[0.9332777261734009, 0.8625840544700623], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
16,5ig7_abc_cut_B_L116A,2.697161,95.298420,13.320,1.610,2.129575,93.730328,0.756877,0.19240,0.86445,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9438903331756592, 0.9470524191856384, 0.08...","[[[0.9438903331756592, 0.879470705986023, 0.01...","[[0.934121310710907, 0.9409371614456177]]","[[[0.934121310710907, 0.8623819947242737], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
17,5ig7_abc_cut_B_V38A,2.540938,95.793462,10.800,1.405,2.050536,94.756844,0.776995,0.19930,0.88640,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9432534575462341, 0.9479488134384155, 0.09...","[[[0.9432534575462341, 0.8869456648826599, 0.0...","[[0.9341434836387634, 0.9406449794769287]]","[[[0.9341434836387634, 0.8628303408622742], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
18,5ig7_abc_cut_B_W107A,3.561995,92.830579,128.475,19.540,2.146591,82.977278,0.155861,0.09575,0.32615,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9412914514541626, 0.9472916126251221, 0.09...","[[[0.9412914514541626, 0.8858029842376709, 0.0...","[[0.9343828558921814, 0.9400894045829773]]","[[[0.9343828558921814, 0.8628431558609009], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
19,5ig7_abc_cut_B_Y37A,2.644076,95.631059,15.830,1.985,1.979167,94.594111,0.720382,0.20810,0.85615,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9416530132293701, 0.9461093544960022, 0.09...","[[[0.9416530132293701, 0.8841282725334167, 0.0...","[[0.9334264993667603, 0.9408474564552307]]","[[[0.9334264993667603, 0.8625325560569763], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
20,5ig7_abc_cut_all_A,3.805987,92.210506,56.120,10.050,2.444928,76.576550,0.061503,0.08945,0.17770,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9479871988296509, 0.943764865398407, 0.091...","[[[0.9479871988296509, 0.8801519870758057, 0.0...","[[0.9336056709289551, 0.94100022315979]]","[[[0.9336056709289551, 0.8625383377075195], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
21,5ijk_acx_cut,3.486349,92.439163,26.435,4.765,5.111071,69.144182,0.088382,0.04025,0.18020,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9387028217315674, 0.9485116600990295]]","[[[0.9387028217315674, 0.8840898871421814], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
22,5ijk_acx_cut_A_I112A,2.957804,94.094014,95.960,16.700,2.786161,76.558583,0.112243,0.05660,0.25410,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9419323205947876, 0.9515408277511597, 0.09...","[[[0.9419323205947876, 0.8887308239936829, 0.0...","[[0.9393779635429382, 0.9484520554542542]]","[[[0.9393779635429382, 0.8840246200561523], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
23,5ijk_acx_cut_A_I114A,3.581104,91.142842,68.070,10.490,3.039530,67.753721,0.024187,0.03975,0.06940,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9325439929962158, 0.951015830039978, 0.098...","[[[0.9325439929962158, 0.8848593235015869, 0.0...","[[0.9389991164207458, 0.9490326046943665]]","[[[0.9389991164207458, 0.8846485614776611], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
24,5ijk_acx_cut_A_K57A,3.333153,92.231214,84.570,13.910,3.738864,66.901441,0.023776,0.03760,0.08380,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9351347088813782, 0.9510679841041565, 0.09...","[[[0.9351347088813782, 0.8865579962730408, 0.0...","[[0.9391107559204102, 0.9484051465988159]]","[[[0.9391107559204102, 0.884272038936615], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
25,5ijk_acx_cut_A_R55A,3.411108,91.770396,58.025,9.175,3.270139,64.294001,0.024243,0.03430,0.08470,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9349604845046997, 0.9504574537277222, 0.09...","[[[0.9349604845046997, 0.8808215260505676, 0.0...","[[0.9393128752708435, 0.9482797384262085]]","[[[0.9393128752708435, 0.884563684463501], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
26,5ijk_acx_cut_A_T113A,2.042686,97.319849,-2.805,-0.835,1.473958,97.583035,0.760557,0.09555,0.93485,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9451172947883606, 0.9515537023544312, 0.09...","[[[0.9451172947883606, 0.8881925940513611, 0.0...","[[0.9387825131416321, 0.9486415982246399]]","[[[0.9387825131416321, 0.8834017515182495], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
27,5ijk_acx_cut_B_K36A,3.220014,93.155359,30.100,7.160,3.395000,72.266295,0.067418,0.03880,0.15895,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9357482194900513, 0.9508245587348938, 0.10...","[[[0.9357482194900513, 0.8863149881362915, 0.0...","[[0.9396297335624695, 0.9479048252105713]]","[[[0.9396297335624695, 0.883185088634491], [0....",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
28,5ijk_acx_cut_B_T113A,3.117051,92.444807,30.825,4.280,2.748438,74.341522,0.075896,0.04325,0.15815,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9378942847251892, 0.9510397911071777, 0.11...","[[[0.9378942847251892, 0.8857946395874023, 0.0...","[[0.9389173984527588, 0.9489221572875977]]","[[[0.9389173984527588, 0.8845291137695312], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
29,5ijk_acx_cut_B_W56A,2.382550,96.678663,6.990,0.850,1.701389,95.561703,0.606970,0.08580,0.82670,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9516229033470154, 0.9518455266952515, 0.11...","[[[0.9516229033470154, 0.8881137371063232, 0.0...","[[0.9388806819915771, 0.9481016397476196]]","[[[0.9388806819915771, 0.8838337659835815], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
30,5ijk_acx_cut_B_Y107A,3.163120,93.553850,41.520,7.365,2.214583,72.905361,0.026280,0.04065,0.12810,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9415576457977295, 0.9507483839988708, 0.10...","[[[0.9415576457977295, 0.892025351524353, 0.02...","[[0.9393523335456848, 0.9482724070549011]]","[[[0.9393523335456848, 0.8832361698150635], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
31,5ijk_acx_cut_B_Y108A,3.341985,91.641826,41.775,7.040,3.902778,65.016859,0.024165,0.02670,0.06370,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9349137544631958, 0.950394332408905, 0.093...","[[[0.9349137544631958, 0.8863245248794556, 0.0...","[[0.9389467239379883, 0.9485079050064087]]","[[[0.9389467239379883, 0.8839555978775024], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
32,5ijk_acx_cut_B_Y31A,3.093042,94.546322,49.185,7.655,2.354934,80.447620,0.054126,0.04045,0.30005,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9345048069953918, 0.9514862895011902, 0.09...","[[[0.9345048069953918, 0.8868847489356995, 0.0...","[[0.9390738010406494, 0.9475822448730469]]","[[[0.9390738010406494, 0.8839995265007019], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
33,5ijk_acx_cut_B_Y38A,3.455154,91.808649,84.050,13.855,4.266518,68.727387,0.047625,0.04295,0.12330,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9347723126411438, 0.9516543745994568, 0.09...","[[[0.9347723126411438, 0.8869415521621704, 0.0...","[[0.9397854208946228, 0.9480567574501038]]","[[[0.9397854208946228, 0.8834027647972107], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
34,5ijk_acx_cut_all_A,4.276973,90.392437,55.260,7.055,4.580952,71.830438,0.058250,0.05665,0.08885,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.935025691986084, 0.944311797618866, 0.0957...","[[[0.935025691986084, 0.8839023113250732, 0.02...","[[0.9395022988319397, 0.948574423789978]]","[[[0.9395022988319397, 0.8836830258369446], [0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...

In [97]:
df_2if = df_1if.drop(columns=["chai_unconstrained_model_path", "chai_constrained_model_path", "boltz_free_model_path", "boltz_template_model_path"])
df_2if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,boltz_template_ipsae,boltz_template_pdockq,boltz_template_pdockq2,boltz_template_lis,binding,interface,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm
0,5ifj_abc_cut,2.593883,95.404666,14.690,1.855,1.993750,95.036725,0.788184,0.20980,0.88085,...,0.937455,0.23935,0.96685,0.87115,False,"A,C","[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9346736073493958, 0.941501259803772]]","[[[0.9346736073493958, 0.8659998178482056], [0..."
1,5ifj_abc_cut_A_D111A,2.815847,95.282854,13.225,1.745,2.100000,94.730775,0.765295,0.18660,0.88195,...,0.908519,0.21980,0.92900,0.85605,False,"A,C","[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.934756338596344, 0.9413727521896362]]","[[[0.934756338596344, 0.8664464950561523], [0...."
2,5ifj_abc_cut_A_K110A,2.790728,94.871984,19.975,2.845,2.275417,92.998114,0.769552,0.18030,0.85065,...,0.939275,0.23650,0.96220,0.87810,False,"A,C","[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9350460767745972, 0.9415807127952576]]","[[[0.9350460767745972, 0.8660252094268799], [0..."
3,5ifj_abc_cut_A_S64A,2.539446,95.613237,14.595,1.810,2.072188,94.813927,0.778962,0.19900,0.88450,...,0.898855,0.22850,0.95750,0.84545,False,"A,C","[[0.9445436000823975, 0.9495869874954224, 0.17...","[[[0.9445436000823975, 0.8924098014831543, 0.0...","[[0.9345250129699707, 0.9413044452667236]]","[[[0.9345250129699707, 0.8659787178039551], [0..."
4,5ifj_abc_cut_A_W52A,3.005329,94.814333,46.435,5.940,2.303125,91.482646,0.695928,0.19125,0.78185,...,0.845670,0.21780,0.94175,0.81200,False,"A,C","[[0.9452440142631531, 0.9471760392189026, 0.16...","[[[0.9452440142631531, 0.8792759776115417, 0.0...","[[0.9345828890800476, 0.9411274194717407]]","[[[0.9345828890800476, 0.8663274645805359], [0..."
5,5ifj_abc_cut_A_Y66A,2.701376,95.337838,17.485,2.305,2.249649,93.429048,0.763715,0.19335,0.84245,...,0.892648,0.20680,0.95410,0.83435,False,"A,C","[[0.9473956227302551, 0.9488828778266907, 0.16...","[[[0.9473956227302551, 0.8850024938583374, 0.0...","[[0.9346519708633423, 0.9413310289382935]]","[[[0.9346519708633423, 0.8664906620979309], [0..."
6,5ifj_abc_cut_B_L116A,2.806607,95.032996,7.610,0.985,2.205952,93.484476,0.747441,0.17235,0.82990,...,0.905323,0.21785,0.94930,0.85275,False,"A,C","[[0.9485109448432922, 0.9499985575675964, 0.17...","[[[0.9485109448432922, 0.8920019865036011, 0.0...","[[0.9348855018615723, 0.9416057467460632]]","[[[0.9348855018615723, 0.8666328191757202], [0..."
7,5ifj_abc_cut_B_V38A,2.714935,95.220947,15.440,2.000,2.254062,93.465938,0.758796,0.19055,0.85940,...,0.840146,0.23650,0.94035,0.82200,False,"A,C","[[0.9468277096748352, 0.9472519159317017, 0.10...","[[[0.9468277096748352, 0.8879522085189819, 0.0...","[[0.9348711967468262, 0.9404247403144836]]","[[[0.9348711967468262, 0.8658405542373657], [0..."
8,5ifj_abc_cut_B_W107A,2.878966,95.089607,17.035,2.335,2.471875,93.380576,0.623665,0.16430,0.79175,...,0.851439,0.21350,0.93755,0.83195,False,"A,C","[[0.9425944089889526, 0.9466992616653442, 0.10...","[[[0.9425944089889526, 0.8834366798400879, 0.0...","[[0.9346067309379578, 0.9413726925849915]]","[[[0.9346067309379578, 0.8661914467811584], [0..."
9,5ifj_abc_cut_B_Y37A,3.004751,94.723352,10.755,1.380,2.298611,92.120377,0.640578,0.17745,0.77900,...,0.823940,0.19345,0.89155,0.81210,False,"A,C","[[0.940564751625061, 0.9448128938674927, 0.095...","[[[0.940564751625061, 0.8819113969802856, 0.04...","[[0.9345679879188538, 0.94112229347229]]","[[[0.9345679879188538, 0.8665298819541931], [0..."
10,5ifj_abc_cut_all_A,3.597543,93.235998,34.575,5.025,2.204441,83.750294,0.189334,0.11440,0.33130,...,0.892680,0.11265,0.65300,0.84915,False,"A,C","[[0.9467074275016785, 0.9420090913772583, 0.11...","[[[0.9467074275016785, 0.8753525018692017, 0.0...","[[0.9341180324554443, 0.9413625597953796]]","[[[0.9341180324554443, 0.8662437200546265], [0..."
11,5ig7_abc_cut,2.572969,95.599717,8.050,1.025,2.020937,94.909961,0.785245,0.20200,0.89390,...,0.925142,0.23420,0.96935,0.85870,False,"A,C","[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9348973035812378, 0.9414625763893127]]","[[[0.9348973035812378, 0.8661490678787231], [0..."
12,5ig7_abc_cut_A_K110A,2.806122,94.950463,16.750,2.340,2.220000,93.355815,0.756785,0.20195,0.85780,...,0.929089,0.24685,0.96725,0.86455,False,"A,C","[[0.9444799423217773, 0.9482003450393677, 0.09...","[[[0.9444799423217773, 0.8866336941719055, 0.0...","[[0.9339132308959961, 0.9403352737426758]]","[[[0.9339132308959961, 0.8629684448242188], [0..."
13,5ig7_abc_cut_A_W52A,2.731340,95.457781,11.955,1.515,2.111607,93.974962,0.749117,0.21550,0.86160,...,0.882207,0.22675,0.95025,0.84120,False,"A,C","[[0.9392455220222473, 0.9467980265617371, 0.08...","[[[0.9392455220222473, 0.8777296543121338, 0.0...","[[0.9339661002159119, 0.9405071139335632]]","[[[0.9339661002159119, 0.863102912902832], [0...."
14,5ig7_abc_cut_A_Y66A,2.572738,95.767986,9.105,1.215,1.959615,95.063667,0.786285,0.22025,0.88890,...,0.902896,0.22320,0.96010,0.84480,False,"A,C","[[0.9482442736625671, 0.9485312104225159, 0.16...","[[[0.9482442736625671, 0.885511040687561, 0.06...","[[0.933533251285553, 0.9410054087638855]]","[[[0.933533251285553, 0.8630070686340332], [0...."
15,5ig7_abc_cut_B_G114A,2.436673,95.869087,12.200,1.510,1.884375,95.531792,0.810392,0.19195,0.90170,...,0.925527,0.21755,0.96405,0.85475,False,"A,C","[[0.9472417831420898, 0.9477450847625732, 0.09...","[[[0.9472417831420898, 0.8837891817092896, 0.0...","[[0.9332777261734009, 0.9409425854682922]]","[[[0.9332777261734009, 0.8625840544700623], [0..."
16,5ig7_abc_cut_B_L116A,2.697161,95.298420,13.320,1.610,2.129575,93.730328,0.756877,0.19240,0.86445,...,0.864337,0.23690,0.94355,0.83955,False,"A,C","[[0.9438903331756592, 0.9470524191856384, 0.08...","[[[0.9438903331756592, 0.879470705986023, 0.01...","[[0.934121310710907, 0.9409371614456177]]","[[[0.934121310710907, 0.8623819947242737], [0...."
17,5ig7_abc_cut_B_V38A,2.540938,95.793462,10.800,1.405,2.050536,94.756844,0.776995,0.19930,0.88640,...,0.851071,0.22940,0.94290,0.83475,False,"A,C","[[0.9432534575462341, 0.9479488134384155, 0.09...","[[[0.9432534575462341, 0.8869456648826599, 0.0...","[[0.9341434836387634, 0.9406449794769287]]","[[[0.9341434836387634, 0.8628303408622742], [0..."
18,5ig7_abc_cut_B_W107A,3.561995,92.830579,128.475,19.540,2.146591,82.977278,0.155861,0.09575,0.32615,...,0.852937,0.22970,0.94420,0.83240,False,"A,C","[[0.9412914514541626, 0.9472916126251221, 0.09...","[[[0.9412914514541626, 0.8858029842376709, 0.0...","[[0.9343828558921814, 0.9400894045829773]]","[[[0.9343828558921814, 0.8628431558609009], [0..."
19,5ig7_abc_cut_B_Y37A,2.644076,95.631059,15.830,1.985,1.979167,94.594111,0.720382,0.20810,0.85615,...,0.770047,0.21510,0.91860,0.78060,False,"A,C","[[0.9416530132293701, 0.9461093544960022, 0.09...","[[[0.9416530132293701, 0.8841282725334167, 0.0...","[[0.9334264993667603, 0.9408474564552307]]","[[[0.9334264993667603, 0.8625325560569763], [0..."
20,5ig7_abc_cut_all_A,3.805987,92.210506,56.120,10.050,2.444928,76.576550,0.061503,0.08945,0.17770,...,0.855379,0.24865,0.87545,0.83435,False,"A,C","[[0.9479871988296509, 0.943764865398407, 0.091...","[[[0.9479871988296509, 0.8801519870758057, 0.0...","[[0.9336056709289551, 0.94100022315979]]","[[[0.9336056709289551, 0.8625383377075195], [0..."
21,5ijk_acx_cut,3.486349,92.439163,26.435,4.765,5.111071,69.144182,0.088382,0.04025,0.18020,...,0.906099,0.08775,0.92390,0.82455,False,"A,C","[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9387028217315674, 0.9485116600990295]]","[[[0.9387028217315674, 0.8840898871421814], [0..."
22,5ijk_acx_cut_A_I112A,2.957804,94.094014,95.960,16.700,2.786161,76.558583,0.112243,0.05660,0.25410,...,0.783578,0.07840,0.80560,0.76260,False,"A,C","[[0.9419323205947876, 0.9515408277511597, 0.09...","[[[0.9419323205947876, 0.8887308239936829, 0.0...","[[0.9393779635429382, 0.9484520554542542]]","[[[0.9393779635429382, 0.8840246200561523], [0..."
23,5ijk_acx_cut_A_I114A,3.581104,91.142842,68.070,10.490,3.039530,67.753721,0.024187,0.03975,0.06940,...,0.786085,0.10075,0.78590,0.77635,False,"A,C","[[0.9325439929962158, 0.951015830039978, 0.098...","[[[0.9325439929962158, 0.8848593235015869, 0.0...","[[0.9389991164207458, 0.9490326046943665]]","[[[0.9389991164207458, 0.8846485614776611], [0..."
24,5ijk_acx_cut_A_K57A,3.333153,92.231214,84.570,13.910,3.738864,66.901441,0.023776,0.03760,0.08380,...,0.848387,0.08755,0.86490,0.78115,False,"A,C","[[0.9351347088813782, 0.9510679841041565, 0.09...","[[[0.9351347088813782, 0.8865579962730408, 0.0...","[[0.9391107559204102, 0.9484051465988159]]","[[[0.9391107559204102, 0.884272038936615], [0...."
25,5ijk_acx_cut_A_R55A,3.411108,91.770396,58.025,9.175,3.270139,64.294001,0.024243,0.03430,0.08470,...,0.765977,0.08580,0.80730,0.75905,False,"A,C","[[0.9349604845046997, 0.9504574537277222, 0.09...","[[[0.9349604845046997, 0.8808215260505676, 0.0...","[[0.9393128752708435, 0.9482797384262085]]","[[[0.9393128752708435, 0.884563684463501], [0...."
26,5ijk_acx_cut_A_T113A,2.042686,97.319849,-2.805,-0.835,1.473958,97.583035,0.760557,0.09555,0.93485,...,0.869268,0.11245,0.86970,0.81090,False,"A,C","[[0.9451172947883606, 0.9515537023544312, 0.09...","[[[0.9451172947883606, 0.8881925940513611, 0.0...","[[0.9387825131416321, 0.9486415982246399]]","[[[0.9387825131416321, 0.8834017515182495], [0..."
27,5ijk_acx_cut_B_K36A,3.220014,93.155359,30.100,7.160,3.395000,72.266295,0.067418,0.03880,0.15895,...,0.926195,0.10265,0.93920,0.84055,False,"A,C","[[0.9357482194900513, 0.9508245587348938, 0.10...","[[[0.9357482194900513, 0.8863149881362915, 0.0...","[[0.9396297335624695, 0.9479048252105713]]","[[[0.9396297335624695, 0.883185088634491], [0...."
28,5ijk_acx_cut_B_T113A,3.117051,92.444807,30.825,4.280,2.748438,74.341522,0.075896,0.04325,0.15815,...,0.903611,0.08625,0.90380,0.82980,False,"A,C","[[0.9378942847251892, 0.9510397911071777, 0.11...","[[[0.9378942847251892, 0.8857946395874023, 0.0...","[[0.9389173984527588, 0.9489221572875977]]","[[[0.9389173984527588, 0.8845291137695312], [0..."
29,5ijk_acx_cut_B_W56A,2.382550,96.678663,6.990,0.850,1.701389,95.561703,0.606970,0.08580,0.82670,...,0.914295,0.11150,0.89670,0.83020,False,"A,C","[[0.9516229033470154, 0.9518455266952515, 0.11...","[[[0.9516229033470154, 0.8881137371063232, 0.0...","[[0.9388806819915771, 0.9481016397476196]]","[[[0.9388806819915771, 0.8838337659835815], [0..."
30,5ijk_acx_cut_B_Y107A,3.163120,93.553850,41.520,7.365,2.214583,72.905361,0.026280,0.04065,0.12810,...,0.887658,0.09310,0.89185,0.81230,False,"A,C","[[0.9415576457977295, 0.9507483839988708, 0.10...","[[[0.9415576457977295, 0.892025351524353, 0.02...","[[0.9393523335456848, 0.9482724070549011]]","[[[0.9393523335456848, 0.8832361698150635], [0..."
31,5ijk_acx_cut_B_Y108A,3.341985,91.641826,41.775,7.040,3.902778,65.016859,0.024165,0.02670,0.06370,...,0.901063,0.09325,0.89230,0.81975,False,"A,C","[[0.9349137544631958, 0.950394332408905, 0.093...","[[[0.9349137544631958, 0.8863245248794556, 0.0...","[[0.9389467239379883, 0.9485079050064087]]","[[[0.9389467239379883, 0.8839555978775024], [0..."
32,5ijk_acx_cut_B_Y31A,3.093042,94.546322,49.185,7.655,2.354934,80.447620,0.054126,0.04045,0.30005,...,0.907933,0.10520,0.89815,0.82685,False,"A,C","[[0.9345048069953918, 0.9514862895011902, 0.09...","[[[0.9345048069953918, 0.8868847489356995, 0.0...","[[0.9390738010406494, 0.9475822448730469]]","[[[0.9390738010406494, 0.8839995265007019], [0..."
33,5ijk_acx_cut_B_Y38A,3.455154,91.808649,84.050,13.855,4.266518,68.727387,0.047625,0.04295,0.12330,...,0.917206,0.10130,0.88760,0.83330,False,"A,C","[[0.9347723126411438, 0.9516543745994568, 0.09...","[[[0.9347723126411438, 0.8869415521621704, 0.0...","[[0.9397854208946228, 0.9480567574501038]]","[[[0.9397854208946228, 0.8834027647972107], [0..."
34,5ijk_acx_cut_all_A,4.276973,90.392437,55.260,7.055,4.580952,71.830438,0.058250,0.05665,0.08885,...,0.642768,0.06440,0.30960,0.71245,False,"A,C","[[0.935025691986084, 0.944311797618866, 0.0957...","[[[0.935025691986084, 0.8839023113250732, 0.02...","[[0.9395022988319397, 0.948574423789978]]","[[[0.9395022988319397, 0.8836830258369446], [0..."

## master df

##### snir

In [98]:
# for snir data
master_df = pd.read_csv(MASTER_PATH, delimiter=';')
master_df

,source,type,sample,fab,interface,vh/vl,target,target_residues,target_sequence,binder,KD[M],notes
0,snir_ab,original,5ifj_abc_cut,1000.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
1,snir_ab,original,5ifj_abc_cut,1000.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
2,snir_ab,original,5ig7_abc_cut,10.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
3,snir_ab,original,5ig7_abc_cut,10.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
4,snir_ab,original,5ijk_acx_cut,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,1,0.000001,Fab 1E01 + KD[M] approximated from Snir et. al...
...,...,...,...,...,...,...,...,...,...,...,...,...
65,snir_ab,alanine_scan,5ijk_acx_cut_B_Y108A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
66,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
67,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLASSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
68,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
69,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNALAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN

In [99]:
master_df2 = master_df.drop(columns=["interface", "fab", "vh/vl", "target", "target_residues", "target_sequence", "notes"])
master_df2

     source          type                sample  binder     KD[M]
0   snir_ab      original          5ifj_abc_cut       1  0.000010
1   snir_ab      original          5ifj_abc_cut       1  0.000010
2   snir_ab      original          5ig7_abc_cut       1  0.000100
3   snir_ab      original          5ig7_abc_cut       1  0.000100
4   snir_ab      original          5ijk_acx_cut       1  0.000001
..      ...           ...                   ...     ...       ...
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
66  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
68  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

[70 rows x 5 columns]

In [100]:
master_df3 = master_df2.drop_duplicates(keep="last")
master_df3

     source          type                sample  binder     KD[M]
1   snir_ab      original          5ifj_abc_cut       1  0.000010
3   snir_ab      original          5ig7_abc_cut       1  0.000100
5   snir_ab      original          5ijk_acx_cut       1  0.000001
7   snir_ab  alanine_scan  5ifj_abc_cut_A_D111A       0       NaN
9   snir_ab  alanine_scan  5ifj_abc_cut_A_K110A       0       NaN
11  snir_ab  alanine_scan   5ifj_abc_cut_A_S64A       0       NaN
13  snir_ab  alanine_scan   5ifj_abc_cut_A_W52A       0       NaN
15  snir_ab  alanine_scan   5ifj_abc_cut_A_Y66A       0       NaN
17  snir_ab  alanine_scan    5ifj_abc_cut_all_A       0       NaN
19  snir_ab  alanine_scan  5ifj_abc_cut_B_L116A       0       NaN
21  snir_ab  alanine_scan   5ifj_abc_cut_B_V38A       0       NaN
23  snir_ab  alanine_scan  5ifj_abc_cut_B_W107A       0       NaN
25  snir_ab  alanine_scan   5ifj_abc_cut_B_Y37A       0       NaN
27  snir_ab  alanine_scan  5ig7_abc_cut_A_K110A       0       NaN
29  snir_ab  alanine_scan   5ig7_abc_cut_A_W52A       0       NaN
31  snir_ab  alanine_scan   5ig7_abc_cut_A_Y66A       0       NaN
33  snir_ab  alanine_scan    5ig7_abc_cut_all_A       0       NaN
35  snir_ab  alanine_scan  5ig7_abc_cut_B_G114A       0       NaN
37  snir_ab  alanine_scan  5ig7_abc_cut_B_L116A       0       NaN
39  snir_ab  alanine_scan   5ig7_abc_cut_B_V38A       0       NaN
41  snir_ab  alanine_scan  5ig7_abc_cut_B_W107A       0       NaN
43  snir_ab  alanine_scan   5ig7_abc_cut_B_Y37A       0       NaN
45  snir_ab  alanine_scan  5ijk_acx_cut_A_I112A       0       NaN
47  snir_ab  alanine_scan  5ijk_acx_cut_A_I114A       0       NaN
49  snir_ab  alanine_scan   5ijk_acx_cut_A_K57A       0       NaN
51  snir_ab  alanine_scan   5ijk_acx_cut_A_R55A       0       NaN
53  snir_ab  alanine_scan  5ijk_acx_cut_A_T113A       0       NaN
55  snir_ab  alanine_scan    5ijk_acx_cut_all_A       0       NaN
57  snir_ab  alanine_scan   5ijk_acx_cut_B_K36A       0       NaN
59  snir_ab  alanine_scan  5ijk_acx_cut_B_T113A       0       NaN
61  snir_ab  alanine_scan   5ijk_acx_cut_B_W56A       0       NaN
63  snir_ab  alanine_scan  5ijk_acx_cut_B_Y107A       0       NaN
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

##### mcmahon / germinal

In [80]:
# for snir data
master_df = pd.read_csv(MASTER_PATH, delimiter=';')
master_df.head()

,source,type,vhh,vhh_sequence,target,target_residues,target_sequence,binder,KD[M],EC50[M],notes
0,mcmahon,original,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,HSA,404-609,LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVE...,1,4.310000e-07,NaN,NaN
1,mcmahon,original,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,HSA,404-601,LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVE...,1,4.310000e-07,NaN,NaN
2,mcmahon,original,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,HSA,25-609,DAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFEDHVKLVNEV...,1,4.310000e-07,NaN,NaN
3,mcmahon,original,Nb.AQ100,QVQLQESGGGLVQAGGSLRLSCAASGTIFRVSFMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,1,2.300000e-06,NaN,NaN
4,mcmahon,original,Nb.AQ101,QVQLQESGGGLVQAGGSLRLSCAASGYIFVYAYMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN

In [81]:
def create_sample_id(row):
    vhh = str(row['vhh'])
    target = str(row['target'])
    residues = str(row['target_residues'])
    
    # Check if target is HSA to apply the specific naming convention
    if target == "HSA":
        return f"{vhh}_{target}_{residues}"
    else:
        return f"{vhh}_{target}"

# 1. Create the 'sample' column in the master table
master_df['sample'] = master_df.apply(create_sample_id, axis=1)
master_df

,source,type,vhh,vhh_sequence,target,target_residues,target_sequence,binder,KD[M],EC50[M],notes,sample
0,mcmahon,original,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,HSA,404-609,LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVE...,1,4.310000e-07,NaN,NaN,Nb.b201_HSA_404-609
1,mcmahon,original,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,HSA,404-601,LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVE...,1,4.310000e-07,NaN,NaN,Nb.b201_HSA_404-601
2,mcmahon,original,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,HSA,25-609,DAHKSEVAHRFKDLGEENFKALVLIAFAQYLQQCPFEDHVKLVNEV...,1,4.310000e-07,NaN,NaN,Nb.b201_HSA_25-609
3,mcmahon,original,Nb.AQ100,QVQLQESGGGLVQAGGSLRLSCAASGTIFRVSFMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,1,2.300000e-06,NaN,NaN,Nb.AQ100_Adiponectin
4,mcmahon,original,Nb.AQ101,QVQLQESGGGLVQAGGSLRLSCAASGYIFVYAYMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.AQ101_Adiponectin
5,mcmahon,original,Nb.AQ102,QVQLQESGGGLVQAGGSLRLSCAASGSIFRVAWMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.AQ102_Adiponectin
6,mcmahon,original,Nb.AQ103,QVQLQESGGGLVQAGGSLRLSCAASGSIFAAAYMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,1,5.100000e-07,NaN,NaN,Nb.AQ103_Adiponectin
7,mcmahon,original,Nb.AQ104,QVQLQESGGGLVQAGGSLRLSCAASGYIFPSAVMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.AQ104_Adiponectin
8,mcmahon,original,Nb.AD101,QVQLQESGGGLVQAGGSLRLSCAASGTISPLPAMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.AD101_A2AR
9,mcmahon,original,Nb.AD102,QVQLQESGGGLVQAGGSLRLSCAASGSIFSILSMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,May have reduced binding on freeze/thaw,Nb.AD102_A2AR
10,mcmahon,original,Nb.c200,QVQLQESGGGLVQAGGSLRLSCAASGNISWVYGMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,7.800000e-08,NaN,SPR,Nb.c200_B2AR
11,mcmahon,original,Nb.c201,QVQLQESGGGLVQAGGSLRLSCAASGSISYYSSMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,1.470000e-07,NaN,SPR,Nb.c201_B2AR
12,mcmahon,original,Nb.c202,QVQLQESGGGLVQAGGSLRLSCAASGSISYDGHMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,4.400000e-07,NaN,SPR,Nb.c202_B2AR
13,mcmahon,original,Nb.c203,QVQLQESGGGLVQAGGSLRLSCAASGTIFYDTAMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,1.510000e-07,NaN,SPR,Nb.c203_B2AR
14,mcmahon,original,Nb.c204,QVQLQESGGGLVQAGGSLRLSCAASGTIFGTVLMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,4.900000e-08,EC50 on yeast: 49 nM,Nb.c204_B2AR
15,mcmahon,original,Nb.c205,QVQLQESGGGLVQAGGSLRLSCAASGTISYYYGMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,2.100000e-08,EC50 on yeast: 21 nM,Nb.c205_B2AR
16,mcmahon,original,Nb.c206,QVQLQESGGGLVQAGGSLRLSCAASGYIFITVPMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,7.700000e-08,EC50 on yeast: 77 nM,Nb.c206_B2AR
17,mcmahon,original,Nb.c207,QVQLQESGGGLVQAGGSLRLSCAASGNISYWYYMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,1.040000e-07,EC50 on yeast: 104 nM,Nb.c207_B2AR
18,mcmahon,original,Nb.c208,QVQLQESGGGLVQAGGSLRLSCAASGNIFSYYYMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,5.500000e-08,EC50 on yeast: 55 nM,Nb.c208_B2AR
19,mcmahon,original,Nb.c209,QVQLQESGGGLVQAGGSLRLRCAASGSISVYFFMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,2.400000e-08,EC50 on yeast: 24 nM,Nb.c209_B2AR
20,mcmahon,original,Nb.c210,QVQLQESGGGLVQAGGSLRLSCAASGSIFRQDLMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,2.100000e-06,EC50 on yeast: 2.1 μM,Nb.c210_B2AR
21,mcmahon,original,Nb.c211,QVQLQESGGGLVQAGGSLRLSCAASGSIFGDVDMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,6.200000e-08,EC50 on yeast: 62 nM,Nb.c211_B2AR
22,mcmahon,original,Nb.c212,QVQLQESGGGLVQAGGSLRLSCAASGYIFLRLTMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,1,NaN,2.000000e-08,EC50 on yeast: 20 nM,Nb.c212_B2AR
23,mcmahon,target_shuffle,Nb.b201,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.b201_Adiponectin
24,mcmahon,target_shuffle,Nb.AQ100,QVQLQESGGGLVQAGGSLRLSCAASGTIFRVSFMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.AQ100_A2AR
25,mcmahon,target_shuffle,Nb.AQ101,QVQLQESGGGLVQAGGSLRLSCAASGYIFVYAYMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.AQ101_A2AR
26,mcmahon,target_shuffle,Nb.AQ102,QVQLQESGGGLVQAGGSLRLSCAASGSIFRVAWMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,0,NaN,NaN,NaN,Nb.AQ102_B2AR
27,mcmahon,target_shuffle,Nb.AQ103,QVQLQESGGGLVQAGGSLRLSCAASGSIFAAAYMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,0,NaN,NaN,NaN,Nb.AQ103_B2AR
28,mcmahon,target_shuffle,Nb.AQ104,QVQLQESGGGLVQAGGSLRLSCAASGYIFPSAVMGWYRQAPGKERE...,B2AR,23-342,DVTQERDEVWVVGMGIVMSLIVLAIVFGNVLVITAIAKFERLQTVT...,0,NaN,NaN,NaN,Nb.AQ104_B2AR
29,mcmahon,target_shuffle,Nb.AD101,QVQLQESGGGLVQAGGSLRLSCAASGTISPLPAMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.AD101_Adiponectin
30,mcmahon,target_shuffle,Nb.AD102,QVQLQESGGGLVQAGGSLRLSCAASGSIFSILSMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.AD102_Adiponectin
31,mcmahon,target_shuffle,Nb.c200,QVQLQESGGGLVQAGGSLRLSCAASGNISWVYGMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.c200_Adiponectin
32,mcmahon,target_shuffle,Nb.c201,QVQLQESGGGLVQAGGSLRLSCAASGSISYYSSMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.c201_Adiponectin
33,mcmahon,target_shuffle,Nb.c202,QVQLQESGGGLVQAGGSLRLSCAASGSISYDGHMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.c202_A2AR
34,mcmahon,target_shuffle,Nb.c203,QVQLQESGGGLVQAGGSLRLSCAASGTIFYDTAMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.c203_A2AR
35,mcmahon,target_shuffle,Nb.c204,QVQLQESGGGLVQAGGSLRLSCAASGTIFGTVLMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.c204_A2AR
36,mcmahon,target_shuffle,Nb.c205,QVQLQESGGGLVQAGGSLRLSCAASGTISYYYGMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.c205_Adiponectin
37,mcmahon,target_shuffle,Nb.c206,QVQLQESGGGLVQAGGSLRLSCAASGYIFITVPMGWYRQAPGKERE...,HSA,404-609,LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVE...,0,NaN,NaN,NaN,Nb.c206_HSA_404-609
38,cmahon,target_shuffle,Nb.c207,QVQLQESGGGLVQAGGSLRLSCAASGNISYWYYMGWYRQAPGKERE...,HSA,404-609,LVEEPQNLIKQNCELFEQLGEYKFQNALLVRYTKKVPQVSTPTLVE...,0,NaN,NaN,NaN,Nb.c207_HSA_404-609
39,mcmahon,target_shuffle,Nb.c208,QVQLQESGGGLVQAGGSLRLSCAASGNIFSYYYMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.c208_Adiponectin
40,mcmahon,target_shuffle,Nb.c209,QVQLQESGGGLVQAGGSLRLRCAASGSISVYFFMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.c209_Adiponectin
41,mcmahon,target_shuffle,Nb.c210,QVQLQESGGGLVQAGGSLRLSCAASGSIFRQDLMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.c210_A2AR
42,mcmahon,target_shuffle,Nb.c211,QVQLQESGGGLVQAGGSLRLSCAASGSIFGDVDMGWYRQAPGKERE...,A2AR,6-309,SSVYITVELAIAVLAILGNVLVCWAVWLNSNLQNVTNYFVVSLAAA...,0,NaN,NaN,NaN,Nb.c211_A2AR
43,mcmahon,target_shuffle,Nb.c212,QVQLQESGGGLVQAGGSLRLSCAASGYIFLRLTMGWYRQAPGKERE...,Adiponectin,108-244,AYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCN...,0,NaN,NaN,NaN,Nb.c212_Adiponectin

In [82]:
master_df2 = master_df.drop(columns=["vhh", "target", "target_residues", "target_sequence", "notes"])
master_df2

,source,type,vhh_sequence,binder,KD[M],EC50[M],sample
0,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,1,4.310000e-07,NaN,Nb.b201_HSA_404-609
1,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,1,4.310000e-07,NaN,Nb.b201_HSA_404-601
2,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,1,4.310000e-07,NaN,Nb.b201_HSA_25-609
3,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGTIFRVSFMGWYRQAPGKERE...,1,2.300000e-06,NaN,Nb.AQ100_Adiponectin
4,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYIFVYAYMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ101_Adiponectin
5,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSIFRVAWMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ102_Adiponectin
6,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSIFAAAYMGWYRQAPGKERE...,1,5.100000e-07,NaN,Nb.AQ103_Adiponectin
7,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYIFPSAVMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ104_Adiponectin
8,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGTISPLPAMGWYRQAPGKERE...,0,NaN,NaN,Nb.AD101_A2AR
9,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSIFSILSMGWYRQAPGKERE...,0,NaN,NaN,Nb.AD102_A2AR
10,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGNISWVYGMGWYRQAPGKERE...,1,7.800000e-08,NaN,Nb.c200_B2AR
11,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSISYYSSMGWYRQAPGKERE...,1,1.470000e-07,NaN,Nb.c201_B2AR
12,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSISYDGHMGWYRQAPGKERE...,1,4.400000e-07,NaN,Nb.c202_B2AR
13,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGTIFYDTAMGWYRQAPGKERE...,1,1.510000e-07,NaN,Nb.c203_B2AR
14,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGTIFGTVLMGWYRQAPGKERE...,1,NaN,4.900000e-08,Nb.c204_B2AR
15,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGTISYYYGMGWYRQAPGKERE...,1,NaN,2.100000e-08,Nb.c205_B2AR
16,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYIFITVPMGWYRQAPGKERE...,1,NaN,7.700000e-08,Nb.c206_B2AR
17,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGNISYWYYMGWYRQAPGKERE...,1,NaN,1.040000e-07,Nb.c207_B2AR
18,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGNIFSYYYMGWYRQAPGKERE...,1,NaN,5.500000e-08,Nb.c208_B2AR
19,mcmahon,original,QVQLQESGGGLVQAGGSLRLRCAASGSISVYFFMGWYRQAPGKERE...,1,NaN,2.400000e-08,Nb.c209_B2AR
20,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSIFRQDLMGWYRQAPGKERE...,1,NaN,2.100000e-06,Nb.c210_B2AR
21,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGSIFGDVDMGWYRQAPGKERE...,1,NaN,6.200000e-08,Nb.c211_B2AR
22,mcmahon,original,QVQLQESGGGLVQAGGSLRLSCAASGYIFLRLTMGWYRQAPGKERE...,1,NaN,2.000000e-08,Nb.c212_B2AR
23,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGYISDAYYMGWYRQAPGKERE...,0,NaN,NaN,Nb.b201_Adiponectin
24,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGTIFRVSFMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ100_A2AR
25,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGYIFVYAYMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ101_A2AR
26,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSIFRVAWMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ102_B2AR
27,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSIFAAAYMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ103_B2AR
28,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGYIFPSAVMGWYRQAPGKERE...,0,NaN,NaN,Nb.AQ104_B2AR
29,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGTISPLPAMGWYRQAPGKERE...,0,NaN,NaN,Nb.AD101_Adiponectin
30,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSIFSILSMGWYRQAPGKERE...,0,NaN,NaN,Nb.AD102_Adiponectin
31,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGNISWVYGMGWYRQAPGKERE...,0,NaN,NaN,Nb.c200_Adiponectin
32,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSISYYSSMGWYRQAPGKERE...,0,NaN,NaN,Nb.c201_Adiponectin
33,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSISYDGHMGWYRQAPGKERE...,0,NaN,NaN,Nb.c202_A2AR
34,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGTIFYDTAMGWYRQAPGKERE...,0,NaN,NaN,Nb.c203_A2AR
35,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGTIFGTVLMGWYRQAPGKERE...,0,NaN,NaN,Nb.c204_A2AR
36,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGTISYYYGMGWYRQAPGKERE...,0,NaN,NaN,Nb.c205_Adiponectin
37,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGYIFITVPMGWYRQAPGKERE...,0,NaN,NaN,Nb.c206_HSA_404-609
38,cmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGNISYWYYMGWYRQAPGKERE...,0,NaN,NaN,Nb.c207_HSA_404-609
39,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGNIFSYYYMGWYRQAPGKERE...,0,NaN,NaN,Nb.c208_Adiponectin
40,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLRCAASGSISVYFFMGWYRQAPGKERE...,0,NaN,NaN,Nb.c209_Adiponectin
41,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSIFRQDLMGWYRQAPGKERE...,0,NaN,NaN,Nb.c210_A2AR
42,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGSIFGDVDMGWYRQAPGKERE...,0,NaN,NaN,Nb.c211_A2AR
43,mcmahon,target_shuffle,QVQLQESGGGLVQAGGSLRLSCAASGYIFLRLTMGWYRQAPGKERE...,0,NaN,NaN,Nb.c212_Adiponectin

### merge

In [101]:
df = pd.merge(master_df3, df_2if, on=['sample'], how='inner')
#df = pd.merge(master_df2, preds_df, on=['sample'], how='inner')
# Display the first few rows to verify
print(df[['sample', 'af3_plddt']])

# Save the merged result
df.to_csv(OUTPUT_DIR /'merged_snir.csv', index=False)

                  sample  af3_plddt
0           5ifj_abc_cut  95.404666
1           5ig7_abc_cut  95.599717
2           5ijk_acx_cut  92.439163
3   5ifj_abc_cut_A_D111A  95.282854
4   5ifj_abc_cut_A_K110A  94.871984
5    5ifj_abc_cut_A_S64A  95.613237
6    5ifj_abc_cut_A_W52A  94.814333
7    5ifj_abc_cut_A_Y66A  95.337838
8     5ifj_abc_cut_all_A  93.235998
9   5ifj_abc_cut_B_L116A  95.032996
10   5ifj_abc_cut_B_V38A  95.220947
11  5ifj_abc_cut_B_W107A  95.089607
12   5ifj_abc_cut_B_Y37A  94.723352
13  5ig7_abc_cut_A_K110A  94.950463
14   5ig7_abc_cut_A_W52A  95.457781
15   5ig7_abc_cut_A_Y66A  95.767986
16    5ig7_abc_cut_all_A  92.210506
17  5ig7_abc_cut_B_G114A  95.869087
18  5ig7_abc_cut_B_L116A  95.298420
19   5ig7_abc_cut_B_V38A  95.793462
20  5ig7_abc_cut_B_W107A  92.830579
21   5ig7_abc_cut_B_Y37A  95.631059
22  5ijk_acx_cut_A_I112A  94.094014
23  5ijk_acx_cut_A_I114A  91.142842
24   5ijk_acx_cut_A_K57A  92.231214
25   5ijk_acx_cut_A_R55A  91.770396
26  5ijk_acx_cut_A_T113A  97.319849
27    5ijk_acx_cut_all_A  90.392437
28   5ijk_acx_cut_B_K36A  93.155359
29  5ijk_acx_cut_B_T113A  92.444807
30   5ijk_acx_cut_B_W56A  96.678663
31  5ijk_acx_cut_B_Y107A  93.553850
32  5ijk_acx_cut_B_Y108A  91.641826
33   5ijk_acx_cut_B_Y31A  94.546322
34   5ijk_acx_cut_B_Y38A  91.808649