Preparations:
- load prediction.csv
    - drop the lines with the non-used ifs
    - if there is more then one if, take mean

- add column "sample" to master table
- join them
- drop unnecessary columns (matadata, paths, ranks)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import ast
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score, precision_score, f1_score, precision_recall_curve, confusion_matrix

# Configuration
CSV_PATH =  "/home/bri/pymol/data/predictions/preds_mcmahon_ad3.csv" 
MASTER_PATH =  "/home/bri/pymol/data/mcmahon/table/master_table_mcmahon.csv" 
YAML_PATH = "/home/bri/pymol/EDA/static/metric_directions.yaml"
OUTPUT_DIR = Path("/home/bri/pymol/EDA/static/adiponectin3_outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


KEEP_INTERFACES = {"A,C", "B,C"}   # as option if there is more than one, default A,B



# Load data
preds_df = pd.read_csv(CSV_PATH)
preds_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 92 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   sample                                  105 non-null    str
 1   binding                                 105 non-null    bool
 2   interface                               105 non-null    str
 3   af3_pae                                 105 non-null    float64
 4   af3_plddt                               105 non-null    float64
 5   af3_interface_dG                        105 non-null    float64
 6   af3_interface_dG_SASA_ratio             105 non-null    float64
 7   af3_ipae                                105 non-null    float64
 8   af3_iplddt                              105 non-null    float64
 9   af3_ipsae                               105 non-null    float64
 10  af3_pdockq                              105 non-null    float64
 11  af3_pdockq2                             105 non-null    float64
 12  af3_lis                                 105 non-null    float64
 13  af3_iptm                                105 non-null    float64
 14  af3_ptm                                 105 non-null    float64
 15  af3_pyros_binder_score                  105 non-null    float64
 16  af3_rank                                105 non-null    float64
 17  af3_ranking_score                       105 non-null    float64
 18  af3_rank0_masif                         35 non-null     float64
 19  cf_af3_rmsd                             105 non-null    float64
 20  cf_pae                                  105 non-null    float64
 21  cf_plddt                                105 non-null    float64
 22  cf_interface_dG                         105 non-null    float64
 23  cf_interface_dG_SASA_ratio              105 non-null    float64
 24  cf_ipae                                 105 non-null    float64
 25  cf_iplddt                               105 non-null    float64
 26  cf_ipsae                                105 non-null    float64
 27  cf_pdockq                               105 non-null    float64
 28  cf_pdockq2                              105 non-null    float64
 29  cf_lis                                  105 non-null    float64
 30  cf_iptm                                 105 non-null    float64
 31  cf_ptm                                  105 non-null    float64
 32  cf_pyros_binder_score                   105 non-null    float64
 33  cf_rank                                 105 non-null    float64
 34  cf_rank0_masif                          37 non-null     float64
 35  pred_ilddt                              105 non-null    float64
 36  pred_lddt                               105 non-null    float64
 37  esmfold_ipae                            37 non-null     float64
 38  esmfold_iplddt                          37 non-null     float64
 39  esmfold_plddt                           105 non-null    float64
 40  esmfold_pae                             105 non-null    float64
 41  esmfold_ptm                             105 non-null    float64
 42  chai_unconstrained_score                105 non-null    float64
 43  chai_unconstrained_model_path           105 non-null    str
 44  chai_constrained_score                  105 non-null    float64
 45  chai_constrained_model_path             105 non-null    str
 46  chai_unconstrained_aggregate_score      105 non-null    float64
 47  chai_unconstrained_ptm                  105 non-null    float64
 48  chai_unconstrained_iptm                 105 non-null    float64
 49  chai_unconstrained_per_chain_ptm        105 non-null    str
 50  chai_unconstrained_per_chain_pair_iptm  105 non-null    str
 51  chai_unconstrained_interface_iptm       105 non-null    float64
 52  chai_unconstrained_ipsae                105 non-null    float64
 53  chai_unconstrained_pdockq               105 non-null    float64
 54  chai_unconstrained_pdockq2              105 non-null    float64
 55  chai_unconstrained_lis                  105 non-null    float64
 56  chai_constrained_aggregate_score        105 non-null    float64
 57  chai_constrained_ptm                    105 non-null    float64
 58  chai_constrained_iptm                   105 non-null    float64
 59  chai_constrained_per_chain_ptm          105 non-null    str
 60  chai_constrained_per_chain_pair_iptm    105 non-null    str
 61  chai_constrained_interface_iptm         105 non-null    float64
 62  chai_constrained_ipsae                  99 non-null     float64
 63  chai_constrained_pdockq                 99 non-null     float64
 64  chai_constrained_pdockq2                99 non-null     float64
 65  chai_constrained_lis                    99 non-null     float64
 66  boltz_free_confidence_score             105 non-null    float64
 67  boltz_free_ptm                          105 non-null    float64
 68  boltz_free_iptm                         105 non-null    float64
 69  boltz_free_plddt                        105 non-null    float64
 70  boltz_free_iplddt                       105 non-null    float64
 71  boltz_free_pde                          105 non-null    float64
 72  boltz_free_ipde                         105 non-null    float64
 73  boltz_free_per_chain_pair_iptm          105 non-null    float64
 74  boltz_free_model_path                   105 non-null    str
 75  boltz_free_ipsae                        105 non-null    float64
 76  boltz_free_pdockq                       105 non-null    float64
 77  boltz_free_pdockq2                      105 non-null    float64
 78  boltz_free_lis                          105 non-null    float64
 79  boltz_template_confidence_score         105 non-null    float64
 80  boltz_template_ptm                      105 non-null    float64
 81  boltz_template_iptm                     105 non-null    float64
 82  boltz_template_plddt                    105 non-null    float64
 83  boltz_template_iplddt                   105 non-null    float64
 84  boltz_template_pde                      105 non-null    float64
 85  boltz_template_ipde                     105 non-null    float64
 86  boltz_template_per_chain_pair_iptm      105 non-null    float64
 87  boltz_template_model_path               105 non-null    str
 88  boltz_template_ipsae                    105 non-null    float64
 89  boltz_template_pdockq                   105 non-null    float64
 90  boltz_template_pdockq2                  105 non-null    float64
 91  boltz_template_lis                      105 non-null    float64
dtypes: bool(1), float64(81), str(10)
memory usage: 74.9 KB

#### snir

In [2]:
df_if = preds_df[preds_df["interface"].str.strip().isin(KEEP_INTERFACES)].copy()
print(f"Loaded {len(df_if)} rows. Interfaces: {df_if['interface'].unique()}")

df_if.head(10)

Loaded 70 rows. Interfaces: <StringArray>
['A,C', 'B,C']
Length: 2, dtype: str

,sample,binding,interface,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,...,boltz_template_plddt,boltz_template_iplddt,boltz_template_pde,boltz_template_ipde,boltz_template_per_chain_pair_iptm,boltz_template_model_path,boltz_template_ipsae,boltz_template_pdockq,boltz_template_pdockq2,boltz_template_lis
1,5ijk_acx_cut_A_I114A,False,"A,C",3.581104,91.142842,52.43,6.22,4.484615,65.463607,0.023617,...,0.971302,0.964612,0.263253,0.334753,0.892070,/scicore/home/schwede/barta0000/scoring_pipeli...,0.798145,0.0303,0.7167,0.7665
2,5ijk_acx_cut_A_I114A,False,"B,C",3.581104,91.142842,83.71,14.76,1.594444,70.043835,0.024757,...,0.971302,0.964612,0.263253,0.334753,0.888323,/scicore/home/schwede/barta0000/scoring_pipeli...,0.774026,0.1712,0.8551,0.7862
4,5ifj_abc_cut_B_V38A,False,"A,C",2.714935,95.220947,17.70,2.18,2.678125,92.334169,0.758807,...,0.983234,0.981698,0.262260,0.333394,0.904294,/scicore/home/schwede/barta0000/scoring_pipeli...,0.831587,0.2632,0.9405,0.8296
5,5ifj_abc_cut_B_V38A,False,"B,C",2.714935,95.220947,13.18,1.82,1.830000,94.597707,0.758785,...,0.983234,0.981698,0.262260,0.333394,0.920807,/scicore/home/schwede/barta0000/scoring_pipeli...,0.848706,0.2098,0.9402,0.8144
7,5ifj_abc_cut_B_Y37A,False,"A,C",3.004751,94.723352,14.88,1.87,2.880556,91.827094,0.665555,...,0.979142,0.971864,0.260346,0.321740,0.921565,/scicore/home/schwede/barta0000/scoring_pipeli...,0.865535,0.2102,0.9206,0.8200
8,5ifj_abc_cut_B_Y37A,False,"B,C",3.004751,94.723352,6.63,0.89,1.716667,92.413659,0.615602,...,0.979142,0.971864,0.260346,0.321740,0.887115,/scicore/home/schwede/barta0000/scoring_pipeli...,0.782346,0.1767,0.8625,0.8042
10,5ig7_abc_cut,False,"A,C",2.572969,95.599717,10.97,1.38,2.321875,94.630252,0.780104,...,0.987334,0.987299,0.258769,0.284754,0.948463,/scicore/home/schwede/barta0000/scoring_pipeli...,0.921477,0.2352,0.9699,0.8588
11,5ig7_abc_cut,False,"B,C",2.572969,95.599717,5.13,0.67,1.720000,95.189670,0.790385,...,0.987334,0.987299,0.258769,0.284754,0.956973,/scicore/home/schwede/barta0000/scoring_pipeli...,0.928806,0.2332,0.9688,0.8586
13,5ifj_abc_cut_A_D111A,False,"A,C",2.815847,95.282854,15.90,2.09,2.450000,94.521058,0.754481,...,0.979963,0.975488,0.256625,0.289870,0.938492,/scicore/home/schwede/barta0000/scoring_pipeli...,0.903545,0.2228,0.9224,0.8619
14,5ifj_abc_cut_A_D111A,False,"B,C",2.815847,95.282854,10.55,1.40,1.750000,94.940492,0.776109,...,0.979963,0.975488,0.256625,0.289870,0.949190,/scicore/home/schwede/barta0000/scoring_pipeli...,0.913493,0.2168,0.9356,0.8502

#### all

In [3]:
num_cols = df_if.select_dtypes(include=['number']).columns
other_cols = [c for c in df_if.columns if c not in num_cols and c != 'sample']

agg_dict = {col: 'mean' for col in num_cols}
agg_dict.update({col: 'first' for col in other_cols})

df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

df_1if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,binding,interface,chai_unconstrained_model_path,chai_constrained_model_path,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm,boltz_free_model_path,boltz_template_model_path
0,5ifj_abc_cut,2.593883,95.404666,14.690,1.855,1.993750,95.036725,0.788184,0.20980,0.88085,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9454320669174194, 0.9492036700248718, 0.17...","[[[0.9454320669174194, 0.8899917602539062, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
1,5ifj_abc_cut_A_D111A,2.815847,95.282854,13.225,1.745,2.100000,94.730775,0.765295,0.18660,0.88195,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.9454193711280823, 0.9488046169281006, 0.17...","[[[0.9454193711280823, 0.8907997608184814, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
2,5ifj_abc_cut_A_K110A,2.790728,94.871984,19.975,2.845,2.275417,92.998114,0.769552,0.18030,0.85065,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9449247717857361, 0.9489190578460693, 0.17...","[[[0.9449247717857361, 0.889130175113678, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
3,5ifj_abc_cut_A_S64A,2.539446,95.613237,14.595,1.810,2.072188,94.813927,0.778962,0.19900,0.88450,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9445436000823975, 0.9495869874954224, 0.17...","[[[0.9445436000823975, 0.8924098014831543, 0.0...","[[0.945385217666626, 0.948758602142334, 0.1724...","[[[0.945385217666626, 0.8885297775268555, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
4,5ifj_abc_cut_A_W52A,3.005329,94.814333,46.435,5.940,2.303125,91.482646,0.695928,0.19125,0.78185,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9452440142631531, 0.9471760392189026, 0.16...","[[[0.9452440142631531, 0.8792759776115417, 0.0...","[[0.9452540874481201, 0.9489129781723022, 0.17...","[[[0.9452540874481201, 0.8904703855514526, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
5,5ifj_abc_cut_A_Y66A,2.701376,95.337838,17.485,2.305,2.249649,93.429048,0.763715,0.19335,0.84245,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9473956227302551, 0.9488828778266907, 0.16...","[[[0.9473956227302551, 0.8850024938583374, 0.0...","[[0.9453608989715576, 0.9489309191703796, 0.17...","[[[0.9453608989715576, 0.8903481960296631, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
6,5ifj_abc_cut_B_L116A,2.806607,95.032996,7.610,0.985,2.205952,93.484476,0.747441,0.17235,0.82990,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9485109448432922, 0.9499985575675964, 0.17...","[[[0.9485109448432922, 0.8920019865036011, 0.0...","[[0.9452025294303894, 0.9490475058555603, 0.17...","[[[0.9452025294303894, 0.8905109763145447, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
7,5ifj_abc_cut_B_V38A,2.714935,95.220947,15.440,2.000,2.254062,93.465938,0.758796,0.19055,0.85940,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9468277096748352, 0.9472519159317017, 0.10...","[[[0.9468277096748352, 0.8879522085189819, 0.0...","[[0.945318341255188, 0.9495519995689392, 0.177...","[[[0.945318341255188, 0.890434980392456, 0.072...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
8,5ifj_abc_cut_B_W107A,2.878966,95.089607,17.035,2.335,2.471875,93.380576,0.623665,0.16430,0.79175,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9425944089889526, 0.9466992616653442, 0.10...","[[[0.9425944089889526, 0.8834366798400879, 0.0...","[[0.9448549747467041, 0.9490682482719421, 0.17...","[[[0.9448549747467041, 0.8899660706520081, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
9,5ifj_abc_cut_B_Y37A,3.004751,94.723352,10.755,1.380,2.298611,92.120377,0.640578,0.17745,0.77900,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.940564751625061, 0.9448128938674927, 0.095...","[[[0.940564751625061, 0.8819113969802856, 0.04...","[[0.9450069665908813, 0.94929438829422, 0.1781...","[[[0.9450069665908813, 0.889803946018219, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
10,5ifj_abc_cut_all_A,3.597543,93.235998,34.575,5.025,2.204441,83.750294,0.189334,0.11440,0.33130,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9467074275016785, 0.9420090913772583, 0.11...","[[[0.9467074275016785, 0.8753525018692017, 0.0...","[[0.9453179836273193, 0.9489884376525879, 0.17...","[[[0.9453179836273193, 0.8899396657943726, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
11,5ig7_abc_cut,2.572969,95.599717,8.050,1.025,2.020937,94.909961,0.785245,0.20200,0.89390,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9455351233482361, 0.9491659998893738, 0.17...","[[[0.9455351233482361, 0.891846776008606, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
12,5ig7_abc_cut_A_K110A,2.806122,94.950463,16.750,2.340,2.220000,93.355815,0.756785,0.20195,0.85780,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9444799423217773, 0.9482003450393677, 0.09...","[[[0.9444799423217773, 0.8866336941719055, 0.0...","[[0.9459781646728516, 0.9495248794555664, 0.17...","[[[0.9459781646728516, 0.8912208080291748, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
13,5ig7_abc_cut_A_W52A,2.731340,95.457781,11.955,1.515,2.111607,93.974962,0.749117,0.21550,0.86160,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9392455220222473, 0.9467980265617371, 0.08...","[[[0.9392455220222473, 0.8777296543121338, 0.0...","[[0.9454331398010254, 0.9495590925216675, 0.17...","[[[0.9454331398010254, 0.8912692070007324, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
14,5ig7_abc_cut_A_Y66A,2.572738,95.767986,9.105,1.215,1.959615,95.063667,0.786285,0.22025,0.88890,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9482442736625671, 0.9485312104225159, 0.16...","[[[0.9482442736625671, 0.885511040687561, 0.06...","[[0.9459070563316345, 0.9496902823448181, 0.17...","[[[0.9459070563316345, 0.891128420829773, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
15,5ig7_abc_cut_B_G114A,2.436673,95.869087,12.200,1.510,1.884375,95.531792,0.810392,0.19195,0.90170,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9472417831420898, 0.9477450847625732, 0.09...","[[[0.9472417831420898, 0.8837891817092896, 0.0...","[[0.9454723596572876, 0.9491568207740784, 0.17...","[[[0.9454723596572876, 0.8910244703292847, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
16,5ig7_abc_cut_B_L116A,2.697161,95.298420,13.320,1.610,2.129575,93.730328,0.756877,0.19240,0.86445,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9438903331756592, 0.9470524191856384, 0.08...","[[[0.9438903331756592, 0.879470705986023, 0.01...","[[0.9453369379043579, 0.9497691988945007, 0.17...","[[[0.9453369379043579, 0.8912421464920044, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
17,5ig7_abc_cut_B_V38A,2.540938,95.793462,10.800,1.405,2.050536,94.756844,0.776995,0.19930,0.88640,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9432534575462341, 0.9479488134384155, 0.09...","[[[0.9432534575462341, 0.8869456648826599, 0.0...","[[0.9457123875617981, 0.949378252029419, 0.174...","[[[0.9457123875617981, 0.89024418592453, 0.072...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
18,5ig7_abc_cut_B_W107A,3.561995,92.830579,128.475,19.540,2.146591,82.977278,0.155861,0.09575,0.32615,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9412914514541626, 0.9472916126251221, 0.09...","[[[0.9412914514541626, 0.8858029842376709, 0.0...","[[0.9455239772796631, 0.9491193890571594, 0.17...","[[[0.9455239772796631, 0.8903375864028931, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
19,5ig7_abc_cut_B_Y37A,2.644076,95.631059,15.830,1.985,1.979167,94.594111,0.720382,0.20810,0.85615,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9416530132293701, 0.9461093544960022, 0.09...","[[[0.9416530132293701, 0.8841282725334167, 0.0...","[[0.9443178176879883, 0.9490799307823181, 0.17...","[[[0.9443178176879883, 0.8913766145706177, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
20,5ig7_abc_cut_all_A,3.805987,92.210506,56.120,10.050,2.444928,76.576550,0.061503,0.08945,0.17770,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9479871988296509, 0.943764865398407, 0.091...","[[[0.9479871988296509, 0.8801519870758057, 0.0...","[[0.9454576969146729, 0.9486308097839355, 0.17...","[[[0.9454576969146729, 0.8897534608840942, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
21,5ijk_acx_cut,3.486349,92.439163,26.435,4.765,5.111071,69.144182,0.088382,0.04025,0.18020,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9452543258666992, 0.9524880051612854, 0.13...","[[[0.9452543258666992, 0.8906955122947693, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
22,5ijk_acx_cut_A_I112A,2.957804,94.094014,95.960,16.700,2.786161,76.558583,0.112243,0.05660,0.25410,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9419323205947876, 0.9515408277511597, 0.09...","[[[0.9419323205947876, 0.8887308239936829, 0.0...","[[0.9465927481651306, 0.9527407288551331, 0.13...","[[[0.9465927481651306, 0.8916440606117249, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
23,5ijk_acx_cut_A_I114A,3.581104,91.142842,68.070,10.490,3.039530,67.753721,0.024187,0.03975,0.06940,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9325439929962158, 0.951015830039978, 0.098...","[[[0.9325439929962158, 0.8848593235015869, 0.0...","[[0.9451525807380676, 0.9521574974060059, 0.13...","[[[0.9451525807380676, 0.8916072845458984, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
24,5ijk_acx_cut_A_K57A,3.333153,92.231214,84.570,13.910,3.738864,66.901441,0.023776,0.03760,0.08380,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9351347088813782, 0.9510679841041565, 0.09...","[[[0.9351347088813782, 0.8865579962730408, 0.0...","[[0.9464284181594849, 0.9522534012794495, 0.13...","[[[0.9464284181594849, 0.8884240388870239, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
25,5ijk_acx_cut_A_R55A,3.411108,91.770396,58.025,9.175,3.270139,64.294001,0.024243,0.03430,0.08470,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9349604845046997, 0.9504574537277222, 0.09...","[[[0.9349604845046997, 0.8808215260505676, 0.0...","[[0.9458076357841492, 0.9529669284820557, 0.13...","[[[0.9458076357841492, 0.891848087310791, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
26,5ijk_acx_cut_A_T113A,2.042686,97.319849,-2.805,-0.835,1.473958,97.583035,0.760557,0.09555,0.93485,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9451172947883606, 0.9515537023544312, 0.09...","[[[0.9451172947883606, 0.8881925940513611, 0.0...","[[0.9464637041091919, 0.9521260857582092, 0.13...","[[[0.9464637041091919, 0.8910889029502869, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
27,5ijk_acx_cut_B_K36A,3.220014,93.155359,30.100,7.160,3.395000,72.266295,0.067418,0.03880,0.15895,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9357482194900513, 0.9508245587348938, 0.10...","[[[0.9357482194900513, 0.8863149881362915, 0.0...","[[0.9461846947669983, 0.952305257320404, 0.136...","[[[0.9461846947669983, 0.8887318968772888, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
28,5ijk_acx_cut_B_T113A,3.117051,92.444807,30.825,4.280,2.748438,74.341522,0.075896,0.04325,0.15815,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9378942847251892, 0.9510397911071777, 0.11...","[[[0.9378942847251892, 0.8857946395874023, 0.0...","[[0.9467201232910156, 0.9526268839836121, 0.13...","[[[0.9467201232910156, 0.8916904926300049, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
29,5ijk_acx_cut_B_W56A,2.382550,96.678663,6.990,0.850,1.701389,95.561703,0.606970,0.08580,0.82670,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9516229033470154, 0.9518455266952515, 0.11...","[[[0.9516229033470154, 0.8881137371063232, 0.0...","[[0.9466335773468018, 0.9514474272727966, 0.13...","[[[0.9466335773468018, 0.8913890719413757, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
30,5ijk_acx_cut_B_Y107A,3.163120,93.553850,41.520,7.365,2.214583,72.905361,0.026280,0.04065,0.12810,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9415576457977295, 0.9507483839988708, 0.10...","[[[0.9415576457977295, 0.892025351524353, 0.02...","[[0.9454445838928223, 0.9516614079475403, 0.13...","[[[0.9454445838928223, 0.8913754820823669, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
31,5ijk_acx_cut_B_Y108A,3.341985,91.641826,41.775,7.040,3.902778,65.016859,0.024165,0.02670,0.06370,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9349137544631958, 0.950394332408905, 0.093...","[[[0.9349137544631958, 0.8863245248794556, 0.0...","[[0.945480465888977, 0.9518694877624512, 0.136...","[[[0.945480465888977, 0.8908371925354004, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
32,5ijk_acx_cut_B_Y31A,3.093042,94.546322,49.185,7.655,2.354934,80.447620,0.054126,0.04045,0.30005,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9345048069953918, 0.9514862895011902, 0.09...","[[[0.9345048069953918, 0.8868847489356995, 0.0...","[[0.9461417198181152, 0.9522110223770142, 0.13...","[[[0.9461417198181152, 0.891068160533905, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
33,5ijk_acx_cut_B_Y38A,3.455154,91.808649,84.050,13.855,4.266518,68.727387,0.047625,0.04295,0.12330,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9347723126411438, 0.9516543745994568, 0.09...","[[[0.9347723126411438, 0.8869415521621704, 0.0...","[[0.9460254311561584, 0.9520831108093262, 0.13...","[[[0.9460254311561584, 0.8908280730247498, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
34,5ijk_acx_cut_all_A,4.276973,90.392437,55.260,7.055,4.580952,71.830438,0.058250,0.05665,0.08885,...,False,"A,C",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.935025691986084, 0.944311797618866, 0.0957...","[[[0.935025691986084, 0.8839023113250732, 0.02...","[[0.946010947227478, 0.952307403087616, 0.1360...","[[[0.946010947227478, 0.8915120363235474, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...

In [4]:
df_2if = df_1if.drop(columns=["binding", "interface","chai_unconstrained_model_path", "chai_constrained_model_path", "boltz_free_model_path", "boltz_template_model_path"])
df_2if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,boltz_template_ipde,boltz_template_per_chain_pair_iptm,boltz_template_ipsae,boltz_template_pdockq,boltz_template_pdockq2,boltz_template_lis,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm
0,5ifj_abc_cut,2.593883,95.404666,14.690,1.855,1.993750,95.036725,0.788184,0.20980,0.88085,...,0.278017,0.960036,0.937455,0.23935,0.96685,0.87115,"[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9454320669174194, 0.9492036700248718, 0.17...","[[[0.9454320669174194, 0.8899917602539062, 0.0..."
1,5ifj_abc_cut_A_D111A,2.815847,95.282854,13.225,1.745,2.100000,94.730775,0.765295,0.18660,0.88195,...,0.289870,0.943841,0.908519,0.21980,0.92900,0.85605,"[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.9454193711280823, 0.9488046169281006, 0.17...","[[[0.9454193711280823, 0.8907997608184814, 0.0..."
2,5ifj_abc_cut_A_K110A,2.790728,94.871984,19.975,2.845,2.275417,92.998114,0.769552,0.18030,0.85065,...,0.275365,0.961354,0.939275,0.23650,0.96220,0.87810,"[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9449247717857361, 0.9489190578460693, 0.17...","[[[0.9449247717857361, 0.889130175113678, 0.07..."
3,5ifj_abc_cut_A_S64A,2.539446,95.613237,14.595,1.810,2.072188,94.813927,0.778962,0.19900,0.88450,...,0.295100,0.938922,0.898855,0.22850,0.95750,0.84545,"[[0.9445436000823975, 0.9495869874954224, 0.17...","[[[0.9445436000823975, 0.8924098014831543, 0.0...","[[0.945385217666626, 0.948758602142334, 0.1724...","[[[0.945385217666626, 0.8885297775268555, 0.07..."
4,5ifj_abc_cut_A_W52A,3.005329,94.814333,46.435,5.940,2.303125,91.482646,0.695928,0.19125,0.78185,...,0.343705,0.913520,0.845670,0.21780,0.94175,0.81200,"[[0.9452440142631531, 0.9471760392189026, 0.16...","[[[0.9452440142631531, 0.8792759776115417, 0.0...","[[0.9452540874481201, 0.9489129781723022, 0.17...","[[[0.9452540874481201, 0.8904703855514526, 0.0..."
5,5ifj_abc_cut_A_Y66A,2.701376,95.337838,17.485,2.305,2.249649,93.429048,0.763715,0.19335,0.84245,...,0.305202,0.935591,0.892648,0.20680,0.95410,0.83435,"[[0.9473956227302551, 0.9488828778266907, 0.16...","[[[0.9473956227302551, 0.8850024938583374, 0.0...","[[0.9453608989715576, 0.9489309191703796, 0.17...","[[[0.9453608989715576, 0.8903481960296631, 0.0..."
6,5ifj_abc_cut_B_L116A,2.806607,95.032996,7.610,0.985,2.205952,93.484476,0.747441,0.17235,0.82990,...,0.290632,0.941965,0.905323,0.21785,0.94930,0.85275,"[[0.9485109448432922, 0.9499985575675964, 0.17...","[[[0.9485109448432922, 0.8920019865036011, 0.0...","[[0.9452025294303894, 0.9490475058555603, 0.17...","[[[0.9452025294303894, 0.8905109763145447, 0.0..."
7,5ifj_abc_cut_B_V38A,2.714935,95.220947,15.440,2.000,2.254062,93.465938,0.758796,0.19055,0.85940,...,0.333394,0.912550,0.840146,0.23650,0.94035,0.82200,"[[0.9468277096748352, 0.9472519159317017, 0.10...","[[[0.9468277096748352, 0.8879522085189819, 0.0...","[[0.945318341255188, 0.9495519995689392, 0.177...","[[[0.945318341255188, 0.890434980392456, 0.072..."
8,5ifj_abc_cut_B_W107A,2.878966,95.089607,17.035,2.335,2.471875,93.380576,0.623665,0.16430,0.79175,...,0.315265,0.916625,0.851439,0.21350,0.93755,0.83195,"[[0.9425944089889526, 0.9466992616653442, 0.10...","[[[0.9425944089889526, 0.8834366798400879, 0.0...","[[0.9448549747467041, 0.9490682482719421, 0.17...","[[[0.9448549747467041, 0.8899660706520081, 0.0..."
9,5ifj_abc_cut_B_Y37A,3.004751,94.723352,10.755,1.380,2.298611,92.120377,0.640578,0.17745,0.77900,...,0.321740,0.904340,0.823940,0.19345,0.89155,0.81210,"[[0.940564751625061, 0.9448128938674927, 0.095...","[[[0.940564751625061, 0.8819113969802856, 0.04...","[[0.9450069665908813, 0.94929438829422, 0.1781...","[[[0.9450069665908813, 0.889803946018219, 0.07..."
10,5ifj_abc_cut_all_A,3.597543,93.235998,34.575,5.025,2.204441,83.750294,0.189334,0.11440,0.33130,...,0.294560,0.935245,0.892680,0.11265,0.65300,0.84915,"[[0.9467074275016785, 0.9420090913772583, 0.11...","[[[0.9467074275016785, 0.8753525018692017, 0.0...","[[0.9453179836273193, 0.9489884376525879, 0.17...","[[[0.9453179836273193, 0.8899396657943726, 0.0..."
11,5ig7_abc_cut,2.572969,95.599717,8.050,1.025,2.020937,94.909961,0.785245,0.20200,0.89390,...,0.284754,0.952718,0.925142,0.23420,0.96935,0.85870,"[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9455351233482361, 0.9491659998893738, 0.17...","[[[0.9455351233482361, 0.891846776008606, 0.07..."
12,5ig7_abc_cut_A_K110A,2.806122,94.950463,16.750,2.340,2.220000,93.355815,0.756785,0.20195,0.85780,...,0.278993,0.955114,0.929089,0.24685,0.96725,0.86455,"[[0.9444799423217773, 0.9482003450393677, 0.09...","[[[0.9444799423217773, 0.8866336941719055, 0.0...","[[0.9459781646728516, 0.9495248794555664, 0.17...","[[[0.9459781646728516, 0.8912208080291748, 0.0..."
13,5ig7_abc_cut_A_W52A,2.731340,95.457781,11.955,1.515,2.111607,93.974962,0.749117,0.21550,0.86160,...,0.310701,0.929829,0.882207,0.22675,0.95025,0.84120,"[[0.9392455220222473, 0.9467980265617371, 0.08...","[[[0.9392455220222473, 0.8777296543121338, 0.0...","[[0.9454331398010254, 0.9495590925216675, 0.17...","[[[0.9454331398010254, 0.8912692070007324, 0.0..."
14,5ig7_abc_cut_A_Y66A,2.572738,95.767986,9.105,1.215,1.959615,95.063667,0.786285,0.22025,0.88890,...,0.291466,0.940558,0.902896,0.22320,0.96010,0.84480,"[[0.9482442736625671, 0.9485312104225159, 0.16...","[[[0.9482442736625671, 0.885511040687561, 0.06...","[[0.9459070563316345, 0.9496902823448181, 0.17...","[[[0.9459070563316345, 0.891128420829773, 0.07..."
15,5ig7_abc_cut_B_G114A,2.436673,95.869087,12.200,1.510,1.884375,95.531792,0.810392,0.19195,0.90170,...,0.278153,0.953022,0.925527,0.21755,0.96405,0.85475,"[[0.9472417831420898, 0.9477450847625732, 0.09...","[[[0.9472417831420898, 0.8837891817092896, 0.0...","[[0.9454723596572876, 0.9491568207740784, 0.17...","[[[0.9454723596572876, 0.8910244703292847, 0.0..."
16,5ig7_abc_cut_B_L116A,2.697161,95.298420,13.320,1.610,2.129575,93.730328,0.756877,0.19240,0.86445,...,0.302204,0.921974,0.864337,0.23690,0.94355,0.83955,"[[0.9438903331756592, 0.9470524191856384, 0.08...","[[[0.9438903331756592, 0.879470705986023, 0.01...","[[0.9453369379043579, 0.9497691988945007, 0.17...","[[[0.9453369379043579, 0.8912421464920044, 0.0..."
17,5ig7_abc_cut_B_V38A,2.540938,95.793462,10.800,1.405,2.050536,94.756844,0.776995,0.19930,0.88640,...,0.306834,0.914633,0.851071,0.22940,0.94290,0.83475,"[[0.9432534575462341, 0.9479488134384155, 0.09...","[[[0.9432534575462341, 0.8869456648826599, 0.0...","[[0.9457123875617981, 0.949378252029419, 0.174...","[[[0.9457123875617981, 0.89024418592453, 0.072..."
18,5ig7_abc_cut_B_W107A,3.561995,92.830579,128.475,19.540,2.146591,82.977278,0.155861,0.09575,0.32615,...,0.303191,0.915054,0.852937,0.22970,0.94420,0.83240,"[[0.9412914514541626, 0.9472916126251221, 0.09...","[[[0.9412914514541626, 0.8858029842376709, 0.0...","[[0.9455239772796631, 0.9491193890571594, 0.17...","[[[0.9455239772796631, 0.8903375864028931, 0.0..."
19,5ig7_abc_cut_B_Y37A,2.644076,95.631059,15.830,1.985,1.979167,94.594111,0.720382,0.20810,0.85615,...,0.356334,0.878285,0.770047,0.21510,0.91860,0.78060,"[[0.9416530132293701, 0.9461093544960022, 0.09...","[[[0.9416530132293701, 0.8841282725334167, 0.0...","[[0.9443178176879883, 0.9490799307823181, 0.17...","[[[0.9443178176879883, 0.8913766145706177, 0.0..."
20,5ig7_abc_cut_all_A,3.805987,92.210506,56.120,10.050,2.444928,76.576550,0.061503,0.08945,0.17770,...,0.301555,0.914891,0.855379,0.24865,0.87545,0.83435,"[[0.9479871988296509, 0.943764865398407, 0.091...","[[[0.9479871988296509, 0.8801519870758057, 0.0...","[[0.9454576969146729, 0.9486308097839355, 0.17...","[[[0.9454576969146729, 0.8897534608840942, 0.0..."
21,5ijk_acx_cut,3.486349,92.439163,26.435,4.765,5.111071,69.144182,0.088382,0.04025,0.18020,...,0.283189,0.943557,0.906099,0.08775,0.92390,0.82455,"[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9452543258666992, 0.9524880051612854, 0.13...","[[[0.9452543258666992, 0.8906955122947693, 0.0..."
22,5ijk_acx_cut_A_I112A,2.957804,94.094014,95.960,16.700,2.786161,76.558583,0.112243,0.05660,0.25410,...,0.354413,0.888475,0.783578,0.07840,0.80560,0.76260,"[[0.9419323205947876, 0.9515408277511597, 0.09...","[[[0.9419323205947876, 0.8887308239936829, 0.0...","[[0.9465927481651306, 0.9527407288551331, 0.13...","[[[0.9465927481651306, 0.8916440606117249, 0.0..."
23,5ijk_acx_cut_A_I114A,3.581104,91.142842,68.070,10.490,3.039530,67.753721,0.024187,0.03975,0.06940,...,0.334753,0.890196,0.786085,0.10075,0.78590,0.77635,"[[0.9325439929962158, 0.951015830039978, 0.098...","[[[0.9325439929962158, 0.8848593235015869, 0.0...","[[0.9451525807380676, 0.9521574974060059, 0.13...","[[[0.9451525807380676, 0.8916072845458984, 0.0..."
24,5ijk_acx_cut_A_K57A,3.333153,92.231214,84.570,13.910,3.738864,66.901441,0.023776,0.03760,0.08380,...,0.320888,0.914674,0.848387,0.08755,0.86490,0.78115,"[[0.9351347088813782, 0.9510679841041565, 0.09...","[[[0.9351347088813782, 0.8865579962730408, 0.0...","[[0.9464284181594849, 0.9522534012794495, 0.13...","[[[0.9464284181594849, 0.8884240388870239, 0.0..."
25,5ijk_acx_cut_A_R55A,3.411108,91.770396,58.025,9.175,3.270139,64.294001,0.024243,0.03430,0.08470,...,0.362754,0.885279,0.765977,0.08580,0.80730,0.75905,"[[0.9349604845046997, 0.9504574537277222, 0.09...","[[[0.9349604845046997, 0.8808215260505676, 0.0...","[[0.9458076357841492, 0.9529669284820557, 0.13...","[[[0.9458076357841492, 0.891848087310791, 0.03..."
26,5ijk_acx_cut_A_T113A,2.042686,97.319849,-2.805,-0.835,1.473958,97.583035,0.760557,0.09555,0.93485,...,0.295899,0.924415,0.869268,0.11245,0.86970,0.81090,"[[0.9451172947883606, 0.9515537023544312, 0.09...","[[[0.9451172947883606, 0.8881925940513611, 0.0...","[[0.9464637041091919, 0.9521260857582092, 0.13...","[[[0.9464637041091919, 0.8910889029502869, 0.0..."
27,5ijk_acx_cut_B_K36A,3.220014,93.155359,30.100,7.160,3.395000,72.266295,0.067418,0.03880,0.15895,...,0.273458,0.953893,0.926195,0.10265,0.93920,0.84055,"[[0.9357482194900513, 0.9508245587348938, 0.10...","[[[0.9357482194900513, 0.8863149881362915, 0.0...","[[0.9461846947669983, 0.952305257320404, 0.136...","[[[0.9461846947669983, 0.8887318968772888, 0.0..."
28,5ijk_acx_cut_B_T113A,3.117051,92.444807,30.825,4.280,2.748438,74.341522,0.075896,0.04325,0.15815,...,0.281364,0.941464,0.903611,0.08625,0.90380,0.82980,"[[0.9378942847251892, 0.9510397911071777, 0.11...","[[[0.9378942847251892, 0.8857946395874023, 0.0...","[[0.9467201232910156, 0.9526268839836121, 0.13...","[[[0.9467201232910156, 0.8916904926300049, 0.0..."
29,5ijk_acx_cut_B_W56A,2.382550,96.678663,6.990,0.850,1.701389,95.561703,0.606970,0.08580,0.82670,...,0.279630,0.946605,0.914295,0.11150,0.89670,0.83020,"[[0.9516229033470154, 0.9518455266952515, 0.11...","[[[0.9516229033470154, 0.8881137371063232, 0.0...","[[0.9466335773468018, 0.9514474272727966, 0.13...","[[[0.9466335773468018, 0.8913890719413757, 0.0..."
30,5ijk_acx_cut_B_Y107A,3.163120,93.553850,41.520,7.365,2.214583,72.905361,0.026280,0.04065,0.12810,...,0.296101,0.933897,0.887658,0.09310,0.89185,0.81230,"[[0.9415576457977295, 0.9507483839988708, 0.10...","[[[0.9415576457977295, 0.892025351524353, 0.02...","[[0.9454445838928223, 0.9516614079475403, 0.13...","[[[0.9454445838928223, 0.8913754820823669, 0.0..."
31,5ijk_acx_cut_B_Y108A,3.341985,91.641826,41.775,7.040,3.902778,65.016859,0.024165,0.02670,0.06370,...,0.286478,0.939573,0.901063,0.09325,0.89230,0.81975,"[[0.9349137544631958, 0.950394332408905, 0.093...","[[[0.9349137544631958, 0.8863245248794556, 0.0...","[[0.945480465888977, 0.9518694877624512, 0.136...","[[[0.945480465888977, 0.8908371925354004, 0.03..."
32,5ijk_acx_cut_B_Y31A,3.093042,94.546322,49.185,7.655,2.354934,80.447620,0.054126,0.04045,0.30005,...,0.283986,0.943800,0.907933,0.10520,0.89815,0.82685,"[[0.9345048069953918, 0.9514862895011902, 0.09...","[[[0.9345048069953918, 0.8868847489356995, 0.0...","[[0.9461417198181152, 0.9522110223770142, 0.13...","[[[0.9461417198181152, 0.891068160533905, 0.03..."
33,5ijk_acx_cut_B_Y38A,3.455154,91.808649,84.050,13.855,4.266518,68.727387,0.047625,0.04295,0.12330,...,0.285020,0.948801,0.917206,0.10130,0.88760,0.83330,"[[0.9347723126411438, 0.9516543745994568, 0.09...","[[[0.9347723126411438, 0.8869415521621704, 0.0...","[[0.9460254311561584, 0.9520831108093262, 0.13...","[[[0.9460254311561584, 0.8908280730247498, 0.0..."
34,5ijk_acx_cut_all_A,4.276973,90.392437,55.260,7.055,4.580952,71.830438,0.058250,0.05665,0.08885,...,0.540619,0.839750,0.642768,0.06440,0.30960,0.71245,"[[0.935025691986084, 0.944311797618866, 0.0957...","[[[0.935025691986084, 0.8839023113250732, 0.02...","[[0.946010947227478, 0.952307403087616, 0.1360...","[[[0.946010947227478, 0.8915120363235474, 0.03..."

## master df

##### snir

In [5]:
# for snir data
master_df = pd.read_csv(MASTER_PATH, delimiter=';')
master_df

,source,type,sample,fab,interface,vh/vl,target,target_residues,target_sequence,binder,KD[M],notes
0,snir_ab,original,5ifj_abc_cut,1000.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
1,snir_ab,original,5ifj_abc_cut,1000.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
2,snir_ab,original,5ig7_abc_cut,10.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
3,snir_ab,original,5ig7_abc_cut,10.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
4,snir_ab,original,5ijk_acx_cut,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,1,0.000001,Fab 1E01 + KD[M] approximated from Snir et. al...
...,...,...,...,...,...,...,...,...,...,...,...,...
65,snir_ab,alanine_scan,5ijk_acx_cut_B_Y108A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
66,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
67,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLASSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
68,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
69,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNALAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN

In [6]:
master_df2 = master_df.drop(columns=["interface", "fab", "vh/vl", "target", "target_residues", "target_sequence", "notes"])
master_df2

     source          type                sample  binder     KD[M]
0   snir_ab      original          5ifj_abc_cut       1  0.000010
1   snir_ab      original          5ifj_abc_cut       1  0.000010
2   snir_ab      original          5ig7_abc_cut       1  0.000100
3   snir_ab      original          5ig7_abc_cut       1  0.000100
4   snir_ab      original          5ijk_acx_cut       1  0.000001
..      ...           ...                   ...     ...       ...
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
66  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
68  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

[70 rows x 5 columns]

In [7]:
master_df3 = master_df2.drop_duplicates(keep="last")
master_df3

     source          type                sample  binder     KD[M]
1   snir_ab      original          5ifj_abc_cut       1  0.000010
3   snir_ab      original          5ig7_abc_cut       1  0.000100
5   snir_ab      original          5ijk_acx_cut       1  0.000001
7   snir_ab  alanine_scan  5ifj_abc_cut_A_D111A       0       NaN
9   snir_ab  alanine_scan  5ifj_abc_cut_A_K110A       0       NaN
11  snir_ab  alanine_scan   5ifj_abc_cut_A_S64A       0       NaN
13  snir_ab  alanine_scan   5ifj_abc_cut_A_W52A       0       NaN
15  snir_ab  alanine_scan   5ifj_abc_cut_A_Y66A       0       NaN
17  snir_ab  alanine_scan    5ifj_abc_cut_all_A       0       NaN
19  snir_ab  alanine_scan  5ifj_abc_cut_B_L116A       0       NaN
21  snir_ab  alanine_scan   5ifj_abc_cut_B_V38A       0       NaN
23  snir_ab  alanine_scan  5ifj_abc_cut_B_W107A       0       NaN
25  snir_ab  alanine_scan   5ifj_abc_cut_B_Y37A       0       NaN
27  snir_ab  alanine_scan  5ig7_abc_cut_A_K110A       0       NaN
29  snir_ab  alanine_scan   5ig7_abc_cut_A_W52A       0       NaN
31  snir_ab  alanine_scan   5ig7_abc_cut_A_Y66A       0       NaN
33  snir_ab  alanine_scan    5ig7_abc_cut_all_A       0       NaN
35  snir_ab  alanine_scan  5ig7_abc_cut_B_G114A       0       NaN
37  snir_ab  alanine_scan  5ig7_abc_cut_B_L116A       0       NaN
39  snir_ab  alanine_scan   5ig7_abc_cut_B_V38A       0       NaN
41  snir_ab  alanine_scan  5ig7_abc_cut_B_W107A       0       NaN
43  snir_ab  alanine_scan   5ig7_abc_cut_B_Y37A       0       NaN
45  snir_ab  alanine_scan  5ijk_acx_cut_A_I112A       0       NaN
47  snir_ab  alanine_scan  5ijk_acx_cut_A_I114A       0       NaN
49  snir_ab  alanine_scan   5ijk_acx_cut_A_K57A       0       NaN
51  snir_ab  alanine_scan   5ijk_acx_cut_A_R55A       0       NaN
53  snir_ab  alanine_scan  5ijk_acx_cut_A_T113A       0       NaN
55  snir_ab  alanine_scan    5ijk_acx_cut_all_A       0       NaN
57  snir_ab  alanine_scan   5ijk_acx_cut_B_K36A       0       NaN
59  snir_ab  alanine_scan  5ijk_acx_cut_B_T113A       0       NaN
61  snir_ab  alanine_scan   5ijk_acx_cut_B_W56A       0       NaN
63  snir_ab  alanine_scan  5ijk_acx_cut_B_Y107A       0       NaN
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

##### mcmahon / germinal

In [ ]:

master_df = pd.read_csv(MASTER_PATH, delimiter=';')
master_df.head()

,source,type,sample,fab,interface,vh/vl,target,target_residues,target_sequence,binder,KD[M],notes
0,snir_ab,original,5ifj_abc_cut,1000.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
1,snir_ab,original,5ifj_abc_cut,1000.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
2,snir_ab,original,5ig7_abc_cut,10.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
3,snir_ab,original,5ig7_abc_cut,10.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
4,snir_ab,original,5ijk_acx_cut,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,1,0.000001,Fab 1E01 + KD[M] approximated from Snir et. al...

In [5]:
AMBIGUOUS_TARGET= "HSA"   # test

def create_sample_id(row):
    vhh = str(row['vhh'])
    target = str(row['target'])
    residues = str(row['target_residues'])
    
    # Check if target is (ambigous target, meaning the same target has different version --> target residues are needed to be able to identify it, the only one for now is HSA) to apply the specific naming convention
    if target == AMBIGUOUS_TARGET:
        return f"{vhh}_{target}_{residues}"
    else:
        return f"{vhh}_{target}"

# 1. Create the 'sample' column in the master table
master_df['sample'] = master_df.apply(create_sample_id, axis=1)
master_df

,source,type,vhh,vhh_sequence,target,target_residues,target_sequence,binder,KD[M],sample
0,germinal,original,nb_s413501_mpnn_3,QVQLVESGGGLVQPGGSLRLSCAASGSRAIHLKYVGLGWFRQAPGQ...,PDL1,19-127,FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNI...,0,NaN,nb_s413501_mpnn_3_PDL1
1,germinal,original,nb_s80903_mpnn_4,QVQLVESGGGLVQPGGSLRLSCAASGSLYISNCKTHLGWFRQAPGQ...,PDL1,19-127,FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNI...,0,NaN,nb_s80903_mpnn_4_PDL1
2,germinal,original,nb_s185784_mpnn_4,QVQLVESGGGLVQPGGSLRLSCAASRWFSNEFHNICLGWFRQAPGQ...,PDL1,19-127,FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNI...,0,NaN,nb_s185784_mpnn_4_PDL1
3,germinal,original,nb_s465730_mpnn_4,QVQLVESGGGLVQPGGSLRLSCAASSANFSLSGFHHLGWFRQAPGQ...,PDL1,19-127,FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNI...,0,NaN,nb_s465730_mpnn_4_PDL1
4,germinal,original,nb_s892360_mpnn_4,QVQLVESGGGLVQPGGSLRLSCAASSRFPWEFIRMWLGWFRQAPGQ...,PDL1,19-127,FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNI...,0,NaN,nb_s892360_mpnn_4_PDL1
...,...,...,...,...,...,...,...,...,...,...
475,germinal,target_shuffle,nb_s276607_mpnn_4,QVQLVESGGGLVQPGGSLRLSCAASGDDVDKWFLDWLGWFRQAPGQ...,IL20,25-176,LKTLNLGSCVIATNLQEIRNGFSEIRGSVQAKDGNIDIRILRRTES...,0,NaN,nb_s276607_mpnn_4_IL20
476,germinal,target_shuffle,nb_s442197_mpnn_3,QVQLVESGGGLVQPGGSLRLSCAASFDLSRCYMISYLGWFRQAPGQ...,PDL1,19-127,FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNI...,0,NaN,nb_s442197_mpnn_3_PDL1
477,germinal,target_shuffle,nb_s776407_mpnn_2,QVQLVESGGGLVQPGGSLRLSCAASDFFTSKYHWWYLGWFRQAPGQ...,IL3,31-152,SWVNCSNMIDEIITHLKQPPLPLLDFNNLNGEDQDILMENNLRRPN...,0,NaN,nb_s776407_mpnn_2_IL3
478,germinal,target_shuffle,nb_s206651_mpnn_1,QVQLVESGGGLVQPGGSLRLSCAASGMTAAEFKERELGWFRQAPGQ...,IL3,31-152,SWVNCSNMIDEIITHLKQPPLPLLDFNNLNGEDQDILMENNLRRPN...,0,NaN,nb_s206651_mpnn_1_IL3
479,germinal,target_shuffle,nb_s972445_mpnn_2,QVQLVESGGGLVQPGGSLRLSCAASPGSPFMFPFWTLGWFRQAPGQ...,IL20,25-176,LKTLNLGSCVIATNLQEIRNGFSEIRGSVQAKDGNIDIRILRRTES...,0,NaN,nb_s972445_mpnn_2_IL20

In [6]:
master_df2 = master_df.drop(columns=["vhh", "vhh_sequence", "target", "target_residues", "target_sequence"])
master_df2

       source            type  binder  KD[M]                  sample
0    germinal        original       0    NaN  nb_s413501_mpnn_3_PDL1
1    germinal        original       0    NaN   nb_s80903_mpnn_4_PDL1
2    germinal        original       0    NaN  nb_s185784_mpnn_4_PDL1
3    germinal        original       0    NaN  nb_s465730_mpnn_4_PDL1
4    germinal        original       0    NaN  nb_s892360_mpnn_4_PDL1
..        ...             ...     ...    ...                     ...
475  germinal  target_shuffle       0    NaN  nb_s276607_mpnn_4_IL20
476  germinal  target_shuffle       0    NaN  nb_s442197_mpnn_3_PDL1
477  germinal  target_shuffle       0    NaN   nb_s776407_mpnn_2_IL3
478  germinal  target_shuffle       0    NaN   nb_s206651_mpnn_1_IL3
479  germinal  target_shuffle       0    NaN  nb_s972445_mpnn_2_IL20

[480 rows x 5 columns]

### merge

In [8]:
scores_df = pd.merge(master_df3, df_2if, on=['sample'], how='inner')
#df = pd.merge(master_df2, preds_df, on=['sample'], how='inner')
# Display the first few rows to verify
print(scores_df[['sample', 'af3_plddt']])

# Save the merged result
scores_df.to_csv(OUTPUT_DIR /'merged_snir.csv', index=False)

                  sample  af3_plddt
0           5ifj_abc_cut  95.404666
1           5ig7_abc_cut  95.599717
2           5ijk_acx_cut  92.439163
3   5ifj_abc_cut_A_D111A  95.282854
4   5ifj_abc_cut_A_K110A  94.871984
5    5ifj_abc_cut_A_S64A  95.613237
6    5ifj_abc_cut_A_W52A  94.814333
7    5ifj_abc_cut_A_Y66A  95.337838
8     5ifj_abc_cut_all_A  93.235998
9   5ifj_abc_cut_B_L116A  95.032996
10   5ifj_abc_cut_B_V38A  95.220947
11  5ifj_abc_cut_B_W107A  95.089607
12   5ifj_abc_cut_B_Y37A  94.723352
13  5ig7_abc_cut_A_K110A  94.950463
14   5ig7_abc_cut_A_W52A  95.457781
15   5ig7_abc_cut_A_Y66A  95.767986
16    5ig7_abc_cut_all_A  92.210506
17  5ig7_abc_cut_B_G114A  95.869087
18  5ig7_abc_cut_B_L116A  95.298420
19   5ig7_abc_cut_B_V38A  95.793462
20  5ig7_abc_cut_B_W107A  92.830579
21   5ig7_abc_cut_B_Y37A  95.631059
22  5ijk_acx_cut_A_I112A  94.094014
23  5ijk_acx_cut_A_I114A  91.142842
24   5ijk_acx_cut_A_K57A  92.231214
25   5ijk_acx_cut_A_R55A  91.770396
26  5ijk_acx_cut_A_T113A  97.319849
27    5ijk_acx_cut_all_A  90.392437
28   5ijk_acx_cut_B_K36A  93.155359
29  5ijk_acx_cut_B_T113A  92.444807
30   5ijk_acx_cut_B_W56A  96.678663
31  5ijk_acx_cut_B_Y107A  93.553850
32  5ijk_acx_cut_B_Y108A  91.641826
33   5ijk_acx_cut_B_Y31A  94.546322
34   5ijk_acx_cut_B_Y38A  91.808649