Preparations:
- load prediction.csv
    - drop the lines with the non-used ifs
    - if there is more then one if, take mean

- add column "sample" to master table
- join them
- drop unnecessary columns (matadata, paths, ranks)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import ast
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score, precision_score, f1_score, precision_recall_curve, confusion_matrix

# Configuration
CSV_PATH =  "/home/bri/pymol/data/predictions/harvey.csv" 
MASTER_PATH =  "/home/bri/pymol/data/harvey/harvey_master.csv" 
YAML_PATH = "/home/bri/pymol/EDA/static/metric_directions.yaml"
OUTPUT_DIR = Path("/home/bri/pymol/EDA/static/harvey_outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


KEEP_INTERFACES = {"A,C", "B,C"}   # as option if there is more than one, default A,B



# Load data
df_if = pd.read_csv(CSV_PATH)
df_if.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 92 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   sample                                  56 non-null     str
 1   binding                                 56 non-null     bool
 2   interface                               56 non-null     str
 3   af3_pae                                 56 non-null     float64
 4   af3_plddt                               56 non-null     float64
 5   af3_interface_dG                        56 non-null     float64
 6   af3_interface_dG_SASA_ratio             56 non-null     float64
 7   af3_ipae                                56 non-null     float64
 8   af3_iplddt                              56 non-null     float64
 9   af3_ipsae                               56 non-null     float64
 10  af3_pdockq                              56 non-null     float64
 11  af3_pdockq2                             56 non-null     float64
 12  af3_lis                                 56 non-null     float64
 13  af3_iptm                                56 non-null     float64
 14  af3_ptm                                 56 non-null     float64
 15  af3_pyros_binder_score                  56 non-null     float64
 16  af3_rank                                56 non-null     float64
 17  af3_ranking_score                       56 non-null     float64
 18  af3_rank0_masif                         55 non-null     float64
 19  cf_af3_rmsd                             56 non-null     float64
 20  cf_pae                                  56 non-null     float64
 21  cf_plddt                                56 non-null     float64
 22  cf_interface_dG                         56 non-null     float64
 23  cf_interface_dG_SASA_ratio              56 non-null     float64
 24  cf_ipae                                 56 non-null     float64
 25  cf_iplddt                               56 non-null     float64
 26  cf_ipsae                                56 non-null     float64
 27  cf_pdockq                               56 non-null     float64
 28  cf_pdockq2                              56 non-null     float64
 29  cf_lis                                  56 non-null     float64
 30  cf_iptm                                 56 non-null     float64
 31  cf_ptm                                  56 non-null     float64
 32  cf_pyros_binder_score                   56 non-null     float64
 33  cf_rank                                 56 non-null     float64
 34  cf_rank0_masif                          55 non-null     float64
 35  pred_ilddt                              56 non-null     float64
 36  pred_lddt                               56 non-null     float64
 37  esmfold_ipae                            56 non-null     float64
 38  esmfold_iplddt                          56 non-null     float64
 39  esmfold_plddt                           56 non-null     float64
 40  esmfold_pae                             56 non-null     float64
 41  esmfold_ptm                             56 non-null     float64
 42  chai_unconstrained_score                56 non-null     float64
 43  chai_unconstrained_model_path           56 non-null     str
 44  chai_constrained_score                  56 non-null     float64
 45  chai_constrained_model_path             56 non-null     str
 46  chai_unconstrained_aggregate_score      56 non-null     float64
 47  chai_unconstrained_ptm                  56 non-null     float64
 48  chai_unconstrained_iptm                 56 non-null     float64
 49  chai_unconstrained_per_chain_ptm        56 non-null     str
 50  chai_unconstrained_per_chain_pair_iptm  56 non-null     str
 51  chai_unconstrained_interface_iptm       56 non-null     float64
 52  chai_unconstrained_ipsae                56 non-null     float64
 53  chai_unconstrained_pdockq               56 non-null     float64
 54  chai_unconstrained_pdockq2              56 non-null     float64
 55  chai_unconstrained_lis                  56 non-null     float64
 56  chai_constrained_aggregate_score        56 non-null     float64
 57  chai_constrained_ptm                    56 non-null     float64
 58  chai_constrained_iptm                   56 non-null     float64
 59  chai_constrained_per_chain_ptm          56 non-null     str
 60  chai_constrained_per_chain_pair_iptm    56 non-null     str
 61  chai_constrained_interface_iptm         56 non-null     float64
 62  chai_constrained_ipsae                  56 non-null     float64
 63  chai_constrained_pdockq                 56 non-null     float64
 64  chai_constrained_pdockq2                56 non-null     float64
 65  chai_constrained_lis                    56 non-null     float64
 66  boltz_free_confidence_score             56 non-null     float64
 67  boltz_free_ptm                          56 non-null     float64
 68  boltz_free_iptm                         56 non-null     float64
 69  boltz_free_plddt                        56 non-null     float64
 70  boltz_free_iplddt                       56 non-null     float64
 71  boltz_free_pde                          56 non-null     float64
 72  boltz_free_ipde                         56 non-null     float64
 73  boltz_free_per_chain_pair_iptm          56 non-null     float64
 74  boltz_free_model_path                   56 non-null     str
 75  boltz_free_ipsae                        56 non-null     float64
 76  boltz_free_pdockq                       56 non-null     float64
 77  boltz_free_pdockq2                      56 non-null     float64
 78  boltz_free_lis                          56 non-null     float64
 79  boltz_template_confidence_score         56 non-null     float64
 80  boltz_template_ptm                      56 non-null     float64
 81  boltz_template_iptm                     56 non-null     float64
 82  boltz_template_plddt                    56 non-null     float64
 83  boltz_template_iplddt                   56 non-null     float64
 84  boltz_template_pde                      56 non-null     float64
 85  boltz_template_ipde                     56 non-null     float64
 86  boltz_template_per_chain_pair_iptm      56 non-null     float64
 87  boltz_template_model_path               56 non-null     str
 88  boltz_template_ipsae                    56 non-null     float64
 89  boltz_template_pdockq                   56 non-null     float64
 90  boltz_template_pdockq2                  56 non-null     float64
 91  boltz_template_lis                      56 non-null     float64
dtypes: bool(1), float64(81), str(10)
memory usage: 40.0 KB

#### all

In [2]:
num_cols = df_if.select_dtypes(include=['number']).columns
other_cols = [c for c in df_if.columns if c not in num_cols and c != 'sample']

agg_dict = {col: 'mean' for col in num_cols}
agg_dict.update({col: 'first' for col in other_cols})

df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

df_1if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,binding,interface,chai_unconstrained_model_path,chai_constrained_model_path,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm,boltz_free_model_path,boltz_template_model_path
0,AT118i4h32_AGTR1,11.528240,78.049861,241.77,7.91,7.356923,76.922909,0.640211,0.4392,0.2198,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8844592571258545, 0.7967235445976257]]","[[[0.8844592571258545, 0.45740675926208496], [...","[[0.899858832359314, 0.9029654264450073]]","[[[0.899858832359314, 0.7897694110870361], [0....",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
1,AT118i4h32_MRGPCRX2,12.439435,74.562329,526.75,19.79,12.266038,60.596945,0.257231,0.1262,0.0341,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8876683115959167, 0.8371615409851074]]","[[[0.8876683115959167, 0.39459025859832764], [...","[[0.8980915546417236, 0.835515022277832]]","[[[0.8980915546417236, 0.5936788320541382], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
2,AT201_AGTR1,12.212700,76.021409,108.25,7.19,18.501786,78.594062,0.426000,0.1468,0.1714,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.885317325592041, 0.7817205786705017]]","[[[0.885317325592041, 0.19592402875423431], [0...","[[0.8954206705093384, 0.82906174659729]]","[[[0.8954206705093384, 0.5672476887702942], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
3,AT201_MRGPCRX2,12.001755,75.830993,238.39,9.45,19.844643,71.049583,0.317248,0.2336,0.0714,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8981631994247437, 0.840274453163147]]","[[[0.8981631994247437, 0.5835593342781067], [0...","[[0.8961554765701294, 0.8428879976272583]]","[[[0.8961554765701294, 0.6239234209060669], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
4,AT202_AGTR1,13.119915,76.458147,299.89,11.87,17.030000,68.662117,0.219051,0.1821,0.0583,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8855280876159668, 0.7832863926887512]]","[[[0.8855280876159668, 0.22815226018428802], [...","[[0.8752248883247375, 0.8392460346221924]]","[[[0.8752248883247375, 0.5595718622207642], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
5,AT202_MRGPCRX2,16.066253,71.030357,397.95,14.91,25.661905,54.736793,0.007376,0.0997,0.0114,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8927343487739563, 0.8273712396621704]]","[[[0.8927343487739563, 0.20616838335990906], [...","[[0.8831577301025391, 0.8069132566452026]]","[[[0.8831577301025391, 0.5096361637115479], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
6,AT203_AGTR1,11.603302,78.053494,77.77,2.87,8.088182,80.329839,0.647259,0.4361,0.3651,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.862318754196167, 0.8046218156814575]]","[[[0.862318754196167, 0.37608620524406433], [0...","[[0.8754035830497742, 0.8123531937599182]]","[[[0.8754035830497742, 0.6163707971572876], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
7,AT204_AA2AR,18.475244,73.484484,504.98,26.73,27.103704,63.955542,0.000000,0.0959,0.0105,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.9030715227127075, 0.7465903759002686]]","[[[0.9030715227127075, 0.21823161840438843], [...","[[0.9020013213157654, 0.7432980537414551]]","[[[0.9020013213157654, 0.2639146149158478], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
8,AT204_AGTR1,16.662872,71.692176,456.19,24.69,14.596774,63.245793,0.000000,0.0919,0.0115,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.9009032845497131, 0.7990964651107788]]","[[[0.9009032845497131, 0.2246391326189041], [0...","[[0.9041344523429871, 0.8222752809524536]]","[[[0.9041344523429871, 0.6109544038772583], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
9,AT205_ACM3,16.165529,73.231713,450.08,19.99,10.601429,62.549086,0.021527,0.0975,0.0155,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8975131511688232, 0.7746583819389343]]","[[[0.8975131511688232, 0.40527528524398804], [...","[[0.8981754779815674, 0.7839779853820801]]","[[[0.8981754779815674, 0.5159655213356018], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
10,AT205_AGTR1,12.078681,77.945758,333.55,11.66,16.094737,72.127838,0.305816,0.2805,0.1133,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8954852819442749, 0.7971125841140747]]","[[[0.8954852819442749, 0.31081849336624146], [...","[[0.9003657102584839, 0.8154690265655518]]","[[[0.9003657102584839, 0.6001021265983582], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
11,AT206_AGTR1,12.140000,77.104133,565.08,17.43,7.664615,73.026588,0.429742,0.3425,0.1524,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8934987187385559, 0.8168030977249146]]","[[[0.8934987187385559, 0.6189501285552979], [0...","[[0.9000794887542725, 0.8263767957687378]]","[[[0.9000794887542725, 0.6687699556350708], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
12,AT207_AGTR1,14.515562,72.984429,575.85,17.79,13.043966,64.423951,0.127196,0.2251,0.0204,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.9021723866462708, 0.7938095927238464]]","[[[0.9021723866462708, 0.48009294271469116], [...","[[0.9140447974205017, 0.8120380640029907]]","[[[0.9140447974205017, 0.5632482767105103], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
13,AT207_MRGPCRX2,11.762713,75.697795,1126.79,32.94,8.712879,67.122512,0.507726,0.2207,0.0812,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.9008268117904663, 0.8316800594329834]]","[[[0.9008268117904663, 0.3829595148563385], [0...","[[0.9152525067329407, 0.8675929307937622]]","[[[0.9152525067329407, 0.7542054653167725], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
14,AT208_AGTR1,13.400510,74.515406,489.56,14.97,12.274658,68.717253,0.228331,0.2595,0.0610,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.895566463470459, 0.8259811401367188]]","[[[0.895566463470459, 0.6455579996109009], [0....","[[0.8955528140068054, 0.8270229697227478]]","[[[0.8955528140068054, 0.6786258816719055], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
15,AT208_MRGPCRX2,12.099813,76.538680,203.40,6.21,10.168966,69.629182,0.249601,0.2311,0.0678,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.9003686904907227, 0.8655581474304199]]","[[[0.9003686904907227, 0.6996217966079712], [0...","[[0.8936228156089783, 0.8567139506340027]]","[[[0.8936228156089783, 0.5774272084236145], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
16,AT209_ACM3,15.559657,73.308805,762.40,26.95,18.626744,63.011355,0.113143,0.1702,0.0220,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8876051902770996, 0.7757290005683899]]","[[[0.8876051902770996, 0.24890118837356567], [...","[[0.8928729295730591, 0.7988908290863037]]","[[[0.8928729295730591, 0.39635714888572693], [...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
17,AT209_AGTR1,14.760581,72.510105,671.46,20.51,14.528947,62.970591,0.121292,0.2023,0.0264,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8895854353904724, 0.8035908341407776]]","[[[0.8895854353904724, 0.43610429763793945], [...","[[0.9006621241569519, 0.8193023204803467]]","[[[0.9006621241569519, 0.7213302850723267], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
18,AT210_AGTR1,12.691293,76.180237,151.40,5.05,9.570339,70.929935,0.299080,0.2898,0.0656,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8891463875770569, 0.8051168918609619]]","[[[0.8891463875770569, 0.4662325382232666], [0...","[[0.902821958065033, 0.8189939260482788]]","[[[0.902821958065033, 0.6878317594528198], [0....",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
19,AT211_ACM3,16.446745,71.794996,1209.77,35.17,21.730556,64.229618,0.055261,0.2579,0.0213,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8511819839477539, 0.786190390586853]]","[[[0.8511819839477539, 0.24678120017051697], [...","[[0.8598822951316833, 0.8038856387138367]]","[[[0.8598822951316833, 0.417564332485199], [0....",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
20,AT211_AGTR1,15.568281,72.819037,384.24,11.52,17.458333,59.721870,0.116996,0.1752,0.0259,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.9039730429649353, 0.8173962831497192]]","[[[0.9039730429649353, 0.6717489957809448], [0...","[[0.9134073257446289, 0.8357183337211609]]","[[[0.9134073257446289, 0.7075044512748718], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
21,AT212_AGTR1,13.847110,74.538897,288.87,10.81,21.531707,67.394865,0.147535,0.1350,0.0281,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.872211754322052, 0.8025923371315002]]","[[[0.872211754322052, 0.2606845498085022], [0....","[[0.8896079659461975, 0.8072039484977722]]","[[[0.8896079659461975, 0.6514948010444641], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
22,AT212_MRGPCRX2,13.067636,74.117945,526.98,17.72,11.962500,63.921086,0.199797,0.1842,0.0461,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8850688934326172, 0.8383941054344177]]","[[[0.8850688934326172, 0.4056294560432434], [0...","[[0.8949531316757202, 0.8464769124984741]]","[[[0.8949531316757202, 0.4619976282119751], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
23,AT213_ACM3,16.087607,73.238243,518.78,16.55,19.611765,66.314420,0.056695,0.2229,0.0191,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.864464521408081, 0.7751399278640747]]","[[[0.864464521408081, 0.27177655696868896], [0...","[[0.8719457387924194, 0.7991185188293457]]","[[[0.8719457387924194, 0.41963282227516174], [...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
24,AT213_AGTR1,14.138736,75.139875,311.90,10.44,10.997222,66.112499,0.120168,0.1948,0.0367,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8747590780258179, 0.7917165756225586]]","[[[0.8747590780258179, 0.3459692895412445], [0...","[[0.8837392926216125, 0.8193203806877136]]","[[[0.8837392926216125, 0.5191982388496399], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
25,CH1_ACM3,12.700779,78.071409,186.24,7.19,15.700000,84.414627,0.671542,0.4800,0.5431,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8825398683547974, 0.7628398537635803]]","[[[0.8825398683547974, 0.21928533911705017], [...","[[0.9041115045547485, 0.7831470966339111]]","[[[0.9041115045547485, 0.6075537800788879], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
26,CH2_ACM3,12.654052,78.288319,206.49,7.86,16.546154,84.516848,0.686851,0.5057,0.5657,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.9011032581329346, 0.7747976183891296]]","[[[0.9011032581329346, 0.560588538646698], [0....","[[0.9000518918037415, 0.7761390209197998]]","[[[0.9000518918037415, 0.5686442255973816], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
27,Nb29_AA2AR,14.911246,79.137338,105.35,3.90,11.309821,82.223881,0.612985,0.4272,0.3025,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.9014462232589722, 0.7441108226776123]]","[[[0.9014462232589722, 0.391018271446228], [0....","[[0.9044357538223267, 0.8893864154815674]]","[[[0.9044357538223267, 0.3619407117366791], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
28,Nb29_ACM3,16.998950,72.876598,288.88,16.42,19.555769,58.810270,0.005718,0.0657,0.0123,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8965845108032227, 0.7774451375007629]]","[[[0.8965845108032227, 0.30402207374572754], [...","[[0.9027241468429565, 0.8125603795051575]]","[[[0.9027241468429565, 0.5946143269538879], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
29,Nb60_ACM3,17.276300,73.093127,166.35,9.89,22.100000,65.052345,0.005977,0.1188,0.0136,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.9014779329299927, 0.7776082158088684]]","[[[0.9014779329299927, 0.45231056213378906], [...","[[0.9062988758087158, 0.7993740439414978]]","[[[0.9062988758087158, 0.5275941491127014], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
30,Nb60_MRGPCRX2,13.892686,72.395864,681.66,19.47,11.333019,59.895196,0.181534,0.1560,0.0218,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8976781964302063, 0.8289141058921814]]","[[[0.8976781964302063, 0.3515624403953552], [0...","[[0.904166579246521, 0.8356736898422241]]","[[[0.904166579246521, 0.504054069519043], [0.4...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
31,Sim0563_AA2AR,15.199062,77.118107,279.04,11.42,20.382609,71.841687,0.347790,0.2057,0.0725,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8947547674179077, 0.7504028081893921]]","[[[0.8947547674179077, 0.2687728703022003], [0...","[[0.8897881507873535, 0.7439739108085632]]","[[[0.8897881507873535, 0.586355447769165], [0....",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
32,Sim0563_MRGPCRX2,10.399938,79.174400,299.80,8.25,7.166234,81.891498,0.684314,0.5380,0.3212,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8970041275024414, 0.8363422155380249]]","[[[0.8970041275024414, 0.4701826274394989], [0...","[[0.8978443145751953, 0.836206316947937]]","[[[0.8978443145751953, 0.6066011190414429], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
33,Sim1846_AGTR1,16.192746,71.790642,154.90,8.33,7.716667,69.257136,0.005107,0.1546,0.0130,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8788759708404541, 0.797477662563324]]","[[[0.8788759708404541, 0.27155905961990356], [...","[[0.897769570350647, 0.8097147941589355]]","[[[0.897769570350647, 0.5513526201248169], [0....",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...
34,Sim1846_MRGPCRX2,11.022852,77.182731,180.20,5.90,8.736792,72.620307,0.479485,0.3095,0.1417,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8832592964172363, 0.8406199216842651]]","[[[0.8832592964172363, 0.5218203067779541], [0...","[[0.8832491636276245, 0.8292175531387329]]","[[[0.8832491636276245, 0.6083658933639526], [0...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
35,Sim3014_MRGPCRX2,12.174620,75.173242,438.13,13.28,12.125000,65.829175,0.248762,0.1979,0.0380,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.9033904671669006, 0.8667539358139038]]","[[[0.9033904671669006, 0.7068060040473938], [0...","[[0.8744826912879944, 0.8399971723556519]]","[[[0.8744826912879944, 0.47338804602622986], [...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
36,Sim4177_MRGPCRX2,11.898365,74.847496,606.80,17.79,11.098305,64.198097,0.341283,0.1753,0.0464,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.884341299533844, 0.8413388133049011]]","[[[0.884341299533844, 0.5382803082466125], [0....","[[0.8929964303970337, 0.845774233341217]]","[[[0.8929964303970337, 0.657489538192749], [0....",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
37,Sim4717_MRGPCRX2,10.490082,78.896985,175.10,5.88,5.747656,79.264479,0.572370,0.4017,0.2418,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...,"[[0.8946914672851562, 0.8297553062438965]]","[[[0.8946914672851562, 0.32395026087760925], [...","[[0.9045283794403076, 0.8445646166801453]]","[[[0.9045283794403076, 0.46451666951179504], [...",/scicore/home/schwede/barta0000/harvey_ds/orig...,/scicore/home/schwede/barta0000/harvey_ds/orig...
38,Sim4784_AA2AR,15.429579,78.533967,95.99,5.01,14.448810,84.903689,0.596587,0.3446,0.3212,...,False,"A,B",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...,"[[0.8991683721542358, 0.7365903258323669]]","[[[0.8991683721542358, 0.3627828359603882], [0...","[[0.8935863971710205, 0.740337610244751]]","[[[0.8935863971710205, 0.4909173846244812], [0...",/scicore/home/schwede/barta0000/harvey_ds/targ...,/scicore/home/schwede/barta0000/harvey_ds/targ...

In [3]:
df_2if = df_1if.drop(columns=["binding", "interface","chai_unconstrained_model_path", "chai_constrained_model_path", "boltz_free_model_path", "boltz_template_model_path"])
df_2if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,boltz_template_ipde,boltz_template_per_chain_pair_iptm,boltz_template_ipsae,boltz_template_pdockq,boltz_template_pdockq2,boltz_template_lis,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm
0,AT118i4h32_AGTR1,11.528240,78.049861,241.77,7.91,7.356923,76.922909,0.640211,0.4392,0.2198,...,0.649316,0.953019,0.871298,0.5023,0.5615,0.6842,"[[0.8844592571258545, 0.7967235445976257]]","[[[0.8844592571258545, 0.45740675926208496], [...","[[0.899858832359314, 0.9029654264450073]]","[[[0.899858832359314, 0.7897694110870361], [0...."
1,AT118i4h32_MRGPCRX2,12.439435,74.562329,526.75,19.79,12.266038,60.596945,0.257231,0.1262,0.0341,...,1.674060,0.892416,0.757991,0.6128,0.6123,0.6028,"[[0.8876683115959167, 0.8371615409851074]]","[[[0.8876683115959167, 0.39459025859832764], [...","[[0.8980915546417236, 0.835515022277832]]","[[[0.8980915546417236, 0.5936788320541382], [0..."
2,AT201_AGTR1,12.212700,76.021409,108.25,7.19,18.501786,78.594062,0.426000,0.1468,0.1714,...,2.173097,0.910365,0.755096,0.4618,0.3734,0.5413,"[[0.885317325592041, 0.7817205786705017]]","[[[0.885317325592041, 0.19592402875423431], [0...","[[0.8954206705093384, 0.82906174659729]]","[[[0.8954206705093384, 0.5672476887702942], [0..."
3,AT201_MRGPCRX2,12.001755,75.830993,238.39,9.45,19.844643,71.049583,0.317248,0.2336,0.0714,...,1.671572,0.926799,0.795390,0.5267,0.5223,0.5838,"[[0.8981631994247437, 0.840274453163147]]","[[[0.8981631994247437, 0.5835593342781067], [0...","[[0.8961554765701294, 0.8428879976272583]]","[[[0.8961554765701294, 0.6239234209060669], [0..."
4,AT202_AGTR1,13.119915,76.458147,299.89,11.87,17.030000,68.662117,0.219051,0.1821,0.0583,...,4.002924,0.822987,0.587241,0.6138,0.2044,0.4111,"[[0.8855280876159668, 0.7832863926887512]]","[[[0.8855280876159668, 0.22815226018428802], [...","[[0.8752248883247375, 0.8392460346221924]]","[[[0.8752248883247375, 0.5595718622207642], [0..."
5,AT202_MRGPCRX2,16.066253,71.030357,397.95,14.91,25.661905,54.736793,0.007376,0.0997,0.0114,...,2.592691,0.792376,0.537988,0.4059,0.3356,0.4029,"[[0.8927343487739563, 0.8273712396621704]]","[[[0.8927343487739563, 0.20616838335990906], [...","[[0.8831577301025391, 0.8069132566452026]]","[[[0.8831577301025391, 0.5096361637115479], [0..."
6,AT203_AGTR1,11.603302,78.053494,77.77,2.87,8.088182,80.329839,0.647259,0.4361,0.3651,...,1.497975,0.910428,0.795326,0.6598,0.6871,0.5950,"[[0.862318754196167, 0.8046218156814575]]","[[[0.862318754196167, 0.37608620524406433], [0...","[[0.8754035830497742, 0.8123531937599182]]","[[[0.8754035830497742, 0.6163707971572876], [0..."
7,AT204_AA2AR,18.475244,73.484484,504.98,26.73,27.103704,63.955542,0.000000,0.0959,0.0105,...,2.225823,0.877184,0.541790,0.1831,0.3296,0.3328,"[[0.9030715227127075, 0.7465903759002686]]","[[[0.9030715227127075, 0.21823161840438843], [...","[[0.9020013213157654, 0.7432980537414551]]","[[[0.9020013213157654, 0.2639146149158478], [0..."
8,AT204_AGTR1,16.662872,71.692176,456.19,24.69,14.596774,63.245793,0.000000,0.0919,0.0115,...,3.520961,0.815329,0.557721,0.5336,0.2333,0.4120,"[[0.9009032845497131, 0.7990964651107788]]","[[[0.9009032845497131, 0.2246391326189041], [0...","[[0.9041344523429871, 0.8222752809524536]]","[[[0.9041344523429871, 0.6109544038772583], [0..."
9,AT205_ACM3,16.165529,73.231713,450.08,19.99,10.601429,62.549086,0.021527,0.0975,0.0155,...,3.146069,0.889565,0.708093,0.3539,0.2981,0.5117,"[[0.8975131511688232, 0.7746583819389343]]","[[[0.8975131511688232, 0.40527528524398804], [...","[[0.8981754779815674, 0.7839779853820801]]","[[[0.8981754779815674, 0.5159655213356018], [0..."
10,AT205_AGTR1,12.078681,77.945758,333.55,11.66,16.094737,72.127838,0.305816,0.2805,0.1133,...,3.379495,0.821988,0.592587,0.5518,0.4039,0.4504,"[[0.8954852819442749, 0.7971125841140747]]","[[[0.8954852819442749, 0.31081849336624146], [...","[[0.9003657102584839, 0.8154690265655518]]","[[[0.9003657102584839, 0.6001021265983582], [0..."
11,AT206_AGTR1,12.140000,77.104133,565.08,17.43,7.664615,73.026588,0.429742,0.3425,0.1524,...,1.158381,0.935807,0.820640,0.6315,0.7949,0.6180,"[[0.8934987187385559, 0.8168030977249146]]","[[[0.8934987187385559, 0.6189501285552979], [0...","[[0.9000794887542725, 0.8263767957687378]]","[[[0.9000794887542725, 0.6687699556350708], [0..."
12,AT207_AGTR1,14.515562,72.984429,575.85,17.79,13.043966,64.423951,0.127196,0.2251,0.0204,...,1.897490,0.902147,0.745535,0.6241,0.5803,0.5907,"[[0.9021723866462708, 0.7938095927238464]]","[[[0.9021723866462708, 0.48009294271469116], [...","[[0.9140447974205017, 0.8120380640029907]]","[[[0.9140447974205017, 0.5632482767105103], [0..."
13,AT207_MRGPCRX2,11.762713,75.697795,1126.79,32.94,8.712879,67.122512,0.507726,0.2207,0.0812,...,2.129303,0.902233,0.760612,0.5927,0.4730,0.6066,"[[0.9008268117904663, 0.8316800594329834]]","[[[0.9008268117904663, 0.3829595148563385], [0...","[[0.9152525067329407, 0.8675929307937622]]","[[[0.9152525067329407, 0.7542054653167725], [0..."
14,AT208_AGTR1,13.400510,74.515406,489.56,14.97,12.274658,68.717253,0.228331,0.2595,0.0610,...,2.079581,0.835657,0.688378,0.6490,0.4953,0.4684,"[[0.895566463470459, 0.8259811401367188]]","[[[0.895566463470459, 0.6455579996109009], [0....","[[0.8955528140068054, 0.8270229697227478]]","[[[0.8955528140068054, 0.6786258816719055], [0..."
15,AT208_MRGPCRX2,12.099813,76.538680,203.40,6.21,10.168966,69.629182,0.249601,0.2311,0.0678,...,2.294088,0.840594,0.663626,0.5836,0.4288,0.5185,"[[0.9003686904907227, 0.8655581474304199]]","[[[0.9003686904907227, 0.6996217966079712], [0...","[[0.8936228156089783, 0.8567139506340027]]","[[[0.8936228156089783, 0.5774272084236145], [0..."
16,AT209_ACM3,15.559657,73.308805,762.40,26.95,18.626744,63.011355,0.113143,0.1702,0.0220,...,3.268070,0.823825,0.613428,0.4815,0.3050,0.4414,"[[0.8876051902770996, 0.7757290005683899]]","[[[0.8876051902770996, 0.24890118837356567], [...","[[0.8928729295730591, 0.7988908290863037]]","[[[0.8928729295730591, 0.39635714888572693], [..."
17,AT209_AGTR1,14.760581,72.510105,671.46,20.51,14.528947,62.970591,0.121292,0.2023,0.0264,...,1.618617,0.901725,0.766039,0.5527,0.5443,0.5774,"[[0.8895854353904724, 0.8035908341407776]]","[[[0.8895854353904724, 0.43610429763793945], [...","[[0.9006621241569519, 0.8193023204803467]]","[[[0.9006621241569519, 0.7213302850723267], [0..."
18,AT210_AGTR1,12.691293,76.180237,151.40,5.05,9.570339,70.929935,0.299080,0.2898,0.0656,...,2.306303,0.927381,0.790658,0.6486,0.4406,0.5812,"[[0.8891463875770569, 0.8051168918609619]]","[[[0.8891463875770569, 0.4662325382232666], [0...","[[0.902821958065033, 0.8189939260482788]]","[[[0.902821958065033, 0.6878317594528198], [0...."
19,AT211_ACM3,16.446745,71.794996,1209.77,35.17,21.730556,64.229618,0.055261,0.2579,0.0213,...,1.353056,0.901093,0.798246,0.6409,0.6484,0.5773,"[[0.8511819839477539, 0.786190390586853]]","[[[0.8511819839477539, 0.24678120017051697], [...","[[0.8598822951316833, 0.8038856387138367]]","[[[0.8598822951316833, 0.417564332485199], [0...."
20,AT211_AGTR1,15.568281,72.819037,384.24,11.52,17.458333,59.721870,0.116996,0.1752,0.0259,...,2.062854,0.902687,0.725552,0.5613,0.4851,0.5271,"[[0.9039730429649353, 0.8173962831497192]]","[[[0.9039730429649353, 0.6717489957809448], [0...","[[0.9134073257446289, 0.8357183337211609]]","[[[0.9134073257446289, 0.7075044512748718], [0..."
21,AT212_AGTR1,13.847110,74.538897,288.87,10.81,21.531707,67.394865,0.147535,0.1350,0.0281,...,2.184377,0.850127,0.670294,0.6698,0.5068,0.5318,"[[0.872211754322052, 0.8025923371315002]]","[[[0.872211754322052, 0.2606845498085022], [0....","[[0.8896079659461975, 0.8072039484977722]]","[[[0.8896079659461975, 0.6514948010444641], [0..."
22,AT212_MRGPCRX2,13.067636,74.117945,526.98,17.72,11.962500,63.921086,0.199797,0.1842,0.0461,...,2.775124,0.870669,0.686888,0.5171,0.2257,0.5530,"[[0.8850688934326172, 0.8383941054344177]]","[[[0.8850688934326172, 0.4056294560432434], [0...","[[0.8949531316757202, 0.8464769124984741]]","[[[0.8949531316757202, 0.4619976282119751], [0..."
23,AT213_ACM3,16.087607,73.238243,518.78,16.55,19.611765,66.314420,0.056695,0.2229,0.0191,...,2.257096,0.895267,0.756430,0.3747,0.2208,0.5462,"[[0.864464521408081, 0.7751399278640747]]","[[[0.864464521408081, 0.27177655696868896], [0...","[[0.8719457387924194, 0.7991185188293457]]","[[[0.8719457387924194, 0.41963282227516174], [..."
24,AT213_AGTR1,14.138736,75.139875,311.90,10.44,10.997222,66.112499,0.120168,0.1948,0.0367,...,2.641302,0.782540,0.580509,0.5421,0.3179,0.4137,"[[0.8747590780258179, 0.7917165756225586]]","[[[0.8747590780258179, 0.3459692895412445], [0...","[[0.8837392926216125, 0.8193203806877136]]","[[[0.8837392926216125, 0.5191982388496399], [0..."
25,CH1_ACM3,12.700779,78.071409,186.24,7.19,15.700000,84.414627,0.671542,0.4800,0.5431,...,1.482290,0.908917,0.731504,0.5222,0.5383,0.5389,"[[0.8825398683547974, 0.7628398537635803]]","[[[0.8825398683547974, 0.21928533911705017], [...","[[0.9041115045547485, 0.7831470966339111]]","[[[0.9041115045547485, 0.6075537800788879], [0..."
26,CH2_ACM3,12.654052,78.288319,206.49,7.86,16.546154,84.516848,0.686851,0.5057,0.5657,...,1.001120,0.935847,0.822143,0.4864,0.6087,0.5995,"[[0.9011032581329346, 0.7747976183891296]]","[[[0.9011032581329346, 0.560588538646698], [0....","[[0.9000518918037415, 0.7761390209197998]]","[[[0.9000518918037415, 0.5686442255973816], [0..."
27,Nb29_AA2AR,14.911246,79.137338,105.35,3.90,11.309821,82.223881,0.612985,0.4272,0.3025,...,3.064893,0.875384,0.602017,0.1788,0.1304,0.4676,"[[0.9014462232589722, 0.7441108226776123]]","[[[0.9014462232589722, 0.391018271446228], [0....","[[0.9044357538223267, 0.8893864154815674]]","[[[0.9044357538223267, 0.3619407117366791], [0..."
28,Nb29_ACM3,16.998950,72.876598,288.88,16.42,19.555769,58.810270,0.005718,0.0657,0.0123,...,2.207983,0.878633,0.734377,0.5650,0.5922,0.5501,"[[0.8965845108032227, 0.7774451375007629]]","[[[0.8965845108032227, 0.30402207374572754], [...","[[0.9027241468429565, 0.8125603795051575]]","[[[0.9027241468429565, 0.5946143269538879], [0..."
29,Nb60_ACM3,17.276300,73.093127,166.35,9.89,22.100000,65.052345,0.005977,0.1188,0.0136,...,3.051749,0.855347,0.670276,0.4476,0.3161,0.4845,"[[0.9014779329299927, 0.7776082158088684]]","[[[0.9014779329299927, 0.45231056213378906], [...","[[0.9062988758087158, 0.7993740439414978]]","[[[0.9062988758087158, 0.5275941491127014], [0..."
30,Nb60_MRGPCRX2,13.892686,72.395864,681.66,19.47,11.333019,59.895196,0.181534,0.1560,0.0218,...,2.726842,0.842142,0.673291,0.4649,0.2602,0.5186,"[[0.8976781964302063, 0.8289141058921814]]","[[[0.8976781964302063, 0.3515624403953552], [0...","[[0.904166579246521, 0.8356736898422241]]","[[[0.904166579246521, 0.504054069519043], [0.4..."
31,Sim0563_AA2AR,15.199062,77.118107,279.04,11.42,20.382609,71.841687,0.347790,0.2057,0.0725,...,2.571573,0.961794,0.869656,0.4734,0.2414,0.5789,"[[0.8947547674179077, 0.7504028081893921]]","[[[0.8947547674179077, 0.2687728703022003], [0...","[[0.8897881507873535, 0.7439739108085632]]","[[[0.8897881507873535, 0.586355447769165], [0...."
32,Sim0563_MRGPCRX2,10.399938,79.174400,299.80,8.25,7.166234,81.891498,0.684314,0.5380,0.3212,...,2.836210,0.816579,0.604948,0.4424,0.2478,0.4631,"[[0.8970041275024414, 0.8363422155380249]]","[[[0.8970041275024414, 0.4701826274394989], [0...","[[0.8978443145751953, 0.836206316947937]]","[[[0.8978443145751953, 0.6066011190414429], [0..."
33,Sim1846_AGTR1,16.192746,71.790642,154.90,8.33,7.716667,69.257136,0.005107,0.1546,0.0130,...,2.291587,0.857510,0.650727,0.5882,0.5584,0.5104,"[[0.8788759708404541, 0.797477662563324]]","[[[0.8788759708404541, 0.27155905961990356], [...","[[0.897769570350647, 0.8097147941589355]]","[[[0.897769570350647, 0.5513526201248169], [0...."
34,Sim1846_MRGPCRX2,11.022852,77.182731,180.20,5.90,8.736792,72.620307,0.479485,0.3095,0.1417,...,2.590167,0.852425,0.650256,0.6271,0.4630,0.5145,"[[0.8832592964172363, 0.8406199216842651]]","[[[0.8832592964172363, 0.5218203067779541], [0...","[[0.8832491636276245, 0.8292175531387329]]","[[[0.8832491636276245, 0.6083658933639526], [0..."
35,Sim3014_MRGPCRX2,12.174620,75.173242,438.13,13.28,12.125000,65.829175,0.248762,0.1979,0.0380,...,1.805392,0.893692,0.749998,0.5160,0.4820,0.5889,"[[0.9033904671669006, 0.8667539358139038]]","[[[0.9033904671669006, 0.7068060040473938], [0...","[[0.8744826912879944, 0.8399971723556519]]","[[[0.8744826912879944, 0.47338804602622986], [..."
36,Sim4177_MRGPCRX2,11.898365,74.847496,606.80,17.79,11.098305,64.198097,0.341283,0.1753,0.0464,...,2.876413,0.876512,0.676726,0.5910,0.3115,0.5467,"[[0.884341299533844, 0.8413388133049011]]","[[[0.884341299533844, 0.5382803082466125], [0....","[[0.8929964303970337, 0.845774233341217]]","[[[0.8929964303970337, 0.657489538192749], [0...."
37,Sim4717_MRGPCRX2,10.490082,78.896985,175.10,5.88,5.747656,79.264479,0.572370,0.4017,0.2418,...,2.830023,0.818734,0.588997,0.5425,0.4046,0.4527,"[[0.8946914672851562, 0.8297553062438965]]","[[[0.8946914672851562, 0.32395026087760925], [...","[[0.9045283794403076, 0.8445646166801453]]","[[[0.9045283794403076, 0.46451666951179504], [..."
38,Sim4784_AA2AR,15.429579,78.533967,95.99,5.01,14.448810,84.903689,0.596587,0.3446,0.3212,...,1.303256,0.954544,0.852636,0.5912,0.6906,0.5921,"[[0.8991683721542358, 0.7365903258323669]]","[[[0.8991683721542358, 0.3627828359603882], [0...","[[0.8935863971710205, 0.740337610244751]]","[[[0.8935863971710205, 0.4909173846244812], [0..."
39,Sim4784_MRGPCRX2,11.134044,76.737652,236.61,8.04,9.514583,73.505507,0.456124,0.2702,0.1284,...,2.467637,0.802716,0.596930,0.5002,0.2950,0.4767,"[[0.9030437469482422, 0.8411462306976318]]","[[[0.9030437469482422, 0.5442968010902405], [0...","[[0.9032381176948547, 0.845802903175354]]","[[[0.9032381176948547, 0.5318591594696045], [0..."
40,Sim4784_R101E_MRGPCRX2,12.570202,74.052318,717.08,21.91,10.443750,64.591960,0.324790,0.1809,0.0494,...,2.000758,0.881197,0.710744,0.4990,0.4307,0.5627,"[[0.9000670909881592, 0.835800051689148]]","[[[0.9000670909881592, 0.459451824426651], [0....","[[0.9055023193359375, 0.8622872233390808]]","[[[0.9055023193359375, 0.6171191334724426], [0..."
41,Sim4784_W103D_MRGPCRX2,12.080430,75.425627,414.83,15.00,12.098936,69.363549,0.326343,0.2244,0.0665,...,2.442112,0.852360,0.668994,0.5658,0.4081,0.5381,"[[0.9011346101760864, 0.8442370891571045]]","[[[0.9011346101760864, 0.45624974370002747], [...","[[0.9080188274383545, 0.8518809676170349]]","[[[0.9080188274383545, 0.6404186487197876], [0..."
42,Sim4784_W103G_MRGPCRX2,10.669275,78.383291,162.53,6.06,9.354444,77.442118,0.536485,0.3224,0.2147,...,1.874488,0.900280,0.740609,0.5220,0.5221,0.5967,"[[0.9017744064331055, 0.8496731519699097]]","[[[0.9017744064331055, 0.5222769975662231], [0...","[[0.90174800157547, 0.850956916809082]]","[[[0.90174800157547, 0.5441616773605347], [0.4..."
43,Sim7252_AGTR1,15.413011,72.390119,393.46,14.11,12.644915,62.798773,0.039121,0.1691,0.0176,...,3.157622,0.865163,0.653923,0.5980,0.3030,0.5069,"[[0.8859579563140869, 0.8068640232086182]]","[[[0.8859579563140869, 0.4353317618370056], [0...","[[0.8913190364837646, 0.8039253950119019]]","[[[0.8913190364837646, 0.4962422251701355], [0..."
44,Sim7252_MRGPCRX2,11.907649,76.717782,239.50,7.26,8.263235,74.310165,0.488423,0.4425,0.1650,...,2.087020,0.870845,0.717581,0.3279,0.2536,0.5538,"[[0.895521879196167, 0.8443046808242798]]","[[[0.895521879196167, 0.6090095639228821], [0....","[[0.8990142345428467, 0.8605393171310425]]","[[[0.8990142345428467, 0.704846203327179], [0...."
45,Sim7492_MRGPCRX2,12.194364,74.520081,492.95,12.38,11.263514,65.323389,0.287933,0.2722,0.0437,...,1.889146,0.907365,0.757390,0.6171,0.5155,0.6052,"[[0.8956150412559509, 0.8551205992698669]]","[[[0.8956150412559509, 0.6946191787719727], [0...","[[0.8840287327766418, 0.8257433176040649]]","[[[0.8840287327766418, 0.6358524560928345], [0..."
46,Sim8619_AGTR1,15.188792,73.813972,322.92,11.49,24.377778,61.395177,0.005555,0.1324,0.0121,...,2.902359,0.822919,0.682927,0.6827,0.4051,0.4720,"[[0.875075101852417, 0.801060140132904]]","[[[0.875075101852417, 0.2935543656349182], [0....","[[0.8787093162536621, 0.8149463534355164]]","[[[0.8787093162536621, 0.5804389715194702], [0..."
47,Sim8619_MRGPCRX2,12.956108,75.153624,309.52,9.99,10.096226,64.879956,0.167816,0.1620,0.0371,...,2.146569,0.845652,0.677488,0.5188,0.3163,0.5056,"[[0.8901891708374023, 0.8522862792015076]]","[[[0.8901891708374023, 0.565464973449707], [0....","[[0.8819963932037354, 0.8422757983207703]]","[[[0.8819963932037354, 0.5301600694656372], [0..."
48,Sim8619_R102A_MRGPCRX2,14.413383,72.521532,534.99,16.33,13.687963,59.309462,0.080359,0.1348,0.0186,...,1.506799,0.882560,0.710524,0.5836,0.4783,0.5713,"[[0.8842890858650208, 0.8388382196426392]]","[[[0.8842890858650208, 0.4644557237625122], [0...","[[0.8864544630050659, 0.8358476161956787]]","[[[0.8864544630050659, 0.5190313458442688], [0..."
49,Sim8619_Y100G_MRGPCRX2,12.361698,75.555399,360.84,10.87,10.239000,66.450982,0.264075,0.2081,0.0427,...,2.312684,0.879148,0.716443,0.6158,0.5341,0.5432,"[[0.8939181566238403, 0.8487788438796997]]","[[[0.8939181566238403, 0.6060372591018677], [0...","[[0.8935202360153198, 0.8357490301132202]]","[[[0.8935202360153198, 0.6238278746604919], [0..."
50,Sim8619_Y105D_MRGPCRX2,13.973779,73.199143,384.66,13.19,11.178431,60.098942,0.091898,0.1225,0.0214,...,1.885157,0.880534,0.715264,0.5755,0.5038,0.5715,"[[0.8862564563751221, 0.8401035070419312]]","[[[0.8862564563751221, 0.36032792925834656], [...","[[0.8921672701835632, 0.8375456929206848]]","[[[0.8921672701835632, 0.5528170466423035], [0..."
51,Sim8619_Y105G_MRGPCRX2,11.229539,79.729492,173.79,5.25,5.886806,78.700795,0.571629,0.4939,0.2399,...,2.458580,0.838813,0.650788,0.6130,0.4259,0.5098,"[[0.8857040405273438, 0.8421773314476013]]","[[[0.8857040405273438, 0.4905948042869568], [0...","[[0.8881192207336426, 0.8450706601142883]]","[[[0.8881192207336426, 0.5385450720787048], [0..."
52,Sim9877_AA2AR,17.264040,74.521448,582.39,23.52,25.648529,60.558094,0.035290,0.1114,0.0150,...,3.589859,0.858048,0.575044,0.3413,0.2622,0.4164,"[[0.8961482644081116, 0.74364173412323]]","[[[0.8961482644081116, 0.2548825740814209], [0...","[[0.8735616207122803, 0.7281084060668945]]","[[[0.8735616207122803, 0.45187342166900635], [..."
53,Sim9877_I102D_MRGPCRX2,10.812023,77.649846,309.06,9.75,7.893846,72.556352,0.527363,0.3559,0.1618,...,1.852492,0.906292,0.764750,0.6342,0.6545,0.6089,"[[0.8827186822891235, 0.8424497842788696]]","[[[0.8827186822891235, 0.5357435941696167], [0...","[[0.9010488986968994, 0.8487441539764404]]","[[[0.9010488986968994, 0.5972872972488403], [0..."
54,Sim9877_MRGPCRX2,11.463827,76.597191,623.54,19.76,9.520588,70.815334,0.440808,0.3323,0.0997,...,1.974256,0.913437,0.795302,0.6323,0.5088,0.6261,"[[0.9002116322517395, 0.8383499383926392]]","[[[0.9002116322517395, 0.4335451126098633], [0...","[[0.9006841778755188, 0.8448808193206787]]","[[[0.9006841778755188, 0.6477355360984802], [0..."
55,Sim9877_Y106A_MRGPCRX2,12.674238,74.633998,465.38,15.40,12.475862,61.897908,0.236706,0.2187,0.0346,...,2.048432,0.902448,0.756813,0.5398,0.3872,0.5917,"[[0.8842341303825378, 0.8396154046058655]]","[[[0.8842341303825378, 0.44769060611724854], [...","[[0.8988289833068848, 0.8458497524261475]]","[[[0.8988289833068848, 0.6713229417800903], [0..."

## master df

##### snir

In [5]:
# for snir data
master_df = pd.read_csv(MASTER_PATH, delimiter=';')
master_df

,source,type,sample,fab,interface,vh/vl,target,target_residues,target_sequence,binder,KD[M],notes
0,snir_ab,original,5ifj_abc_cut,1000.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
1,snir_ab,original,5ifj_abc_cut,1000.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
2,snir_ab,original,5ig7_abc_cut,10.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
3,snir_ab,original,5ig7_abc_cut,10.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
4,snir_ab,original,5ijk_acx_cut,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,1,0.000001,Fab 1E01 + KD[M] approximated from Snir et. al...
...,...,...,...,...,...,...,...,...,...,...,...,...
65,snir_ab,alanine_scan,5ijk_acx_cut_B_Y108A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
66,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
67,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLASSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
68,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
69,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNALAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN

In [6]:
master_df2 = master_df.drop(columns=["interface", "fab", "vh/vl", "target", "target_residues", "target_sequence", "notes"])
master_df2

     source          type                sample  binder     KD[M]
0   snir_ab      original          5ifj_abc_cut       1  0.000010
1   snir_ab      original          5ifj_abc_cut       1  0.000010
2   snir_ab      original          5ig7_abc_cut       1  0.000100
3   snir_ab      original          5ig7_abc_cut       1  0.000100
4   snir_ab      original          5ijk_acx_cut       1  0.000001
..      ...           ...                   ...     ...       ...
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
66  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
68  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

[70 rows x 5 columns]

In [7]:
master_df3 = master_df2.drop_duplicates(keep="last")
master_df3

     source          type                sample  binder     KD[M]
1   snir_ab      original          5ifj_abc_cut       1  0.000010
3   snir_ab      original          5ig7_abc_cut       1  0.000100
5   snir_ab      original          5ijk_acx_cut       1  0.000001
7   snir_ab  alanine_scan  5ifj_abc_cut_A_D111A       0       NaN
9   snir_ab  alanine_scan  5ifj_abc_cut_A_K110A       0       NaN
11  snir_ab  alanine_scan   5ifj_abc_cut_A_S64A       0       NaN
13  snir_ab  alanine_scan   5ifj_abc_cut_A_W52A       0       NaN
15  snir_ab  alanine_scan   5ifj_abc_cut_A_Y66A       0       NaN
17  snir_ab  alanine_scan    5ifj_abc_cut_all_A       0       NaN
19  snir_ab  alanine_scan  5ifj_abc_cut_B_L116A       0       NaN
21  snir_ab  alanine_scan   5ifj_abc_cut_B_V38A       0       NaN
23  snir_ab  alanine_scan  5ifj_abc_cut_B_W107A       0       NaN
25  snir_ab  alanine_scan   5ifj_abc_cut_B_Y37A       0       NaN
27  snir_ab  alanine_scan  5ig7_abc_cut_A_K110A       0       NaN
29  snir_ab  alanine_scan   5ig7_abc_cut_A_W52A       0       NaN
31  snir_ab  alanine_scan   5ig7_abc_cut_A_Y66A       0       NaN
33  snir_ab  alanine_scan    5ig7_abc_cut_all_A       0       NaN
35  snir_ab  alanine_scan  5ig7_abc_cut_B_G114A       0       NaN
37  snir_ab  alanine_scan  5ig7_abc_cut_B_L116A       0       NaN
39  snir_ab  alanine_scan   5ig7_abc_cut_B_V38A       0       NaN
41  snir_ab  alanine_scan  5ig7_abc_cut_B_W107A       0       NaN
43  snir_ab  alanine_scan   5ig7_abc_cut_B_Y37A       0       NaN
45  snir_ab  alanine_scan  5ijk_acx_cut_A_I112A       0       NaN
47  snir_ab  alanine_scan  5ijk_acx_cut_A_I114A       0       NaN
49  snir_ab  alanine_scan   5ijk_acx_cut_A_K57A       0       NaN
51  snir_ab  alanine_scan   5ijk_acx_cut_A_R55A       0       NaN
53  snir_ab  alanine_scan  5ijk_acx_cut_A_T113A       0       NaN
55  snir_ab  alanine_scan    5ijk_acx_cut_all_A       0       NaN
57  snir_ab  alanine_scan   5ijk_acx_cut_B_K36A       0       NaN
59  snir_ab  alanine_scan  5ijk_acx_cut_B_T113A       0       NaN
61  snir_ab  alanine_scan   5ijk_acx_cut_B_W56A       0       NaN
63  snir_ab  alanine_scan  5ijk_acx_cut_B_Y107A       0       NaN
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

##### mcmahon / germinal

In [24]:

master= pd.read_csv(MASTER_PATH, delimiter=';')
master_df = master.drop(columns=["Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17"])
master_df.head()

master_df.to_csv("/home/bri/pymol/data/harvey/harvey_master.csv", index=False )

In [5]:
AMBIGUOUS_TARGET= "HSA"   # test

def create_sample_id(row):
    vhh = str(row['vhh'])
    target = str(row['target'])
    residues = str(row['target_residues'])
    
    # Check if target is (ambigous target, meaning the same target has different version --> target residues are needed to be able to identify it, the only one for now is HSA) to apply the specific naming convention
    if target == AMBIGUOUS_TARGET:
        return f"{vhh}_{target}_{residues}"
    else:
        return f"{vhh}_{target}"

# 1. Create the 'sample' column in the master table
master_df['sample'] = master_df.apply(create_sample_id, axis=1)
master_df

,source,type,vhh,vhh_sequence,target,target_residues,target_sequence,binder,KD[M],EC50[M],notes,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,sample
0,harvey,original,AT118i4h32,EVQLVESGGGLVQPGGSLRLSCAASGYIYRRYRMGWYRQAPGKGRE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1,NaN,NaN,8TH3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT118i4h32_AGTR1
1,harvey,original,AT201,QVQLQESGGGLVQAGGSLRLSCAASGTISDPPYMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT201_AGTR1
2,harvey,original,AT202,QVQLQESGGGLVQAGGSLRLSCAASGYIFDLPYMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT202_AGTR1
3,harvey,original,AT203,QVQLQESGGLVQAGGSLRLSCAASGYISRSYDMGWYRQAPGKEREL...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT203_AGTR1
4,harvey,original,AT204,QVQLQESGGGLVQAGGSLRLSCAASGYIFTRGFMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT204_AGTR1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,harvey,target_shuffle,Sim7252,QVQLQESGGGLVQAGGSLRLSCAASGSISRWLGMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim7252_AGTR1
61,harvey,target_shuffle,Sim7492,QVQLQESGGGLVQAGGSLRLSCAASGNIFRIGPMGWYRQAPGKERE...,ACM3,1-394,MALHSNSTTSPLFPNISSSWVHSPSEAGLPLGTVTQLGSYNISQET...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim7492_ACM3
62,harvey,target_shuffle,Sim8619,QVQLQESGGGLVQAGGSLRLSCAASGSIFYIRGMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim8619_AGTR1
63,harvey,target_shuffle,Sim9877,QVQLQESGGGLVQAGGSLRLSCAASGYISSFPVMGWYRQAPGKERE...,AA2AR,1-472,MKTIIALSYIFCLVFADYKDDDDAMVFLSGQASDSSQCTQPPAPVQ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim9877_AA2AR
64,harvey,target_shuffle,Nb60,QVQLQESGGGLVQAGGSLRLSCAASGSIFSLNDMGWYRQAPGKLRE...,ACM3,1-394,MALHSNSTTSPLFPNISSSWVHSPSEAGLPLGTVTQLGSYNISQET...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nb60_ACM3

In [14]:
master_df2 = master_df.drop(columns=["vhh", "vhh_sequence", "target", "target_residues", "target_sequence", "notes", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17"])

master_df2

    source            type  binder KD[M]  EC50[M]            sample
0   harvey        original       1   NaN      NaN  AT118i4h32_AGTR1
1   harvey        original       1   NaN      NaN       AT201_AGTR1
2   harvey        original       1   NaN      NaN       AT202_AGTR1
3   harvey        original       1   NaN      NaN       AT203_AGTR1
4   harvey        original       1   NaN      NaN       AT204_AGTR1
..     ...             ...     ...   ...      ...               ...
60  harvey  target_shuffle       0   NaN      NaN     Sim7252_AGTR1
61  harvey  target_shuffle       0   NaN      NaN      Sim7492_ACM3
62  harvey  target_shuffle       0   NaN      NaN     Sim8619_AGTR1
63  harvey  target_shuffle       0   NaN      NaN     Sim9877_AA2AR
64  harvey  target_shuffle       0   NaN      NaN         Nb60_ACM3

[65 rows x 6 columns]

### merge

In [15]:
scores_df = pd.merge(master_df2, df_2if, on=['sample'], how='inner')
#df = pd.merge(master_df2, preds_df, on=['sample'], how='inner')
# Display the first few rows to verify
print(scores_df[['sample', 'af3_plddt']])

# Save the merged result
scores_df.to_csv(OUTPUT_DIR /'merged_harvey.csv', index=False)

                    sample  af3_plddt
0         AT118i4h32_AGTR1  78.049861
1              AT201_AGTR1  76.021409
2              AT202_AGTR1  76.458147
3              AT203_AGTR1  78.053494
4              AT204_AGTR1  71.692176
5              AT205_AGTR1  77.945758
6              AT206_AGTR1  77.104133
7              AT207_AGTR1  72.984429
8              AT208_AGTR1  74.515406
9              AT209_AGTR1  72.510105
10             AT210_AGTR1  76.180237
11             AT211_AGTR1  72.819037
12             AT212_AGTR1  74.538897
13             AT213_AGTR1  75.139875
14                CH1_ACM3  78.071409
15                CH2_ACM3  78.288319
16              Nb29_AA2AR  79.137338
17        Sim0563_MRGPCRX2  79.174400
18        Sim1846_MRGPCRX2  77.182731
19        Sim3014_MRGPCRX2  75.173242
20        Sim4177_MRGPCRX2  74.847496
21        Sim4717_MRGPCRX2  78.896985
22        Sim4784_MRGPCRX2  76.737652
23        Sim7252_MRGPCRX2  76.717782
24        Sim7492_MRGPCRX2  74.520081
25        Sim8619_MRGPCRX2  75.153624
26        Sim9877_MRGPCRX2  76.597191
27           Nb60_MRGPCRX2  72.395864
28  Sim8619_Y100G_MRGPCRX2  75.555399
29  Sim8619_R102A_MRGPCRX2  72.521532
30  Sim8619_Y105D_MRGPCRX2  73.199143
31  Sim8619_Y105G_MRGPCRX2  79.729492
32  Sim9877_I102D_MRGPCRX2  77.649846
33  Sim9877_Y106A_MRGPCRX2  74.633998
34  Sim4784_R101E_MRGPCRX2  74.052318
35  Sim4784_W103D_MRGPCRX2  75.425627
36  Sim4784_W103G_MRGPCRX2  78.383291
37     AT118i4h32_MRGPCRX2  74.562329
38          AT201_MRGPCRX2  75.830993
39          AT202_MRGPCRX2  71.030357
40             AT204_AA2AR  73.484484
41              AT205_ACM3  73.231713
42          AT207_MRGPCRX2  75.697795
43          AT208_MRGPCRX2  76.538680
44              AT209_ACM3  73.308805
45              AT211_ACM3  71.794996
46          AT212_MRGPCRX2  74.117945
47              AT213_ACM3  73.238243
48               Nb29_ACM3  72.876598
49           Sim0563_AA2AR  77.118107
50           Sim1846_AGTR1  71.790642
51           Sim4784_AA2AR  78.533967
52           Sim7252_AGTR1  72.390119
53           Sim8619_AGTR1  73.813972
54           Sim9877_AA2AR  74.521448
55               Nb60_ACM3  73.093127