Preparations:
- load prediction.csv
    - drop the lines with the non-used ifs
    - if there is more then one if, take mean

- add column "sample" to master table
- join them
- drop unnecessary columns (matadata, paths, ranks)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import ast
from pathlib import Path
from sklearn.metrics import roc_auc_score, average_precision_score, precision_score, f1_score, precision_recall_curve, confusion_matrix

# Configuration
CSV_PATH =  "/home/bri/pymol/data/predictions/preds_snir.csv" 
MASTER_PATH =  "/home/bri/pymol/data/3ab/table/master_table_snir.csv" 
YAML_PATH = "/home/bri/pymol/EDA/static/metric_directions.yaml"
OUTPUT_DIR = Path("/home/bri/pymol/EDA/static/snir_outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


KEEP_INTERFACES = {"A,C", "B,C"}   # as option if there is more than one, default A,B



# Load data
df_if = pd.read_csv(CSV_PATH)
df_if.info()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Columns: 138 entries, sample to esmfold_mpnn_nll_b
dtypes: bool(1), float64(127), str(10)
memory usage: 218.5 KB

#### all

In [2]:
num_cols = df_if.select_dtypes(include=['number']).columns
other_cols = [c for c in df_if.columns if c not in num_cols and c != 'sample']

agg_dict = {col: 'mean' for col in num_cols}
agg_dict.update({col: 'first' for col in other_cols})

df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

df_1if

/tmp/ipykernel_5272/4193676620.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,binding,interface,chai_unconstrained_model_path,chai_constrained_model_path,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm,boltz_free_model_path,boltz_template_model_path
0,5ifj_abc_cut,2.593883,95.404666,28.410000,2.370000,1.988426,95.031040,0.824021,0.321900,0.872133,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9454320669174194, 0.9492036700248718, 0.17...","[[[0.9454320669174194, 0.8899917602539062, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
1,5ifj_abc_cut_A_D111A,2.815847,95.282854,57.816667,3.936667,2.304955,94.104966,0.806316,0.302767,0.856633,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.9454193711280823, 0.9488046169281006, 0.17...","[[[0.9454193711280823, 0.8907997608184814, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
2,5ifj_abc_cut_A_K110A,2.790728,94.871984,36.826667,3.240000,2.416944,92.917901,0.810150,0.296900,0.830000,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9449247717857361, 0.9489190578460693, 0.17...","[[[0.9449247717857361, 0.889130175113678, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
3,5ifj_abc_cut_A_S64A,2.539446,95.613237,34.810000,2.686667,1.973646,95.207555,0.818178,0.312200,0.889533,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9445436000823975, 0.9495869874954224, 0.17...","[[[0.9445436000823975, 0.8924098014831543, 0.0...","[[0.945385217666626, 0.948758602142334, 0.1724...","[[[0.945385217666626, 0.8885297775268555, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
4,5ifj_abc_cut_A_W52A,3.005329,94.814333,45.003333,4.813333,2.193750,92.632748,0.755118,0.311567,0.809633,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9452440142631531, 0.9471760392189026, 0.16...","[[[0.9452440142631531, 0.8792759776115417, 0.0...","[[0.9452540874481201, 0.9489129781723022, 0.17...","[[[0.9452540874481201, 0.8904703855514526, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
5,5ifj_abc_cut_A_Y66A,2.701376,95.337838,32.103333,2.763333,2.138492,94.162554,0.805907,0.308767,0.858167,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9473956227302551, 0.9488828778266907, 0.16...","[[[0.9473956227302551, 0.8850024938583374, 0.0...","[[0.9453608989715576, 0.9489309191703796, 0.17...","[[[0.9453608989715576, 0.8903481960296631, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
6,5ifj_abc_cut_B_L116A,2.806607,95.032996,30.606667,2.200000,2.177498,94.090785,0.793489,0.295733,0.844567,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9485109448432922, 0.9499985575675964, 0.17...","[[[0.9485109448432922, 0.8920019865036011, 0.0...","[[0.9452025294303894, 0.9490475058555603, 0.17...","[[[0.9452025294303894, 0.8905109763145447, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
7,5ifj_abc_cut_B_V38A,2.714935,95.220947,37.886667,2.943333,2.238356,93.849034,0.803100,0.308100,0.858500,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9468277096748352, 0.9472519159317017, 0.10...","[[[0.9468277096748352, 0.8879522085189819, 0.0...","[[0.945318341255188, 0.9495519995689392, 0.177...","[[[0.945318341255188, 0.890434980392456, 0.072...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
8,5ifj_abc_cut_B_Y37A,3.004751,94.723352,19.743333,1.660000,2.273611,92.894702,0.721584,0.300000,0.815433,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.940564751625061, 0.9448128938674927, 0.095...","[[[0.940564751625061, 0.8819113969802856, 0.04...","[[0.9450069665908813, 0.94929438829422, 0.1781...","[[[0.9450069665908813, 0.889803946018219, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
9,5ifj_abc_cut_all_A,3.597543,93.235998,39.330000,4.260000,2.361091,86.447573,0.413262,0.275333,0.470667,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9467074275016785, 0.9420090913772583, 0.11...","[[[0.9467074275016785, 0.8753525018692017, 0.0...","[[0.9453179836273193, 0.9489884376525879, 0.17...","[[[0.9453179836273193, 0.8899396657943726, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
10,5ig7_abc_cut,2.572969,95.599717,38.373333,2.653333,1.920729,95.341065,0.821896,0.317900,0.896167,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9455351233482361, 0.9491659998893738, 0.17...","[[[0.9455351233482361, 0.891846776008606, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
11,5ig7_abc_cut_A_K110A,2.806122,94.950463,30.576667,2.670000,2.365965,93.257680,0.801589,0.312800,0.839000,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9444799423217773, 0.9482003450393677, 0.09...","[[[0.9444799423217773, 0.8866336941719055, 0.0...","[[0.9459781646728516, 0.9495248794555664, 0.17...","[[[0.9459781646728516, 0.8912208080291748, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
12,5ig7_abc_cut_A_W52A,2.731340,95.457781,25.323333,2.083333,1.998690,94.535086,0.795046,0.325567,0.874500,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9392455220222473, 0.9467980265617371, 0.08...","[[[0.9392455220222473, 0.8777296543121338, 0.0...","[[0.9454331398010254, 0.9495590925216675, 0.17...","[[[0.9454331398010254, 0.8912692070007324, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
13,5ig7_abc_cut_A_Y66A,2.572738,95.767986,32.880000,2.450000,1.883553,95.502270,0.822819,0.331467,0.895267,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9482442736625671, 0.9485312104225159, 0.16...","[[[0.9482442736625671, 0.885511040687561, 0.06...","[[0.9459070563316345, 0.9496902823448181, 0.17...","[[[0.9459070563316345, 0.891128420829773, 0.07...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
14,5ig7_abc_cut_B_G114A,2.436673,95.869087,33.123333,2.460000,1.792361,95.856390,0.841049,0.310533,0.904167,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9472417831420898, 0.9477450847625732, 0.09...","[[[0.9472417831420898, 0.8837891817092896, 0.0...","[[0.9454723596572876, 0.9491568207740784, 0.17...","[[[0.9454723596572876, 0.8910244703292847, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
15,5ig7_abc_cut_B_L116A,2.697161,95.298420,31.386667,2.416667,2.103951,94.187333,0.801491,0.310067,0.860033,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9438903331756592, 0.9470524191856384, 0.08...","[[[0.9438903331756592, 0.879470705986023, 0.01...","[[0.9453369379043579, 0.9497691988945007, 0.17...","[[[0.9453369379043579, 0.8912421464920044, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
16,5ig7_abc_cut_B_V38A,2.540938,95.793462,46.020000,3.250000,1.948744,95.232639,0.816745,0.316667,0.892000,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9432534575462341, 0.9479488134384155, 0.09...","[[[0.9432534575462341, 0.8869456648826599, 0.0...","[[0.9457123875617981, 0.949378252029419, 0.174...","[[[0.9457123875617981, 0.89024418592453, 0.072...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
17,5ig7_abc_cut_B_W107A,3.561995,92.830579,100.306667,13.873333,2.270227,86.026669,0.390782,0.246067,0.475300,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9412914514541626, 0.9472916126251221, 0.09...","[[[0.9412914514541626, 0.8858029842376709, 0.0...","[[0.9455239772796631, 0.9491193890571594, 0.17...","[[[0.9455239772796631, 0.8903375864028931, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
18,5ig7_abc_cut_B_Y37A,2.644076,95.631059,31.833333,2.560000,1.877540,95.164646,0.778930,0.322100,0.874367,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9416530132293701, 0.9461093544960022, 0.09...","[[[0.9416530132293701, 0.8841282725334167, 0.0...","[[0.9443178176879883, 0.9490799307823181, 0.17...","[[[0.9443178176879883, 0.8913766145706177, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
19,5ig7_abc_cut_all_A,3.805987,92.210506,49.996667,7.456667,2.414636,81.956167,0.328881,0.253500,0.378033,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9479871988296509, 0.943764865398407, 0.091...","[[[0.9479871988296509, 0.8801519870758057, 0.0...","[[0.9454576969146729, 0.9486308097839355, 0.17...","[[[0.9454576969146729, 0.8897534608840942, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
20,5ijk_acx_cut,3.486349,92.439163,33.730000,4.226667,4.470284,77.156482,0.350599,0.199767,0.402267,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9452543258666992, 0.9524880051612854, 0.13...","[[[0.9452543258666992, 0.8906955122947693, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
21,5ijk_acx_cut_A_I112A,2.957804,94.094014,64.466667,11.166667,2.454107,83.096826,0.370337,0.223733,0.478033,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9419323205947876, 0.9515408277511597, 0.09...","[[[0.9419323205947876, 0.8887308239936829, 0.0...","[[0.9465927481651306, 0.9527407288551331, 0.13...","[[[0.9465927481651306, 0.8916440606117249, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
22,5ijk_acx_cut_A_I114A,3.581104,91.142842,64.580000,8.136667,3.360150,74.844415,0.310486,0.200900,0.305833,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9325439929962158, 0.951015830039978, 0.098...","[[[0.9325439929962158, 0.8848593235015869, 0.0...","[[0.9451525807380676, 0.9521574974060059, 0.13...","[[[0.9451525807380676, 0.8916072845458984, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
23,5ijk_acx_cut_A_K57A,3.333153,92.231214,70.016667,10.153333,3.337674,75.508519,0.310639,0.195867,0.342833,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9351347088813782, 0.9510679841041565, 0.09...","[[[0.9351347088813782, 0.8865579962730408, 0.0...","[[0.9464284181594849, 0.9522534012794495, 0.13...","[[[0.9464284181594849, 0.8884240388870239, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
24,5ijk_acx_cut_A_R55A,3.411108,91.770396,51.483333,6.956667,3.123322,73.418735,0.307887,0.185267,0.334967,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9349604845046997, 0.9504574537277222, 0.09...","[[[0.9349604845046997, 0.8808215260505676, 0.0...","[[0.9458076357841492, 0.9529669284820557, 0.13...","[[[0.9458076357841492, 0.891848087310791, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
25,5ijk_acx_cut_A_T113A,2.042686,97.319849,2.173333,-0.296667,1.401528,97.826782,0.814601,0.248467,0.944167,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9451172947883606, 0.9515537023544312, 0.09...","[[[0.9451172947883606, 0.8881925940513611, 0.0...","[[0.9464637041091919, 0.9521260857582092, 0.13...","[[[0.9464637041091919, 0.8910889029502869, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
26,5ijk_acx_cut_B_T113A,3.117051,92.444807,38.533333,3.923333,2.738743,80.009061,0.345256,0.191600,0.380267,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9378942847251892, 0.9510397911071777, 0.11...","[[[0.9378942847251892, 0.8857946395874023, 0.0...","[[0.9467201232910156, 0.9526268839836121, 0.13...","[[[0.9467201232910156, 0.8916904926300049, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
27,5ijk_acx_cut_B_W56A,2.382550,96.678663,9.290000,0.870000,1.598238,96.349787,0.707506,0.237233,0.869733,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9516229033470154, 0.9518455266952515, 0.11...","[[[0.9516229033470154, 0.8881137371063232, 0.0...","[[0.9466335773468018, 0.9514474272727966, 0.13...","[[[0.9466335773468018, 0.8913890719413757, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
28,5ijk_acx_cut_B_Y107A,3.163120,93.553850,32.103333,5.186667,2.038510,80.496129,0.316023,0.208467,0.392967,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9415576457977295, 0.9507483839988708, 0.10...","[[[0.9415576457977295, 0.892025351524353, 0.02...","[[0.9454445838928223, 0.9516614079475403, 0.13...","[[[0.9454445838928223, 0.8913754820823669, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
29,5ijk_acx_cut_B_Y108A,3.341985,91.641826,42.140000,5.580000,3.489597,73.981461,0.310483,0.192700,0.330300,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9349137544631958, 0.950394332408905, 0.093...","[[[0.9349137544631958, 0.8863245248794556, 0.0...","[[0.945480465888977, 0.9518694877624512, 0.136...","[[[0.945480465888977, 0.8908371925354004, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
30,5ijk_acx_cut_B_Y31A,3.093042,94.546322,33.070000,5.120000,2.123720,85.861336,0.331876,0.211233,0.511733,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9345048069953918, 0.9514862895011902, 0.09...","[[[0.9345048069953918, 0.8868847489356995, 0.0...","[[0.9461417198181152, 0.9522110223770142, 0.13...","[[[0.9461417198181152, 0.891068160533905, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
31,5ijk_acx_cut_B_Y38A,3.455154,91.808649,65.186667,9.836667,3.673191,76.971519,0.320673,0.201733,0.370600,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.9347723126411438, 0.9516543745994568, 0.09...","[[[0.9347723126411438, 0.8869415521621704, 0.0...","[[0.9460254311561584, 0.9520831108093262, 0.13...","[[[0.9460254311561584, 0.8908280730247498, 0.0...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...
32,5ijk_acx_cut_all_A,4.276973,90.392437,64.230000,6.276667,4.320635,77.275147,0.315294,0.220833,0.264500,...,False,"A,B",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...,"[[0.935025691986084, 0.944311797618866, 0.0957...","[[[0.935025691986084, 0.8839023113250732, 0.02...","[[0.946010947227478, 0.952307403087616, 0.1360...","[[[0.946010947227478, 0.8915120363235474, 0.03...",/scicore/home/schwede/barta0000/scoring_pipeli...,/scicore/home/schwede/barta0000/scoring_pipeli...

In [3]:
df_2if = df_1if.drop(columns=["binding", "interface","chai_unconstrained_model_path", "chai_constrained_model_path", "boltz_free_model_path", "boltz_template_model_path"])
df_2if

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,esmfold_esm3dg_dg_b,esmfold_esm3dg_dg_std,esmfold_mpnn_confidence,esmfold_mpnn_nll,esmfold_mpnn_nll_a,esmfold_mpnn_nll_b,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm
0,5ifj_abc_cut,2.593883,95.404666,28.410000,2.370000,1.988426,95.031040,0.824021,0.321900,0.872133,...,3.138038,0.218290,0.188899,1.707462,1.309943,2.104981,"[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9454320669174194, 0.9492036700248718, 0.17...","[[[0.9454320669174194, 0.8899917602539062, 0.0..."
1,5ifj_abc_cut_A_D111A,2.815847,95.282854,57.816667,3.936667,2.304955,94.104966,0.806316,0.302767,0.856633,...,3.096884,0.224287,0.193141,1.675427,1.333623,2.017231,"[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.9454193711280823, 0.9488046169281006, 0.17...","[[[0.9454193711280823, 0.8907997608184814, 0.0..."
2,5ifj_abc_cut_A_K110A,2.790728,94.871984,36.826667,3.240000,2.416944,92.917901,0.810150,0.296900,0.830000,...,3.015681,0.209554,0.194116,1.674882,1.299580,2.050184,"[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9449247717857361, 0.9489190578460693, 0.17...","[[[0.9449247717857361, 0.889130175113678, 0.07..."
3,5ifj_abc_cut_A_S64A,2.539446,95.613237,34.810000,2.686667,1.973646,95.207555,0.818178,0.312200,0.889533,...,3.052398,0.213692,0.190961,1.699475,1.282060,2.116890,"[[0.9445436000823975, 0.9495869874954224, 0.17...","[[[0.9445436000823975, 0.8924098014831543, 0.0...","[[0.945385217666626, 0.948758602142334, 0.1724...","[[[0.945385217666626, 0.8885297775268555, 0.07..."
4,5ifj_abc_cut_A_W52A,3.005329,94.814333,45.003333,4.813333,2.193750,92.632748,0.755118,0.311567,0.809633,...,3.156102,0.236498,0.185690,1.730604,1.315515,2.145692,"[[0.9452440142631531, 0.9471760392189026, 0.16...","[[[0.9452440142631531, 0.8792759776115417, 0.0...","[[0.9452540874481201, 0.9489129781723022, 0.17...","[[[0.9452540874481201, 0.8904703855514526, 0.0..."
5,5ifj_abc_cut_A_Y66A,2.701376,95.337838,32.103333,2.763333,2.138492,94.162554,0.805907,0.308767,0.858167,...,3.205366,0.209332,0.185966,1.727805,1.309762,2.145849,"[[0.9473956227302551, 0.9488828778266907, 0.16...","[[[0.9473956227302551, 0.8850024938583374, 0.0...","[[0.9453608989715576, 0.9489309191703796, 0.17...","[[[0.9453608989715576, 0.8903481960296631, 0.0..."
6,5ifj_abc_cut_B_L116A,2.806607,95.032996,30.606667,2.200000,2.177498,94.090785,0.793489,0.295733,0.844567,...,3.035983,0.208600,0.182653,1.745321,1.322374,2.168267,"[[0.9485109448432922, 0.9499985575675964, 0.17...","[[[0.9485109448432922, 0.8920019865036011, 0.0...","[[0.9452025294303894, 0.9490475058555603, 0.17...","[[[0.9452025294303894, 0.8905109763145447, 0.0..."
7,5ifj_abc_cut_B_V38A,2.714935,95.220947,37.886667,2.943333,2.238356,93.849034,0.803100,0.308100,0.858500,...,3.181652,0.208299,0.188240,1.712567,1.312490,2.112644,"[[0.9468277096748352, 0.9472519159317017, 0.10...","[[[0.9468277096748352, 0.8879522085189819, 0.0...","[[0.945318341255188, 0.9495519995689392, 0.177...","[[[0.945318341255188, 0.890434980392456, 0.072..."
8,5ifj_abc_cut_B_Y37A,3.004751,94.723352,19.743333,1.660000,2.273611,92.894702,0.721584,0.300000,0.815433,...,3.144416,0.244345,0.196540,1.665227,1.292638,2.037816,"[[0.940564751625061, 0.9448128938674927, 0.095...","[[[0.940564751625061, 0.8819113969802856, 0.04...","[[0.9450069665908813, 0.94929438829422, 0.1781...","[[[0.9450069665908813, 0.889803946018219, 0.07..."
9,5ifj_abc_cut_all_A,3.597543,93.235998,39.330000,4.260000,2.361091,86.447573,0.413262,0.275333,0.470667,...,2.979492,0.273020,0.193412,1.692783,1.275496,2.110071,"[[0.9467074275016785, 0.9420090913772583, 0.11...","[[[0.9467074275016785, 0.8753525018692017, 0.0...","[[0.9453179836273193, 0.9489884376525879, 0.17...","[[[0.9453179836273193, 0.8899396657943726, 0.0..."
10,5ig7_abc_cut,2.572969,95.599717,38.373333,2.653333,1.920729,95.341065,0.821896,0.317900,0.896167,...,2.954845,0.212535,0.184891,1.734242,1.313232,2.155251,"[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9455351233482361, 0.9491659998893738, 0.17...","[[[0.9455351233482361, 0.891846776008606, 0.07..."
11,5ig7_abc_cut_A_K110A,2.806122,94.950463,30.576667,2.670000,2.365965,93.257680,0.801589,0.312800,0.839000,...,2.880116,0.202406,0.189610,1.706069,1.294805,2.117333,"[[0.9444799423217773, 0.9482003450393677, 0.09...","[[[0.9444799423217773, 0.8866336941719055, 0.0...","[[0.9459781646728516, 0.9495248794555664, 0.17...","[[[0.9459781646728516, 0.8912208080291748, 0.0..."
12,5ig7_abc_cut_A_W52A,2.731340,95.457781,25.323333,2.083333,1.998690,94.535086,0.795046,0.325567,0.874500,...,2.965353,0.244786,0.187233,1.719450,1.316334,2.122566,"[[0.9392455220222473, 0.9467980265617371, 0.08...","[[[0.9392455220222473, 0.8777296543121338, 0.0...","[[0.9454331398010254, 0.9495590925216675, 0.17...","[[[0.9454331398010254, 0.8912692070007324, 0.0..."
13,5ig7_abc_cut_A_Y66A,2.572738,95.767986,32.880000,2.450000,1.883553,95.502270,0.822819,0.331467,0.895267,...,3.020486,0.213666,0.187966,1.712854,1.316195,2.109514,"[[0.9482442736625671, 0.9485312104225159, 0.16...","[[[0.9482442736625671, 0.885511040687561, 0.06...","[[0.9459070563316345, 0.9496902823448181, 0.17...","[[[0.9459070563316345, 0.891128420829773, 0.07..."
14,5ig7_abc_cut_B_G114A,2.436673,95.869087,33.123333,2.460000,1.792361,95.856390,0.841049,0.310533,0.904167,...,2.807459,0.228907,0.185193,1.735362,1.301415,2.169309,"[[0.9472417831420898, 0.9477450847625732, 0.09...","[[[0.9472417831420898, 0.8837891817092896, 0.0...","[[0.9454723596572876, 0.9491568207740784, 0.17...","[[[0.9454723596572876, 0.8910244703292847, 0.0..."
15,5ig7_abc_cut_B_L116A,2.697161,95.298420,31.386667,2.416667,2.103951,94.187333,0.801491,0.310067,0.860033,...,2.942762,0.218230,0.182366,1.746710,1.324846,2.168573,"[[0.9438903331756592, 0.9470524191856384, 0.08...","[[[0.9438903331756592, 0.879470705986023, 0.01...","[[0.9453369379043579, 0.9497691988945007, 0.17...","[[[0.9453369379043579, 0.8912421464920044, 0.0..."
16,5ig7_abc_cut_B_V38A,2.540938,95.793462,46.020000,3.250000,1.948744,95.232639,0.816745,0.316667,0.892000,...,2.965338,0.205608,0.188463,1.710756,1.314316,2.107196,"[[0.9432534575462341, 0.9479488134384155, 0.09...","[[[0.9432534575462341, 0.8869456648826599, 0.0...","[[0.9457123875617981, 0.949378252029419, 0.174...","[[[0.9457123875617981, 0.89024418592453, 0.072..."
17,5ig7_abc_cut_B_W107A,3.561995,92.830579,100.306667,13.873333,2.270227,86.026669,0.390782,0.246067,0.475300,...,2.955391,0.227355,0.187726,1.713577,1.318927,2.108226,"[[0.9412914514541626, 0.9472916126251221, 0.09...","[[[0.9412914514541626, 0.8858029842376709, 0.0...","[[0.9455239772796631, 0.9491193890571594, 0.17...","[[[0.9455239772796631, 0.8903375864028931, 0.0..."
18,5ig7_abc_cut_B_Y37A,2.644076,95.631059,31.833333,2.560000,1.877540,95.164646,0.778930,0.322100,0.874367,...,2.880589,0.233870,0.192974,1.688938,1.291303,2.086573,"[[0.9416530132293701, 0.9461093544960022, 0.09...","[[[0.9416530132293701, 0.8841282725334167, 0.0...","[[0.9443178176879883, 0.9490799307823181, 0.17...","[[[0.9443178176879883, 0.8913766145706177, 0.0..."
19,5ig7_abc_cut_all_A,3.805987,92.210506,49.996667,7.456667,2.414636,81.956167,0.328881,0.253500,0.378033,...,2.949232,0.251962,0.192118,1.693583,1.276929,2.110236,"[[0.9479871988296509, 0.943764865398407, 0.091...","[[[0.9479871988296509, 0.8801519870758057, 0.0...","[[0.9454576969146729, 0.9486308097839355, 0.17...","[[[0.9454576969146729, 0.8897534608840942, 0.0..."
20,5ijk_acx_cut,3.486349,92.439163,33.730000,4.226667,4.470284,77.156482,0.350599,0.199767,0.402267,...,2.509422,0.183531,0.214035,1.611258,1.105336,2.117180,"[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9452543258666992, 0.9524880051612854, 0.13...","[[[0.9452543258666992, 0.8906955122947693, 0.0..."
21,5ijk_acx_cut_A_I112A,2.957804,94.094014,64.466667,11.166667,2.454107,83.096826,0.370337,0.223733,0.478033,...,2.687798,0.166294,0.213049,1.616696,1.113003,2.120390,"[[0.9419323205947876, 0.9515408277511597, 0.09...","[[[0.9419323205947876, 0.8887308239936829, 0.0...","[[0.9465927481651306, 0.9527407288551331, 0.13...","[[[0.9465927481651306, 0.8916440606117249, 0.0..."
22,5ijk_acx_cut_A_I114A,3.581104,91.142842,64.580000,8.136667,3.360150,74.844415,0.310486,0.200900,0.305833,...,2.462533,0.189100,0.213465,1.599422,1.163705,2.035139,"[[0.9325439929962158, 0.951015830039978, 0.098...","[[[0.9325439929962158, 0.8848593235015869, 0.0...","[[0.9451525807380676, 0.9521574974060059, 0.13...","[[[0.9451525807380676, 0.8916072845458984, 0.0..."
23,5ijk_acx_cut_A_K57A,3.333153,92.231214,70.016667,10.153333,3.337674,75.508519,0.310639,0.195867,0.342833,...,2.795398,0.236031,0.210176,1.632712,1.118614,2.146809,"[[0.9351347088813782, 0.9510679841041565, 0.09...","[[[0.9351347088813782, 0.8865579962730408, 0.0...","[[0.9464284181594849, 0.9522534012794495, 0.13...","[[[0.9464284181594849, 0.8884240388870239, 0.0..."
24,5ijk_acx_cut_A_R55A,3.411108,91.770396,51.483333,6.956667,3.123322,73.418735,0.307887,0.185267,0.334967,...,2.729907,0.237577,0.207755,1.641400,1.146517,2.136283,"[[0.9349604845046997, 0.9504574537277222, 0.09...","[[[0.9349604845046997, 0.8808215260505676, 0.0...","[[0.9458076357841492, 0.9529669284820557, 0.13...","[[[0.9458076357841492, 0.891848087310791, 0.03..."
25,5ijk_acx_cut_A_T113A,2.042686,97.319849,2.173333,-0.296667,1.401528,97.826782,0.814601,0.248467,0.944167,...,2.552660,0.221140,0.208146,1.633083,1.169772,2.096394,"[[0.9451172947883606, 0.9515537023544312, 0.09...","[[[0.9451172947883606, 0.8881925940513611, 0.0...","[[0.9464637041091919, 0.9521260857582092, 0.13...","[[[0.9464637041091919, 0.8910889029502869, 0.0..."
26,5ijk_acx_cut_B_T113A,3.117051,92.444807,38.533333,3.923333,2.738743,80.009061,0.345256,0.191600,0.380267,...,2.634778,0.228606,0.205434,1.674588,1.096105,2.253071,"[[0.9378942847251892, 0.9510397911071777, 0.11...","[[[0.9378942847251892, 0.8857946395874023, 0.0...","[[0.9467201232910156, 0.9526268839836121, 0.13...","[[[0.9467201232910156, 0.8916904926300049, 0.0..."
27,5ijk_acx_cut_B_W56A,2.382550,96.678663,9.290000,0.870000,1.598238,96.349787,0.707506,0.237233,0.869733,...,2.449254,0.188619,0.210980,1.621961,1.129850,2.114071,"[[0.9516229033470154, 0.9518455266952515, 0.11...","[[[0.9516229033470154, 0.8881137371063232, 0.0...","[[0.9466335773468018, 0.9514474272727966, 0.13...","[[[0.9466335773468018, 0.8913890719413757, 0.0..."
28,5ijk_acx_cut_B_Y107A,3.163120,93.553850,32.103333,5.186667,2.038510,80.496129,0.316023,0.208467,0.392967,...,2.536124,0.211703,0.204704,1.660162,1.128113,2.192212,"[[0.9415576457977295, 0.9507483839988708, 0.10...","[[[0.9415576457977295, 0.892025351524353, 0.02...","[[0.9454445838928223, 0.9516614079475403, 0.13...","[[[0.9454445838928223, 0.8913754820823669, 0.0..."
29,5ijk_acx_cut_B_Y108A,3.341985,91.641826,42.140000,5.580000,3.489597,73.981461,0.310483,0.192700,0.330300,...,2.673023,0.225190,0.207797,1.653247,1.104259,2.202236,"[[0.9349137544631958, 0.950394332408905, 0.093...","[[[0.9349137544631958, 0.8863245248794556, 0.0...","[[0.945480465888977, 0.9518694877624512, 0.136...","[[[0.945480465888977, 0.8908371925354004, 0.03..."
30,5ijk_acx_cut_B_Y31A,3.093042,94.546322,33.070000,5.120000,2.123720,85.861336,0.331876,0.211233,0.511733,...,2.722084,0.219074,0.218507,1.584546,1.105573,2.063519,"[[0.9345048069953918, 0.9514862895011902, 0.09...","[[[0.9345048069953918, 0.8868847489356995, 0.0...","[[0.9461417198181152, 0.9522110223770142, 0.13...","[[[0.9461417198181152, 0.891068160533905, 0.03..."
31,5ijk_acx_cut_B_Y38A,3.455154,91.808649,65.186667,9.836667,3.673191,76.971519,0.320673,0.201733,0.370600,...,2.518887,0.193468,0.223153,1.569658,1.053925,2.085391,"[[0.9347723126411438, 0.9516543745994568, 0.09...","[[[0.9347723126411438, 0.8869415521621704, 0.0...","[[0.9460254311561584, 0.9520831108093262, 0.13...","[[[0.9460254311561584, 0.8908280730247498, 0.0..."
32,5ijk_acx_cut_all_A,4.276973,90.392437,64.230000,6.276667,4.320635,77.275147,0.315294,0.220833,0.264500,...,2.104933,0.177596,0.187110,1.740616,1.243517,2.237715,"[[0.935025691986084, 0.944311797618866, 0.0957...","[[[0.935025691986084, 0.8839023113250732, 0.02...","[[0.946010947227478, 0.952307403087616, 0.1360...","[[[0.946010947227478, 0.8915120363235474, 0.03..."

## master df

##### snir

In [5]:
# for snir data
master_df = pd.read_csv(MASTER_PATH, delimiter=';')
master_df

,source,type,sample,fab,interface,vh/vl,target,target_residues,target_sequence,binder,KD[M],notes
0,snir_ab,original,5ifj_abc_cut,1000.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
1,snir_ab,original,5ifj_abc_cut,1000.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_E,NaN,PLQPEQPFP,1,0.000010,Fab 1E03 + KD[M] approximated from Snir et. al...
2,snir_ab,original,5ig7_abc_cut,10.0,"A,C",EVQLLESGGGLVQPGGSLRLSCAASGFTFSTYAMSWVRQAPGKGLE...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
3,snir_ab,original,5ig7_abc_cut,10.0,"B,C",QLVLTQSPSASASLGASVRLTCTLSSGHSSYVIAWHQQQSEKGPRY...,gliadin_alpha_Q,NaN,PLQPQQPFP,1,0.000100,Fab 1E01 + KD[M] approximated from Snir et. al...
4,snir_ab,original,5ijk_acx_cut,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,1,0.000001,Fab 1E01 + KD[M] approximated from Snir et. al...
...,...,...,...,...,...,...,...,...,...,...,...,...
65,snir_ab,alanine_scan,5ijk_acx_cut_B_Y108A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
66,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
67,snir_ab,alanine_scan,5ijk_acx_cut_B_Y31A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLASSNNKNYLAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
68,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"A,C",EVQLVESGGGLVKPGGSLRLSCAASGFTFSNAWFNWVRQAPGKGLE...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN
69,snir_ab,alanine_scan,5ijk_acx_cut_B_Y38A,10.0,"B,C",DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNALAWYQQKP...,gliadin_gamma_E,NaN,LQPEQPFP,0,NaN,NaN

In [6]:
master_df2 = master_df.drop(columns=["interface", "fab", "vh/vl", "target", "target_residues", "target_sequence", "notes"])
master_df2

     source          type                sample  binder     KD[M]
0   snir_ab      original          5ifj_abc_cut       1  0.000010
1   snir_ab      original          5ifj_abc_cut       1  0.000010
2   snir_ab      original          5ig7_abc_cut       1  0.000100
3   snir_ab      original          5ig7_abc_cut       1  0.000100
4   snir_ab      original          5ijk_acx_cut       1  0.000001
..      ...           ...                   ...     ...       ...
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
66  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
68  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

[70 rows x 5 columns]

In [7]:
master_df3 = master_df2.drop_duplicates(keep="last")
master_df3

     source          type                sample  binder     KD[M]
1   snir_ab      original          5ifj_abc_cut       1  0.000010
3   snir_ab      original          5ig7_abc_cut       1  0.000100
5   snir_ab      original          5ijk_acx_cut       1  0.000001
7   snir_ab  alanine_scan  5ifj_abc_cut_A_D111A       0       NaN
9   snir_ab  alanine_scan  5ifj_abc_cut_A_K110A       0       NaN
11  snir_ab  alanine_scan   5ifj_abc_cut_A_S64A       0       NaN
13  snir_ab  alanine_scan   5ifj_abc_cut_A_W52A       0       NaN
15  snir_ab  alanine_scan   5ifj_abc_cut_A_Y66A       0       NaN
17  snir_ab  alanine_scan    5ifj_abc_cut_all_A       0       NaN
19  snir_ab  alanine_scan  5ifj_abc_cut_B_L116A       0       NaN
21  snir_ab  alanine_scan   5ifj_abc_cut_B_V38A       0       NaN
23  snir_ab  alanine_scan  5ifj_abc_cut_B_W107A       0       NaN
25  snir_ab  alanine_scan   5ifj_abc_cut_B_Y37A       0       NaN
27  snir_ab  alanine_scan  5ig7_abc_cut_A_K110A       0       NaN
29  snir_ab  alanine_scan   5ig7_abc_cut_A_W52A       0       NaN
31  snir_ab  alanine_scan   5ig7_abc_cut_A_Y66A       0       NaN
33  snir_ab  alanine_scan    5ig7_abc_cut_all_A       0       NaN
35  snir_ab  alanine_scan  5ig7_abc_cut_B_G114A       0       NaN
37  snir_ab  alanine_scan  5ig7_abc_cut_B_L116A       0       NaN
39  snir_ab  alanine_scan   5ig7_abc_cut_B_V38A       0       NaN
41  snir_ab  alanine_scan  5ig7_abc_cut_B_W107A       0       NaN
43  snir_ab  alanine_scan   5ig7_abc_cut_B_Y37A       0       NaN
45  snir_ab  alanine_scan  5ijk_acx_cut_A_I112A       0       NaN
47  snir_ab  alanine_scan  5ijk_acx_cut_A_I114A       0       NaN
49  snir_ab  alanine_scan   5ijk_acx_cut_A_K57A       0       NaN
51  snir_ab  alanine_scan   5ijk_acx_cut_A_R55A       0       NaN
53  snir_ab  alanine_scan  5ijk_acx_cut_A_T113A       0       NaN
55  snir_ab  alanine_scan    5ijk_acx_cut_all_A       0       NaN
57  snir_ab  alanine_scan   5ijk_acx_cut_B_K36A       0       NaN
59  snir_ab  alanine_scan  5ijk_acx_cut_B_T113A       0       NaN
61  snir_ab  alanine_scan   5ijk_acx_cut_B_W56A       0       NaN
63  snir_ab  alanine_scan  5ijk_acx_cut_B_Y107A       0       NaN
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

##### mcmahon / germinal

In [8]:

master_df= pd.read_csv(MASTER_PATH, delimiter=',')
#master_df = master.drop(columns=["Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17"])
master_df.head()

master_df.to_csv("/home/bri/pymol/data/harvey/harvey_master.csv", index=False )

In [9]:
AMBIGUOUS_TARGET= "HSA"   # test

def create_sample_id(row):
    vhh = str(row['vhh'])
    target = str(row['target'])
    residues = str(row['target_residues'])
    
    # Check if target is (ambigous target, meaning the same target has different version --> target residues are needed to be able to identify it, the only one for now is HSA) to apply the specific naming convention
    if target == AMBIGUOUS_TARGET:
        return f"{vhh}_{target}_{residues}"
    else:
        return f"{vhh}_{target}"

# 1. Create the 'sample' column in the master table
master_df['sample'] = master_df.apply(create_sample_id, axis=1)
master_df

,source,type,vhh,vhh_sequence,target,target_residues,target_sequence,binder,KD[M],EC50[M],notes,sample
0,harvey,original,AT118i4h32,EVQLVESGGGLVQPGGSLRLSCAASGYIYRRYRMGWYRQAPGKGRE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1.0,NaN,NaN,8TH3,AT118i4h32_AGTR1
1,harvey,original,AT201,QVQLQESGGGLVQAGGSLRLSCAASGTISDPPYMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1.0,NaN,NaN,NaN,AT201_AGTR1
2,harvey,original,AT202,QVQLQESGGGLVQAGGSLRLSCAASGYIFDLPYMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1.0,NaN,NaN,NaN,AT202_AGTR1
3,harvey,original,AT203,QVQLQESGGLVQAGGSLRLSCAASGYISRSYDMGWYRQAPGKEREL...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1.0,NaN,NaN,NaN,AT203_AGTR1
4,harvey,original,AT204,QVQLQESGGGLVQAGGSLRLSCAASGYIFTRGFMGWYRQAPGKERE...,AGTR1,1-359,MILNSSTEDGIKRIQDDCPKAGRHNYIFVMIPTLYSIIFVVGIFGN...,1.0,NaN,NaN,NaN,AT204_AGTR1
...,...,...,...,...,...,...,...,...,...,...,...,...
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan_nan
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan_nan
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan_nan
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan_nan
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan_nan

In [11]:
master_df3.head()

    source      type        sample     fab interface  binder     KD[M]
0  snir_ab  original  5ifj_abc_cut  1000.0       A,C       1  0.000010
1  snir_ab  original  5ifj_abc_cut  1000.0       B,C       1  0.000010
2  snir_ab  original  5ig7_abc_cut    10.0       A,C       1  0.000100
3  snir_ab  original  5ig7_abc_cut    10.0       B,C       1  0.000100
4  snir_ab  original  5ijk_acx_cut    10.0       A,C       1  0.000001

In [12]:
master_df4 = master_df3.drop(columns=["fab", "interface"]) #, "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17"])

master_df4

     source          type                sample  binder     KD[M]
0   snir_ab      original          5ifj_abc_cut       1  0.000010
1   snir_ab      original          5ifj_abc_cut       1  0.000010
2   snir_ab      original          5ig7_abc_cut       1  0.000100
3   snir_ab      original          5ig7_abc_cut       1  0.000100
4   snir_ab      original          5ijk_acx_cut       1  0.000001
..      ...           ...                   ...     ...       ...
65  snir_ab  alanine_scan  5ijk_acx_cut_B_Y108A       0       NaN
66  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
67  snir_ab  alanine_scan   5ijk_acx_cut_B_Y31A       0       NaN
68  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN
69  snir_ab  alanine_scan   5ijk_acx_cut_B_Y38A       0       NaN

[70 rows x 5 columns]

### merge

In [13]:
scores_df = pd.merge(master_df4, df_2if, on=['sample'], how='inner')
#df = pd.merge(master_df2, preds_df, on=['sample'], how='inner')
# Display the first few rows to verify
print(scores_df[['sample', 'af3_plddt']])

# Save the merged result
scores_df.to_csv(OUTPUT_DIR /'merged_snir.csv', index=False)

                  sample  af3_plddt
0           5ifj_abc_cut  95.404666
1           5ifj_abc_cut  95.404666
2           5ig7_abc_cut  95.599717
3           5ig7_abc_cut  95.599717
4           5ijk_acx_cut  92.439163
..                   ...        ...
61  5ijk_acx_cut_B_Y108A  91.641826
62   5ijk_acx_cut_B_Y31A  94.546322
63   5ijk_acx_cut_B_Y31A  94.546322
64   5ijk_acx_cut_B_Y38A  91.808649
65   5ijk_acx_cut_B_Y38A  91.808649

[66 rows x 2 columns]