#### all

In [ ]:
# TO DO: organize (as a module), add save/load functions, add tests, add docstrings, add type hints, add logging, add CLI interface
import config
import pandas as pd


def load_and_join_predictions(org_path, ts_path=None, keep_interfaces=None, preds_path=config.PREDS_PATH,):
    """Load predictions from originals CSV and optionally target_shuffle CSV.

    Args:
        org_path: Path to originals CSV
        ts_path: Optional path to target_shuffle CSV
        keep_interfaces: Optional set of interfaces to keep. Default = {"A,B"}
        preds_path: Optional path to save the resulting CSV
    """
    # Load original dataframe
    org_df = pd.read_csv(org_path)

    # Optionally load and concatenate target_shuffle dataframe
    if ts_path is not None:
        ts_df = pd.read_csv(ts_path)
        df = pd.concat([org_df, ts_df], ignore_index=True)
    else:
        df = org_df.copy()

    # Filter interfaces
    if keep_interfaces is None:
        keep_interfaces = {"A,B"}

    df = df[df["interface"].str.strip().isin(keep_interfaces)].copy()

    # Save if output path is provided
    if preds_path:
        df.to_csv(preds_path, index=False)

    return df

# default (the ds wildcards should be specified in config...)
#df = load_and_join_predictions('/scicore/home/schwede/barta0000/mcmahon_ds/originals/predictionsv5.csv', '/scicore/home/schwede/barta0000/mcmahon_ds/target_shuffle/predictionsv4.csv')


# Use default interface "A,B" with specific output path
#df = load_and_join_predictions('/scicore/home/schwede/barta0000/mcmahon_ds/originals/predictions.csv', '/scicore/home/schwede/barta0000/mcmahon_ds/target_shuffle/predictions.csv', preds_path='/scicore/home/schwede/barta0000/project/data/raw/preds_mcmahon2.csv')

# Or use config.KEEP_INTERFACES to filter specific interfaces
df = load_and_join_predictions('/scicore/home/schwede/barta0000/alphaseq_ds/test/predictions.csv', keep_interfaces=config.KEEP_INTERFACES, preds_path=config.PREDS_PATH)

print(f"Loaded {len(df)} rows. Interfaces: {df['interface'].unique()}")
df.head()

In [ ]:
# Load data
df_if = pd.read_csv(config.PREDS_PATH)
df_if.info()

In [ ]:
# TO DO: refactor to a function (it selects numeric columns and aggregates them by mean, while taking the first value of other columns)
def aggregate_predictions(df_if):
    num_cols = df_if.select_dtypes(include=['number']).columns
    other_cols = [c for c in df_if.columns if c not in num_cols and c != 'sample']

    agg_dict = {col: 'mean' for col in num_cols}
    agg_dict.update({col: 'first' for col in other_cols})
    return agg_dict

agg_dict = aggregate_predictions(df_if)
df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

df_1if.info()
df_1if.head()

/scratch/ipykernel_3412983/577471144.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_1if = df_if.groupby('sample').agg(agg_dict).reset_index()

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,binding,interface,chai_unconstrained_model_path,chai_constrained_model_path,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm,boltz_free_model_path,boltz_template_model_path
0,N1.10_RBM-1,3.858878,90.448146,65.16,5.67,3.740000,79.326973,0.182499,0.1842,0.2619,...,False,"A,B",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...,"[[0.8971477746963501, 0.08495928347110748]]","[[[0.8971477746963501, 0.010165227577090263], ...","[[0.9095517992973328, 0.08663083612918854]]","[[[0.9095517992973328, 0.023061230778694153], ...",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...
1,N1.10_RBM-2,4.171958,87.653520,49.47,6.45,2.834375,75.758121,0.101203,0.0939,0.2726,...,False,"A,B",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...,"[[0.8964142203330994, 0.08152760565280914]]","[[[0.8964142203330994, 0.008266166783869267], ...","[[0.9134353399276733, 0.08305077999830246]]","[[[0.9134353399276733, 0.011391742154955864], ...",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...
2,N1.1_RBM-1,5.206876,84.964047,103.52,9.98,5.215000,71.865072,0.112917,0.0899,0.1133,...,False,"A,B",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...,"[[0.9044861793518066, 0.0836571529507637]]","[[[0.9044861793518066, 0.008903898298740387], ...","[[0.9045647382736206, 0.08411453664302826]]","[[[0.9045647382736206, 0.010531282983720303], ...",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...
3,N1.1_RBM-2,5.518893,84.762485,17.59,1.85,5.475000,77.024845,0.233053,0.1370,0.1531,...,False,"A,B",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...,"[[0.9053446054458618, 0.08255389332771301]]","[[[0.9053446054458618, 0.008160410448908806], ...","[[0.9032577276229858, 0.08267711102962494]]","[[[0.9032577276229858, 0.012340253219008446], ...",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...
4,N1.2_RBM-1,5.555026,84.368306,206.27,18.06,4.697059,69.079469,0.085150,0.0895,0.1249,...,False,"A,B",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...,"[[0.8977466225624084, 0.08535739779472351]]","[[[0.8977466225624084, 0.009244095534086227], ...","[[0.9060524702072144, 0.09880343824625015]]","[[[0.9060524702072144, 0.03468354046344757], [...",/scicore/home/schwede/barta0000/peptide_ds/ori...,/scicore/home/schwede/barta0000/peptide_ds/ori...

In [ ]:
# TO DO: refactor to a function (it drops unnecessary columns)
def drop_unnecessary_columns(df):
    return df.drop(columns=config.COLS_TO_DROP)

df_2if = drop_unnecessary_columns(df_1if)
df_2if.info()
df_2if.head()

df_2if.to_csv(config.RAW_DATA_DIR / 'predictions_2if.csv', index=False)

,sample,af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,af3_ipsae,af3_pdockq,af3_pdockq2,...,esmfold_esm3dg_dg_b,esmfold_esm3dg_dg_std,esmfold_mpnn_confidence,esmfold_mpnn_nll,esmfold_mpnn_nll_a,esmfold_mpnn_nll_b,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm
0,N1.10_RBM-1,3.858878,90.448146,65.16,5.67,3.740000,79.326973,0.182499,0.1842,0.2619,...,1.423596,0.191821,0.110297,2.204581,1.390948,3.018214,"[[0.8971477746963501, 0.08495928347110748]]","[[[0.8971477746963501, 0.010165227577090263], ...","[[0.9095517992973328, 0.08663083612918854]]","[[[0.9095517992973328, 0.023061230778694153], ..."
1,N1.10_RBM-2,4.171958,87.653520,49.47,6.45,2.834375,75.758121,0.101203,0.0939,0.2726,...,0.070937,0.126172,0.107594,2.229390,1.374719,3.084061,"[[0.8964142203330994, 0.08152760565280914]]","[[[0.8964142203330994, 0.008266166783869267], ...","[[0.9134353399276733, 0.08305077999830246]]","[[[0.9134353399276733, 0.011391742154955864], ..."
2,N1.1_RBM-1,5.206876,84.964047,103.52,9.98,5.215000,71.865072,0.112917,0.0899,0.1133,...,1.388996,0.182289,0.112099,2.188370,1.379588,2.997152,"[[0.9044861793518066, 0.0836571529507637]]","[[[0.9044861793518066, 0.008903898298740387], ...","[[0.9045647382736206, 0.08411453664302826]]","[[[0.9045647382736206, 0.010531282983720303], ..."
3,N1.1_RBM-2,5.518893,84.762485,17.59,1.85,5.475000,77.024845,0.233053,0.1370,0.1531,...,-0.163115,0.155643,0.122415,2.100342,1.367087,2.833597,"[[0.9053446054458618, 0.08255389332771301]]","[[[0.9053446054458618, 0.008160410448908806], ...","[[0.9032577276229858, 0.08267711102962494]]","[[[0.9032577276229858, 0.012340253219008446], ..."
4,N1.2_RBM-1,5.555026,84.368306,206.27,18.06,4.697059,69.079469,0.085150,0.0895,0.1249,...,1.336663,0.212934,0.098800,2.314660,1.447490,3.181830,"[[0.8977466225624084, 0.08535739779472351]]","[[[0.8977466225624084, 0.009244095534086227], ...","[[0.9060524702072144, 0.09880343824625015]]","[[[0.9060524702072144, 0.03468354046344757], [..."